### ISSUE TITLE
Bug : carriage router is breaking the tokenizer

### ISSUE THREAD

**Issue by abarre** [jakubpawlowicz/clean-css#1000]
Our solution minifies CSS from various websites and some CSS have carriage return (`\r`) without the new line character (`\n`). This character breaks the tokenizer. The only patch I found is removing all (\r) with a replace statement before applying clean-css.

### Environment

* clean-css version - `npm ls clean-css`: clean-css@4.1.9
* node.js version - `node -v`: v8.9.4
* operating system: Mac OS

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
level: { 1: {all:false}}
})
```

### Input CSS
```css
\r@media only screen and (max-width: 1250px) {#aspot-standard {width: 100%;}}
```
**Please note the '\r' before the '@'.**

### Actual output CSS

```css
@media only screen and (max-width: 1250px){}
```

### Expected output CSS

```css
@media only screen and (max-width: 1250px){#aspot-standard{width:100%}}
```
