### ISSUE TITLE
Question: rules on one line

### ISSUE THREAD

**Issue by rowild** [jakubpawlowicz/clean-css#1004]
I am trying to find out how I can preserve one-liners. When processing SCSS there is the "compact" formatting rule. But when using this this, empty lines are kept. So I wonder how to improve this layout with cleanCss, either by:
- applying some "keep one liners" rule; or:
- removing empty lines.

So far my research and tests remain unsuccessful, so I dare to ask here hoping that someone can point me into the right direction. Thank you in advance!

**Comment by jakubpawlowicz** [comment]
@rowild - could you give me an example how your input looks like and how expected output should look like? It may already be covered by https://github.com/jakubpawlowicz/clean-css#formatting-options but without seeing an example I can't really tell.

**Comment by rowild** [comment]
Oh... now that's long ago... but I think I wanted to achieve a result like this:
```css
/* Desired resuls */
.colPrim { color: #fff; }
.colSec { color: #444; }
.bgColPrim { color: #e5e5e5; }
```
(Phantasy code...)
So all classes that have only should remain in one line (at least, when the original SCSS is written like that), and at the same time there should not be any empty lines between those classes:

```css
/* Not desired result, because of empty lines
.colPrim { color: #fff; }

.colSec { color: #444; }

.bgColPrim { color: #e5e5e5; }

```
Hope this makes it clearer:
But - I seem to have had too much time. This is really not important, just sugar on the cake, so please feel free to close this issue!!! :-)
