### ISSUE TITLE
Bug : pseudo selector with a space is corrupted after minification

### ISSUE THREAD

**Issue by abarre** [jakubpawlowicz/clean-css#1007]
A pseudo selector :not is corrupted after minification. To be frank, I never saw this CSS syntax. It may be wrong but it seems to be correctly interpreted by the browser.

### Environment

* clean-css version - `npm ls clean-css`: clean-css@4.1.9
* node.js version - `node -v`: v8.9.4
* operating system: Mac OS

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
level: { 1: {all:false}}
})
```

### Input CSS
```css
.gfr body:not(dockbar aui) {
    color: #2ecc71
}
```

### Actual output CSS

```css
.gfr body:not(dockbaraui) {
    color: #2ecc71
}
```

### Expected output CSS

```css
.gfr body:not(dockbar aui) {
    color: #2ecc71
}
```
