### ISSUE TITLE
removing rules

### ISSUE THREAD

**Issue by tadward** [jakubpawlowicz/clean-css#1013]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* node.js version - `6.10.3`:
* operating system: Mac Sierra
* gulp-clean-css - `3.9.3`

### Configuration options

```return gulp.src(source)
    .pipe(cleancss({
      sourceMap: true,
      level: {
        2: {
          mergeSemantically: true,
        }
      }
    }))
```

### Input CSS

```css
button,.btn {
	margin: 0;
	padding: 12px;
	color: #fff;
	line-height: 1rem;
	border: none;
	border-radius: var(--border-radius);
	text-transform: uppercase;
	cursor: pointer;
	transition: all 0.2s;
}
```

### Actual output CSS

```css
.btn {
	/* styles from above */
}
```

### Expected output CSS

```css
button,.btn {
	/* styles from above */
}
```

It is removing button from my complied file. If I switch the order to ```css .btn,button``` it removes the .btn and keeps just button
