### ISSUE TITLE
Deactivate placeholder or other pseudoclasses/pseudoelements

### ISSUE THREAD

**Issue by dulcetti** [jakubpawlowicz/clean-css#1014]
### Precheck
 
Hi guys.

My component uses SASS with Webpack with `sass-loader`, `ExtractTextPlugin`, `clean-css` and `clean-css-loader`. In development files work without problems. But when I build the component to the production version, with minified files, Internet Explorer execute with bugs on placeholder.

### Environment

* clean-css version - `4.1.11`:
* node.js version - `v6.11.4`:
* operating system: Windows 10 :(

### Configuration options

* Basic Configuration

### Input SASS

```css
.field-container
    > .field-group
        > .field
            &::placeholder
                color: rgba(#fff, 0)
                transition: color .1s
```

### Actual output development version CSS

```css
.field-container > .field-group > .field:-ms-input-placeholder {
  color: rgba(255, 255, 255, 0);
  transition: color .1s; }
.field-container > .field-group > .field::-ms-input-placeholder {
  color: rgba(255, 255, 255, 0);
  transition: color .1s; }
```

This configuration works fine, but the production version...

### Actual output production version CSS

```css
.field-container>.field-group>.field:-ms-input-placeholder,.field-container>.field-group>.field::-ms-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}
```

### Expected output production CSS

```css
.field-container>.field-group>.field:-ms-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}.field-container>.field-group>.field::-ms-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}
```

The Internet Explorer don't works fine when have both selectors with comma:

```css
.field-container > .field-group > .field:-ms-input-placeholder, .field-container > .field-group > .field::-ms-input-placeholder
```

If has separated declaration, works ok, but together with comma, no. I can disabled the version `::-ms-input-placeholder` inside clean-css? Or configure to make separated the two versions?

The bug runs on Internet Explore 10 and 11. Edge works fine.

**Comment by dulcetti** [comment]
Well, it worked. I don't see in documentation about this, but I put the preffix/pseudoelement after the general preffixer and worked:
```css
&::placeholder
    color: rgba($placeholder-color, 0)
    transition: color .1s

    &:-ms-input-placeholder
        color: rgba($placeholder-color, 0)
        transition: color .1s
```
Now, the selectors are separated:
```css
.field-container>.field-group>.field::-webkit-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}.field-container>.field-group>.field::-ms-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}.field-container>.field-group>.field::placeholder{color:hsla(0,0%,100%,0);transition:color .1s}.field-container>.field-group>.field:-ms-input-placeholder{color:hsla(0,0%,100%,0);transition:color .1s}
```
I'am posting this answer maybe someone have the same trouble.

Regards
