### ISSUE TITLE
SVG styles are being ignored

### ISSUE THREAD

**Issue by adityatj** [jakubpawlowicz/clean-css#1021]
Hello,

Firstly thank you for the awesome library.

My issue is with the svg styles being skipped/not appearing in the final output CSS.

I use a grunt plugin `grunt-contrib-cssmin`

### Environment

* grunt-contrib-cssmin version - 2.2.1
* clean-css version - 4.1.11
* node.js version - 6.11.3
* operating system: Windows 8

### Input CSS

```css
.node:hover circle {
    r: 18;
    stroke: orange;
}
```

### Actual output CSS

```css
.node:hover circle {
    stroke: orange;
}
```

### Expected output CSS

```css
.node:hover circle {
    r: 18;
    stroke: orange;
}
```
