### ISSUE TITLE
mergeIntoShorthands ordering

### ISSUE THREAD

**Issue by iamchucky** [jakubpawlowicz/clean-css#1022]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported; yes
* do a quick check if the bug still exists in the latest patch version; yes
* finally, be nice and have fun! 

### Environment

* clean-css version - `npm ls clean-css`: clean-css@4.1.11
* node.js version - `node -v`: v8.9.4
* operating system: macOS 10.13.3

### Configuration options
https://github.com/angular/angular-cli/blob/1.7.x/packages/@angular/cli/plugins/cleancss-webpack-plugin.ts#L38
```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: 'ie9',
  level: 2,
  inline: false,
  returnPromise: true,
  sourceMap: this._options.sourceMap,
})
```

### Input CSS

```css
.link-block {
  border-color: red;
  background-color: black;
  color: white;
  border-width: 5px;
  border-style: solid;

  font-style: italic;

  border-top: 0;
  border-right: 0;
  border-left: 0;
}
```

### Actual output CSS

```css
.link-block {
  background-color:#000;
  color:#fff;
  font-style:italic;
  border-top:0;
  border-right:0;
  border-left:0;
  border:5px solid red
}
```

### Expected output CSS

```css
.link-block{
  background-color:#000;
  color:#fff;
  border:5px solid red;
  font-style:italic;
  border-top:0;
  border-right:0;
  border-left:0
}
```

related issue in Angular CLI: https://github.com/angular/angular-cli/issues/10186
