### ISSUE TITLE
"merge components into shorthand properties" (level 2) causes invalid repetition of !import

### ISSUE THREAD

**Issue by pocketjoso** [jakubpawlowicz/clean-css#1032]
Hi again, continuous thanks for providing this excellent library! Long time since I last found a bug, but here's a new one, hoping it will be easy to fix. :)

### Environment

* clean-css version - `npm ls clean-css`:
`clean-css@4.1.11`. Also reproduced via online demo (https://jakubpawlowicz.github.io/clean-css/)
* node.js version - `node -v`:
10.0.0 (also online demo)
* operating system:
MacOS (also online demo)

### Configuration options
I run with `level: 2`, but I broke it down more specifically to the `merge components into shorthand properties` being responsible, via the online demo.

### Input CSS

```css
div {
    border-color: currentColor!important;
    border-radius: 0!important;
    border-style: none!important;
    border-width: medium!important;
    list-style-type: inherit!important;
    list-style-position: outside!important;
    list-style-image: none!important;
}

```

### Actual output CSS

```css
div{border-radius:0!important;border:currentColor!important!important!important;border:currentColor!important!important!important;border:currentColor!important!important!important;list-style:outside;list-style-type:inherit!important}
```
This broken rule repeats badly, taking up more and more space the larger the file. It made the original css file about 3 times larger than before clean-css (before I pruned it for debugging and presenting here).

### Expected output CSS
Haven't reviewed this with 100% certainty; the main thing is just to not have the incorrect `!important!important`.. repetition. But it also seems that there is a missing `important` on the `list-style` property.

```css
div{border-radius:0!important;border:currentColor;list-style:outside!important;list-style-type:inherit!important}

```
