### ISSUE TITLE
clean-css appears to strip @font-face declarations

### ISSUE THREAD

**Issue by chadarsenault** [jakubpawlowicz/clean-css#1035]
### Environment

* clean-css version - `npm ls clean-css`:  4.1.11
* node.js version - `node -v`: 6.9.4
* operating system:

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: 'ie10'
})
```

### Input CSS

```css
@font-face {
  font-family: 'FontAwesome';
  src: url('/fontawesome-webfont.eot?v=4.7.0');
  src: url('/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'),
    url('/fontawesome-webfont.woff2?v=4.7.0') format('woff2'),
    url('/fontawesome-webfont.woff?v=4.7.0') format('woff'),
    url('/fontawesome-webfont.ttf?v=4.7.0') format('truetype'),
    url('/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
    //  src: url('/FontAwesome.otf') format('opentype'); // used when developing fonts
   font-weight: normal;
   font-style: normal;
}

.fa {
  display: inline-block;
  font: normal normal normal 10px/1 FontAwesome; // shortening font declaration
  font-size: inherit; // can't have font-size inherit on line above, so need to override
  text-rendering: auto; // optimizelegibility throws things off #1094
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.fa-lg {
  font-size: (4em / 3);
  line-height: (3em / 4);
  vertical-align: -15%;
}
.fa-2x { font-size: 2em; }
.fa-3x { font-size: 3em; }
.fa-4x { font-size: 4em; }
.fa-5x { font-size: 5em; }

/* ... and so on for a thousand+ lines of font class declarations, the rest isn't important */
```

### Actual output CSS

```css
.fa{display:inline-block;font:normal normal normal 10px/1 FontAwesome;font-size:inherit;text-rendering:auto;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.fa-lg{font-size:1.33333em;line-height:.75em;vertical-align:-15%}.fa-2x{font-size:2em}.fa-3x{font-size:3em}
/* Note the @font-face declaration has been stripped */
```

### Expected output CSS

```css
@font-face {  font-family: 'FontAwesome';  src: url("/fontawesome-webfont.eot?v=4.7.0");  src: url("/fontawesome-webfont.eot?#iefix&v=4.7.0") format("embedded-opentype"), url("/fontawesome-webfont.woff2?v=4.7.0") format("woff2"), url("/fontawesome-webfont.woff?v=4.7.0") format("woff"), url("/fontawesome-webfont.ttf?v=4.7.0") format("truetype"), url("/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular") format("svg");  font-weight: normal;  font-style: normal;}.fa{display:inline-block;font:normal normal normal 10px/1 FontAwesome;font-size:inherit;text-rendering:auto;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.fa-lg{font-size:1.33333em;line-height:.75em;vertical-align:-15%}.fa-2x{font-size:2em}.fa-3x{font-size:3em}
/*...*/
```
