### ISSUE TITLE
Font-variation-settings getting quotes stripped & shouldn't

### ISSUE THREAD

**Issue by jpamental** [jakubpawlowicz/clean-css#1038]
I've found that the new `font-variation-settings` CSS attribute is getting quotes stripped out when it should not (it should work just like `font-feature-settings`, which are handled properly). I found the line and included a change below.

### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: v4.1.11
* node.js version - `node -v`: v8.11.3
* operating system: Mac OS High Sierra

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  // compatibility: 'ie8',
  // format: 'keep-breaks',
  // level: 2
})
```

### Input CSS

```css
h2 {
 font-variation-settings: 'wght' 600 'opz' 48;
}
```

### Actual output CSS

```css
h2 {
 font-variation-settings: wght 600 opz 48;
}

```

### Expected output CSS

```css
h2 {
 font-variation-settings: 'wght' 600 'opz' 48;
}
```

I found the line in /lib/optimizer/level-1/optimize.js, line 337:
`if (name == 'content' || name.indexOf('font-feature-settings') > -1 ||`

if changed to this:

`if (name == 'content' || name.indexOf('font-variation-settings') > -1 || name.indexOf('font-feature-settings') > -1 ||`

fixes the issue
