### ISSUE TITLE
Slash removed when url is enclosed within brackets

### ISSUE THREAD

**Issue by prayashm** [jakubpawlowicz/clean-css#1045]
URLs wierd conversion of // to /
### Environment
* clean-css version - `npm ls clean-css`: 4.1.7
* node.js version - `node -v`: v8.10.0
* operating system: Ubuntu 16.04

### Configuration options
```js
var CleanCSS = require('clean-css');
new CleanCSS({})
```

### Input CSS
```css
div {
    background-image: url([//abc.com/image.png])
}
```

### Actual output CSS
```css
div{background-image:url([/abc.com/image.png])}
```

### Expected output CSS
```css
div{background-image:url([//abc.com/image.png])}
```
