### ISSUE TITLE
transition shorthand unit lost when level is 2

### ISSUE THREAD

**Issue by hsuanxyz** [jakubpawlowicz/clean-css#1050]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version: `4.2.x`
* node.js version: `v10.0.0`
* operating system:  `darwin x64`

### Configuration options

```js
var CleanCSS = require('clean-css');
var input = `
.a {
  transition: opacity .3s linear, height 0s ease .3s;
}

.b {
  transition: opacity .3s linear, height 1s ease .3s;
}
`;

var options = {
  compatibility: 'ie9',
  level        : 2,
  inline       : false,
  returnPromise: true,
  sourceMap    : true,
};

new CleanCSS(options).minify(input)
  .then(output => {
    console.log(output.styles)
  });

```

### Input CSS

```css
.a {
  transition: opacity .3s linear, height 0s ease .3s;
}

.b {
  transition: opacity .3s linear, height 1s ease .3s;
}
```

### Actual output CSS

```css
.a{transition:opacity .3s linear,height .3s}.b{transition:opacity .3s linear,height 1s .3s}
```

### Expected output CSS

```css
.a{transition:opacity .3s linear,height  0s ease .3s}.b{transition:opacity .3s linear,height 1s ease .3s}
```
