### ISSUE TITLE
Width set with calc cut off in `width style color` shorthand properties

### ISSUE THREAD

**Issue by yggg** [jakubpawlowicz/clean-css#1053]
### Environment

* clean-css version - `4.2.1`:
* node.js version - `10.13.0`:
* operating system: macOS 10.14

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: {
    2: { all: false },
  },
})
```

### Input CSS

```css
.width-style-color-props {
  border: calc(1px) solid blue;
  outline: calc(1px) solid blue;
}
```

### Actual output CSS

```css
.width-style-color-props {
  border: solid #00f;
  outline: #00f solid;
}
```

### Expected output CSS

```css
.width-style-color-props {
  border: calc(1px) solid #00f;
  outline: calc(1px) solid #00f;
}
```

`_widthFilter` which is used by `widthStyleColor` function to get width part, excludes `calc` with `!validator.isDynamicUnit(value[1])` statement, for some reason.
https://github.com/jakubpawlowicz/clean-css/blob/887ac0e2d1f10e16663edf0719153f18597824d5/lib/optimizer/level-2/break-up.js#L61
Is it intentional? I believe it's a valid css since `calc` [can be used wherever length values are allowed.](https://www.w3.org/TR/css-values/#calc-notation)
