### ISSUE TITLE
Incorrect output with 4-digit-hex

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [jakubpawlowicz/clean-css#1055]
### Environment

Online tool 
### Configuration options

```
Level 2, merge semantically, restructure rules, ie7 compatibility
```

### Input CSS

```css
blockquote {
	color: #696969;
	color: rgba(68, 68, 68, 0.8);
	color: #444c;
}
```

### Actual output CSS

```
blockquote {
	color: rgba(68,68,68,.8);
	color: #444c
}
```

### Expected output CSS

```
blockquote {
	color: #696969;
	color: rgba(68,68,68,.8);
	color: #444c
}
```
