### ISSUE TITLE
Identifier with starting underscore considered incorrect

### ISSUE THREAD

**Issue by oranmor** [jakubpawlowicz/clean-css#1056]
### Environment

Online tool

### Configuration options

Level 2, merge semantically, remove unused @ at rules, restructure rules

### Input CSS

```css
@keyframes _loading {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.load {
  animation: _loading 8s steps(8) infinite;
}
```

### Actual output CSS

Empty

### Expected output CSS

```css
@keyframes _loading{from{transform:rotate(0)}to{transform:rotate(360deg)}}.load{animation:8s steps(8) infinite _loading}
```
### Explanation

If we change animation name from `_loading` to `loading`, then everything works as expected. So it seems that the animation identifier with starting underscore is considered incorrect. However, it is correct according to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident#Examples).
As far as I understand, problem can be solved by fixing `identifierRegex` in lib/optimizer/validator.js
