### ISSUE TITLE
@font-face src:local(".. Black ..") gets replaced with ".. #000 .."

### ISSUE THREAD

**Issue by dr-itz** [jakubpawlowicz/clean-css#1058]
### Environment

* clean-css@4.2.1
* node.js v10.14.1
* operating system: Windows 7

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({})
```

### Input CSS

```css
`@font-face {
  font-family: "Some Sans";
  font-weight: bold;
  font-style: italic;
  src: local("Some Sans Black Italic");
}
```

When `local` is any string that contains a color name with spaces on both sides of the string, the name gets replaced with the color value. If e.g. it just ends with a color name, the incorrect replacement does not happen.

### Actual output CSS

```css
@font-face{font-family:"Some Sans";font-weight:700;font-style:italic;src:local("Some Sans #000 Italic")}
```

### Expected output CSS

```css
@font-face{font-family:"Some Sans";font-weight:700;font-style:italic;src:local("Some Sans Black Italic")}
```

**Comment by Sirius-A** [comment]
I am also facing this problem. PR with a suggested fix here #1077

**Comment by manniL** [comment]
The same problem occurs when you don't have quotes around the font-family, which is also valid CSS (and often the end output from minimizers like cssnano).

```css
 .title { font-family: Some Sans Black }
```
