### ISSUE TITLE
CSS calculations do not work for inline animation delay

### ISSUE THREAD

**Issue by mariusvlas** [jakubpawlowicz/clean-css#1059]
### Environment

* clean-css version - `npm ls clean-css`:
4.2.1 (using with angular-cli 7.2.3)
* node.js version - `node -v`: 11.2.0
* operating system: macOS 10.13.6

### Configuration options
(using with angular-cli 7.2.3)
clean-css configs are found in /node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.js
```js
const CleanCSS = require('clean-css');
new CleanCSS({
                compatibility: 'ie9',
                level: {
                    2: {
                        skipProperties: ['transition'] // Fixes #12408
                    }
                },
                inline: false,
                returnPromise: true,
                sourceMap: this._options.sourceMap,
            });
```

### Input CSS

```css
/* the shorter the better! */

@keyframes someAnimationName {
  0% {
    transform: translateY(-50px) scale(0.8, 0);
  }
}
some-element {
  animation: someAnimationName 0.3s calc(0.04s * 2) linear 1 backwards;
}
```
or
```css
some-element {
  animation: someAnimationName 0.3s (0.04s * 2) linear 1 backwards;
}
```

### Actual output CSS

```css
some-element{}
```

### Expected output CSS

```css
some-element{animation:.3s linear calc(0.04s * 2) backwards someAnimationName}
```

Please note that separately setting the `animation-delay: calc(0.04s * 2)` works.
Only the inline animation delay makes the whole line completely ignored.
