### ISSUE TITLE
Variable !important is replaced with none when level 2 is enabled

### ISSUE THREAD

**Issue by pawelkondraciuk** [jakubpawlowicz/clean-css#1060]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `4.2.1`:
* node.js version - `8.11.3`:
* operating system: macOS 10.14.1

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
:root {
  --border-test: 1px solid red;
}
.u-test {
  border-left: var(--border-test) !important;
}
```

### Actual output CSS

```css
:root{--border-test:1px solid red}.u-test{border-left:none!important}
```

### Expected output CSS

```css
:root{--border-test:1px solid red}.u-test{border-left:var(--border-test)!important}
```

### Notes
Without `!important` flag it compiles to 
```css
:root{--border-test:1px solid red}.u-test{border-left:var(--border-test)}
```
