### ISSUE TITLE
:host-context selectors are being optimized incorrectly in level 2

### ISSUE THREAD

**Issue by alan-agius4** [jakubpawlowicz/clean-css#1062]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `4.2.1`:
* node.js version - `10.12`:
* operating system: Win32

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
    compatibility: 'ie9',
    level: 2,
    format: {
        aroundSelectorRelation: false,
    },
    inline: false,
    returnPromise: true,
    sourceMap: this._options.sourceMap,
});
```

### Input CSS

```css
:host-context(selector selector){
	color: red;
}
```

### Actual output CSS

```css
:host-context(selectorselector){color:red}
```

### Expected output CSS

```css
:host-context(selector selector){color:red}
```
