### ISSUE TITLE
level 2 (even with all: false) incorrectly re-orders animation name

### ISSUE THREAD

**Issue by leeoniya** [jakubpawlowicz/clean-css#1072]
ping @jakubpawlowicz

```js
let css = `
    .spinner {
        animation: x .5s infinite linear;
    }
`
var CleanCSS = require('clean-css');
var input = css;

var options = {
    level: {
        2: {all: false}
    }
};

var output = new CleanCSS(options).minify(input);

console.log(output.styles);
```

actual:

```css
.spinner{animation:.5s linear infinite x}
```

expected:

```css
.spinner{animation:x .5s infinite linear}
```

works as expected without level 2
