### ISSUE TITLE
reopen border with rpx

### ISSUE THREAD

**Issue by NewFuture** [jakubpawlowicz/clean-css#1073]
### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 10.x
* operating system: windows/liunx

### Input CSS

```css
.c{
  border: 2rpx solid #ddd;
}
```

### Actual output CSS

```css
.c{
  border: solid #ddd;
}
```

### Expected output CSS

```css
.c{
  border: 2rpx solid #ddd;
}
```
related #882 

As we know that `rpx` is not a standard css unit，
but it's a valid unit in [wxss](https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxss.html#unit-of-measurement) and some processors.

How to keep it in the clean result?

1. a config to ignore the unknown unit?
2. extend  `units`  config to support user-defined unit？
