### ISSUE TITLE
mediaMerging breaking behavior with css variables

### ISSUE THREAD

**Issue by rickysandoval** [jakubpawlowicz/clean-css#1075]
With css-variables, media query variable definitions don't overrule non-media query variable definitions, so if at the same level of specificity the value is determined by order in the stylesheet. In the case below with mediaMerging enabled, the merged media query is placed above where it normally would and so is overwritten by the non media query definition.

Here's what happens:
https://codepen.io/rickysandoval/pen/WBgPZE

### Environment

* clean-css version - `4.2.1`:
* node.js version - `v8.9.4`:
* operating system: macOS Mojave

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
    level: {
        2: {}
      }
})
```

### Input CSS

```css
@media (min-width: 48em) {
    .unrelated-share-media-query {
        font-size: 5px;
    }
}

.filler {
    font-size: 15px;
}

.defines-variable {
    --max-items: 1;
    --col-width: calc(100%/var(--max-items));

    display: flex;
    width: calc(100% + 20px);
    flex-wrap: wrap;
}

.uses-variable {
    flex-basis: var(--col-width);
}

@media (min-width: 48em) {
  .defines-variable {
      --max-items: 3;
  }
}
```

### Actual output CSS

```css
@media (min-width:48em) {
	.unrelated-share-media-query {
		font-size: 5px
	}
	.defines-variable {
		--max-items: 3
	}
}

.filler {
	font-size: 15px
}

.defines-variable {
	--max-items: 1;
	--col-width: calc(100%/var(--max-items));
	display: flex;
	width: calc(100% + 20px);
	flex-wrap: wrap
}

.uses-variable {
	flex-basis: var(--col-width)
}
```

### Expected output CSS

```css
.filler {
	font-size: 15px
}

.defines-variable {
	--max-items: 1;
	--col-width: calc(100%/var(--max-items));
	display: flex;
	width: calc(100% + 20px);
	flex-wrap: wrap
}

.uses-variable {
	flex-basis: var(--col-width)
}

@media (min-width:48em) {
	.unrelated-share-media-query {
		font-size: 5px
	}
	.defines-variable {
		--max-items: 3
	}
}
```

**Comment by jakubpawlowicz** [comment]
This issue is fixed now.

Please note that the correct CSS output is:

```css
@media (min-width: 48em) {
    .unrelated-share-media-query {
        font-size: 5px;
    }
}

.filler {
    font-size: 15px;
}

.defines-variable {
    --max-items: 1;
    --col-width: calc(100%/var(--max-items));

    display: flex;
    width: calc(100% + 20px);
    flex-wrap: wrap;
}

.uses-variable {
    flex-basis: var(--col-width);
}

@media (min-width: 48em) {
  .defines-variable {
      --max-items: 3;
  }
}
```

as you cannot move `.unrelated-share-media-query` block down because it defines `font-size` and `.filler` block just below redefines is. Unfortunately there can be an HTML element with `class="filler unrelated-share-media-query"` which in original CSS will always have a `15px` font size, while in the other one it won't.
