### ISSUE TITLE
Quotes removed from single column grid definitions 

### ISSUE THREAD

**Issue by veleek** [jakubpawlowicz/clean-css#1078]
If you define a single column CSS grid using the `grid` property (instead of the explicit grid-template-areas/rows/columns), the quotes get removed from the the grid area names which results in invalid CSS (as far as I can tell).  

The minified CSS fails to render properly in both Chrome and Firefox whereas the regular CSS renders as expected.  Quotes are NOT removed when using `grid-template-areas` property which was fixed in #917.

Note: I'm running this through gulp, but I don't have any special configuration for clean-css.  I can figure out how to do it directly if necessary.

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 12.3.1
* operating system: Windows

### Configuration options

```js
const { src, dest, series, } = require('gulp');
const rename = require('gulp-rename');
const cleanCSS = require('gulp-clean-css');

const minifyCss = () => {
    return src('./test.css')
        .pipe(cleanCSS({ rebase: false }))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(dest(f => f.base));
}

exports.default = series(minifyCss);
```

### Input CSS

```css
#wrapper {
    display: grid;
    grid:
        "logo" auto
        "nav" auto
        "content" 1fr
        / 1fr;
}
```

### Actual output CSS

```css
#wrapper{display:grid;grid:logo auto nav auto content 1fr/1fr}
```

### Expected output CSS

```css
#wrapper{display:grid;grid:"logo" auto "nav" auto "content" 1fr/1fr}
```
