### ISSUE TITLE
Numbers in URLs getting mangled

### ISSUE THREAD

**Issue by mattbasta** [jakubpawlowicz/clean-css#108]
``` css
p {background: url(/foo/1.0/img.png)}
```

ends up as

``` css
p {background: url(/foo/1/img.png)}
```

String values should never be manipulated.
