### ISSUE TITLE
Incorrect border transform makes border disappear

### ISSUE THREAD

**Issue by mashedcode** [jakubpawlowicz/clean-css#1090]
### Environment

clean-css version 4.2.1 (clean-css-cli -O2 from master)

### Input CSS

```css
.test {
        border-color: currentcolor currentcolor rgb(148, 148, 148);
        border-image: none 100% / 1 / 0 stretch;
        border-width: 0px 0px 1px;
        border-style: none none solid;
}
```

### Actual output CSS

```css
.test{border-image:none 100%/1/0 stretch;border:0 currentcolor}
```

### Expected output CSS

```css
.test{border-color:#949494;border-width:0 0 1px;border-style:solid}
```
or
```css
.test{border:0;border-bottom:1px solid #949494}
```
