### ISSUE TITLE
Relatives paths getting Broken (../ being stripped from paths)

### ISSUE THREAD

**Issue by taibhse-designs** [jakubpawlowicz/clean-css#1100]
No matter what I try, the ../ gets stripped from the image path resulting in a broken link and no image being displayed.

### Configuration options
Clean CSS is part of the minify plugin / extension for Brackets, configs appear to be all defaults I think.

### Input CSS

```css
.hire-me {
    background: url("../images/hire.jpg");
}
```

### Actual output CSS

```
.hire-me {background: url(images/hire.jpg);}
```

### Expected output CSS

```
.hire-me {background: url(../images/hire.jpg);}
```
