### ISSUE TITLE
Multi-value CSS involving 'unset' is changed into an invalid CSS

### ISSUE THREAD

**Issue by totoguy** [jakubpawlowicz/clean-css#1103]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 12.13.0
* operating system: Windows 10

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: 'ie9',
  level: {
     2: {
        skipProperties: [
           'transition', 
           'font', 
        ],
     },
  },
  inline: false,
  returnPromise: true,
  sourceMap: this._options.sourceMap,
})
```

### Input CSS

```css
.some-class {
   padding: unset;
   padding-right: 30px;
}
```

### Actual output CSS

```css
.some-class {
   padding: unset 30px unset unset;
}
```

### Expected output CSS

```css
.some-class {
   padding: unset;
   padding-right: 30px;
}
```
