### ISSUE TITLE
4.2.2 breaking bug - mal search pattern for replacing rgba to hexdecimal

### ISSUE THREAD

**Issue by miao-yu** [jakubpawlowicz/clean-css#1106]
The css I have:
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(30,87,153,1)), color-stop(50%,rgba(41,137,216,1)), color-stop(51%,rgba(32,124,202,1)), color-stop(100%,rgba(125,185,232,1))); 

The css compiled after by 4.2.2, ')' missing.
background:-webkit-gradient(linear,left top,left bottom,color-stop(0,#1e5799,color-stop(50%,#2989d8,color-stop(51%,#207cca,color-stop(100%,#7db9e8);

**Comment by jakubmazanec** [comment]
I was just going to report the same issue (version 4.2.2).

Example code:
```js
let fs = require('fs');
let CleanCSS = require('clean-css');
let output = new CleanCSS().minify(`
.foo {
  background-image: linear-gradient(to right, rgba(255,255,255,0), rgba(255,255,255,1));
  pointer-events: none;
}
`);

fs.writeFileSync('./output.css', output.styles);
```

Output:
```css
.foo{background-image:linear-gradient(to right,rgba(255,255,255,0),#fff;pointer-events:none}
```

Expected output:
```css
.foo{background-image:linear-gradient(to right,rgba(255,255,255,0),#fff);pointer-events:none}
```
