### ISSUE TITLE
@Keyframes removed even they are used

### ISSUE THREAD

**Issue by Frankusky** [jakubpawlowicz/clean-css#1111]
### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 10.13.0
* operating system: Windows 10

### Configuration options
Im using gulp-clean-css, with all level 1 and 2 enabled

### Input CSS

```css
i.icoArrow:before {
  animation: arrowSmall ease 1s infinite;
  opacity: 0.5;
  transform: scale(0.8);
}
i.icoArrow:after {
  animation: arrowBig ease 1s infinite;
  right: 10px;
}

@media screen and (max-width: 1023px) {
  .item:hover i.icoArrow:before {
    opacity: 1;
  }
}
@keyframes arrowBig {
  0% {
    opacity: 0;
    transform: translateX(-30px);
  }
  25% {
    opacity: 1;
  }
  65% {
    opacity: 1;
  }
  100% {
    opacity: 0;
    transform: translateX(0);
  }
}
@keyframes arrowSmall {
  0% {
    opacity: 0;
    transform: translateX(-28px) scale(0.8);
  }
  10% {
    transform: translateX(-28px) scale(0.8);
  }
  65% {
    opacity: 0.5;
  }
  100% {
    opacity: 0;
    transform: translateX(0) scale(0.8);
  }
}

```

### Actual output CSS

Keyframes are not on the minified version (the whole minified version its too big to add it here)

### Expected output CSS

Keyframes should be on the minified version.

### Aditional information

I found that if you remove the hover rule on the media query the keyframes wont be deleted
