### ISSUE TITLE
Level 2 Optimization drops multiple transition properties

### ISSUE THREAD

**Issue by wclaibor** [jakubpawlowicz/clean-css#1115]
### Environment

* clean-css version - `npm ls clean-css`: -- clean-css@4.2.3
* node.js version - `node -v`: v12.13.0
* operating system: Windows

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
.a {
    transition-property: transform, margin-left;
    transition-delay: 0ms;
    transition-duration: 375ms;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}
```

### Actual output CSS

```css
.a{transition:transform 375ms cubic-bezier(.4,0,.2,1)}
```

### Expected output CSS

```css
.a {
    transition-property: transform, margin-left;
    transition-delay: 0ms;
    transition-duration: 375ms;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}
```
