### ISSUE TITLE
CSS functions with value "0px" are converted to "0"

### ISSUE THREAD

**Issue by reiallenramos** [jakubpawlowicz/clean-css#1117]
Some CSS functions such as `max()`, `min()`, and `clamp()` do not recognize "0" as a valid value therefore resulting in "Invalid property value" error.

![clean_css_bug](https://user-images.githubusercontent.com/26242729/82292145-e01be200-99dc-11ea-9d91-b8c30df4b5d6.png)

### Environment

* clean-css version - `npm ls clean-css`: clean-css@3.4.28
* node.js version - `node -v`: v10.16.3
* operating system: Ubuntu 18.04

### Configuration options
I used [clean-css-cli](https://github.com/jakubpawlowicz/clean-css-cli) to replicate the behavior: `cleancss -o cleaned.min.css clean_me.css`

### Input CSS (clean_me.css)

```css
.my-class {
  width: max(0px, 30px);
}
```

### Actual output CSS (cleaned.min.css)

```css
.my-class{width:max(0,30px)}
```

### Expected output CSS

```css
.my-class{width:max(0px,30px)}
```
Note: the second value "30px" is a contrived example and just used to simplify bug replication. In the real world, we use something like `calc()`.
