### ISSUE TITLE
Semicolon removed even when enabling semicolonAfterLastProperty

### ISSUE THREAD

**Issue by curbengh** [jakubpawlowicz/clean-css#1118]
### Environment

* clean-css version - `npm ls clean-css`: 4.2.3
* node.js version - `node -v`: 12.16.3
* operating system: Solus

### Configuration options

```js
new CleanCSS({
  format: 'beautify',
  level: {
    1: {
      semicolonAfterLastProperty: true
    }
  }
})
```

### Input CSS

```css
a {
  margin-top: 1em;
  margin-bottom: 1em;
}
```

### Actual output CSS

```css
a {
  margin-top: 1em;
  margin-bottom: 1em
}
```

### Expected output CSS

```css
a {
  margin-top: 1em;
  margin-bottom: 1em;
}
```
