### ISSUE TITLE
Space appended to "() value

### ISSUE THREAD

**Issue by curbengh** [jakubpawlowicz/clean-css#1119]
### Environment

* clean-css version - `npm ls clean-css`: 4.2.3
* node.js version - `node -v`: 12.16.3
* operating system: Solus

### Configuration options

```js
new CleanCSS({
  format: 'beautify'
})
```

### Input CSS

```css
a::before {
  content: "\"()";
}
```

### Actual output CSS

```css
a::before {
  content: ""() ";
}
```

### Expected output CSS

```css
a::before {
  content: ""()";
}
```
