### ISSUE TITLE
DataURI without optional <mediatype> part incorrectly put inside single quote

### ISSUE THREAD

**Issue by awarecan** [jakubpawlowicz/clean-css#1122]
* clean-css version - `npm ls clean-css`: 4.2.3
* node.js version - `node -v`: 12.16.2
* operating system: Mac

### Configuration options

```js
var CleanCSS = require('clean-css');
var input = "@font-face{font-family:'B';src:url(\"data:;base64,SEVMTE8=\")}";
var output = new CleanCSS({}).minify(input);
```

### Input CSS

```css
@font-face {
    font-family: 'B';
    src: url("data:;base64,SEVMTE8=");
}
```

### Actual output CSS

```css
@font-face{font-family:'B';src:url("'data:;base64,SEVMTE8='")}
```

### Expected output CSS

```css
@font-face{font-family:'B';src:url(data:;base64,SEVMTE8=)}
```

Per [RFC 2397](https://tools.ietf.org/html/rfc2397), `<mediatype>` is optional in data uri. `data:;base64` is valid, should not be put inside single quote.

It is a special case of #676
