### ISSUE TITLE
Quotes incorrectly stripped from font-*-settings when used in @supports

### ISSUE THREAD

**Issue by tylergaw** [jakubpawlowicz/clean-css#1125]
### Precheck
 
* ✅ Do a quick search and make sure a bug has not yet been reported;
* ✅ (seeing it in 4.2.3) do a quick check if the bug still exists in the latest patch version;
* 💃 finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: `4.2.3`
* node.js version - `node -v`: `12.16.3`
* operating system: `macOS 10.15.4`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({});
```

### Input CSS

```css
@supports (font-feature-settings: "liga" 0) {
  html {
    --font: "font-with-features", helvetica, sans-serif;
  }
}

@supports (font-variation-settings: "wdth" 285) {
  html {
    --font: "variable-font", helvetica, sans-serif;
  }
}
```

### Actual output CSS

```css
@supports (font-feature-settings:liga 0) {html {--font: "font-with-features", helvetica, sans-serif;}}
@supports (font-variation-settings:wdth 285) {html {--font: "variable-font", helvetica, sans-serif;}}
```

### Expected output CSS

```css
@supports (font-feature-settings:"liga" 0) {html {--font: "font-with-features", helvetica, sans-serif;}}
@supports (font-variation-settings:"wdth" 285) {html {--font: "variable-font", helvetica, sans-serif;}}
```

For feature detection to work on those properties the first value–liga, wdth, etc–must be in quotes.

In #1038, `font-variation-settings` quoting as a property was reported and fixed in #1039. That works as expected, but that doesn't fix the quoting when these props are used within `@supports`.

**Comment by tylergaw** [comment]
A note for anyone that lands here. If you need to work around this you can use `ignore:start|end` documented at https://github.com/jakubpawlowicz/clean-css#how-to-keep-a-css-fragment-intact to keep these feature queries as is. 

Example:

```css
/* clean-css ignore:start */
@supports (font-variation-settings: "wdth" 285) {
  html {
    --font: "variable-font", helvetica, sans-serif;
  }
}
/* clean-css ignore:end */
```

I'm using this on project to detect variable font support and works as expected.
