### ISSUE TITLE
Second animation lost when transformed to shorthand

### ISSUE THREAD

**Issue by fotijr** [jakubpawlowicz/clean-css#1126]
### Environment

* clean-css version - `npm ls clean-css`: 4.2.3
* node.js version - `node -v`: 14.12.0
* operating system: macOS 10.13.6

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
.test {
  animation-name: show, showAgain;
  animation-duration: 1s, 1.7s;
  animation-timing-function: linear, linear;
  animation-fill-mode: forwards, forwards;
  animation-delay: 0s, 2.5s;
  animation-iteration-count: 1, 1;
  animation-direction: normal, normal;
  animation-play-state: running, running;
}

@keyframes show {
  0% {
    visibility: hidden;
  }
  1% {
    visibility: visible;
  }
  100% {
    visibility: hidden;
  }
}
@keyframes showAgain {
  0% {
    visibility: hidden;
  }
  1% {
    visibility: visible;
  }
  100% {
    visibility: hidden;
  }
}
```

### Actual output CSS

```css
.test{animation:1s linear forwards show}@keyframes show{0%,100%{visibility:hidden}1%{visibility:visible}}@keyframes showAgain{0%,100%{visibility:hidden}1%{visibility:visible}}
```

### Expected output CSS

```css
.test{animation-name:show,showAgain;animation-duration:1s,1.7s;animation-timing-function:linear,linear;animation-fill-mode:forwards,forwards;animation-delay:0s,2.5s;animation-iteration-count:1,1;animation-direction:normal,normal;animation-play-state:running,running}@keyframes show{0%,100%{visibility:hidden}1%{visibility:visible}}@keyframes showAgain{0%,100%{visibility:hidden}1%{visibility:visible}}
```

### Explanation
When using multiple animations in long form, in some scenarios an animation is stripped out since clean-css tries to reduce it to shorthand format. This scenario seems a bit strange, but I needed identical keyframe animations to work around a Safari bug.
