### ISSUE TITLE
@import in comment breaks minification

### ISSUE THREAD

**Issue by apfelbox** [jakubpawlowicz/clean-css#113]
``` css
/* @import */
a { color: red; }
```

Expected output:

``` css
a{color:red}
```

Actual output:

``` css
/*}
```

Used version:

``` bash
$ /usr/local/share/npm/lib/node_modules/clean-css/bin/cleancss -v
1.0.8
```
