### ISSUE TITLE
Level 2 merges any `:not()` even when it leads to incompatibility

### ISSUE THREAD

**Issue by PetrP** [jakubpawlowicz/clean-css#1132]
The level 2 does not consider selector inside of the `:not()` with mergeablePseudoClasses or mergeablePseudoElements (from /lib/options/compatibility.js) and merges the selectors which may lead to incompatibility because the whole rule is dropped if it contains an invalid pseudo-element.

I think it affects following options:
mergeAdjacentRules
mergeNonAdjacentRules
reduceNonAdjacentRules
restructureRules (default is false)
So to bypass this bug, set all of those to false.

### Environment

* clean-css version: 4.2.3
* node.js version: v12.18.1
* operating system: windows

### Configuration options

```js
const CleanCSS = require('clean-css');
const source = 'a:not(:-moz-focusring) {outline:0}\na:not(:focus-visible) {outline:0}';
const options = {
	level: {
		2: {
			all: false,
			mergeAdjacentRules: true,
			removeEmpty: true,
		},
	},
};
const output = new CleanCSS(options).minify(source);
```

### Input CSS

```css
a:not(:-moz-focusring) {outline:0}
a:not(:focus-visible) {outline:0}
```

### Actual output CSS

```css
a:not(:-moz-focusring),a:not(:focus-visible){outline:0}
```

### Expected output CSS

```css
a:not(:-moz-focusring){outline:0}a:not(:focus-visible){outline:0}
```
