### ISSUE TITLE
CleanCSS add extra `%` when calculate color from css variable inside hsl

### ISSUE THREAD

**Issue by Farsad** [jakubpawlowicz/clean-css#1133]
CleanCSS adds extra `%` just after css variable name in calculation of color by css variable for hsl.

### Environment

* clean-css version - `4.2.3`:
* node.js version - `v12.18.3`:
* operating system: macOs

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
   level: 1
})
```

### Input CSS

```css
.test{
    color: hsl(0, 0%, calc((var(--button_color_l) - 65) * -100%)) !important;
}
```

### Actual output CSS

```css
.test{color:hsl(0, 0%, calc((var(--button_color_l%) - 65) * -100%))!important}
```

### Expected output CSS

```css
.test{color:hsl(0, 0%, calc((var(--button_color_l) - 65) * -100%))!important}
```

A temporary solution:
```csss
color: hsl(0, 0%, calc(-100% * (var(--button_color_l) - 65))) !important;
```
swap the values to bring percentage before the css var
