### ISSUE TITLE
clean-css 5.0.1 leading zeros are not removed

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#1143]
### Environment

* clean-css version - `npm ls clean-css`: 5.0.1
* node.js version - `node -v`: 14.15.5
* operating system: Windows 10

### Configuration options

```sh
cleancss -O1 specialComments:0 -o 2.css 1.css
```

### Input CSS

* https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css

```css
kbd {
  padding: 0.2rem 0.4rem;
  font-size: 0.875em;
  color: #fff;
  background-color: #212529;
  border-radius: 0.2rem;
}
```

### Actual output CSS

```css
kbd{padding:.2rem .4rem;font-size:.875em;color:#fff;background-color:#212529;border-radius:0.2rem}
```

### Expected output CSS

```css
kbd{padding:.2rem .4rem;font-size:.875em;color:#fff;background-color:#212529;border-radius:.2rem}
```

I noticed more cases, not only `border-radius` and it seems to only happen for `rem`s.

**Comment by jakubpawlowicz** [comment]
Hey @XhmikosR - by saying "I noticed more cases" do you mean more cases of `border-radius` or other properties too?

**Comment by XhmikosR** [comment]
I meant more CSS properties. It's like it's unrelated to the CSS property but specific to rem.

You can try the branch if you want to check the diff https://github.com/twbs/bootstrap/tree/main-xmr-update-cleancss

**Comment by XhmikosR** [comment]
FYI [this](https://ja2r7.app.goo.gl/W9mZAqtrX6xLyiPB6) is the size diff compared to clean-css v4.

**Comment by jakubpawlowicz** [comment]
Thanks, I'll have a look and fix it.

**Comment by jakubpawlowicz** [comment]
^ this should do the trick, please have a quick look at https://github.com/jakubpawlowicz/clean-css/commit/b8c26572d7cc3023d12a8ada14ea8a71dcd37892#diff-ec858cb5d55ea11dd5f18cb15cfd49435b1bb3cfb1833eee78398b17ac0dd527 if it looks ok to you.

**Comment by XhmikosR** [comment]
Thanks for taking a look, I really appreciate it!

https://ja2r7.app.goo.gl/cVvQAgjcNbovnGNZ7

It seems there are more cases, like this one:

```css
.progress-bar-striped {
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-size: 1rem 1rem;
}
```

`0.15` isn't converted to `.15`.

I'd just check out my [upstream branch](https://github.com/twbs/bootstrap/tree/main-xmr-update-cleancss) and as long as the output is the same, then we should be good to go :)
