### ISSUE TITLE
Optimizing properties of level 2 removes hsla values

### ISSUE THREAD

**Issue by lex111** [jakubpawlowicz/clean-css#1156]
For some unknown reason, when using 2 level, color values specified in hsla format are removed.

### Environment

* clean-css version - `npm ls clean-css`: 5.1.0
* node.js version - `node -v`: 12.13.0
* operating system: Ubuntu 20.04

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  inline: false,
  level: {
    1: {
      all: false,
    },
    2: {
      all: true,
      restructureRules: true,
      removeUnusedAtRules: false,
    },
  },
})
```

### Input CSS

```css
.test {
  border: 1px solid hsla(0, 0%, 65.5%, 0.2);
}
```

### Actual output CSS

```css
.test {
  border: 1px solid;
}
```

### Expected output CSS

```css
.test {
  border: 1px solid hsla(0, 0%, 65.5%, 0.2);
}
```
