### ISSUE TITLE
Media Query issue

### ISSUE THREAD

**Issue by lukeapage** [jakubpawlowicz/clean-css#117]
Hi,

I'm part of the less core team. We always had an option to compress with yui-compressor, but due to lack of support for that we are looking at moving to a different npm package.

We had a bug raised about the existing compressor which is what brought this about. However testing with clean css has produced some strange results (I think). Apologies if there is a reason for this.

With this input from less

``` css
@media print, (-o-min-device-pixel-ratio: 5/4), (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
  /* Style adjustments for high resolution devices */
}
/**===================================================**\
/**  PRINT STYLES
/**===================================================**/
@media only print {
  a,
  a:visited {
    text-decoration: underline;
  }
  a[href]:after {
    content: " (" attr(href) ")";
  }
  abbr[title]:after {
    content: " (" attr(title) ")";
  }
  /** MANUALLY TRUNCATED FOR BREVITY **/
}
```

we get

``` css
@media print,(-o-min-device-pixel-ratio:5/4),(-webkit-min-device-pixel-ratio:1.25),(min-resolution:120dpi){}/ @media only print{a,a:visited{text-decoration:underline}a[href]:after{content:" (" attr(href) ")"}abbr[title]:after{content:" (" attr(title) ")"}}
```
1. what is the `/` about? It seems to be caused by using `\` instead of `/` at the end of the comment.. it seems to be making clean-css get confused
2. could you save space by removing empty media blocks?
