### ISSUE TITLE
Duplicate css variable initialization not removed in minify

### ISSUE THREAD

**Issue by subi-ksha97** [jakubpawlowicz/clean-css#1283]
### Environment

* clean-css version - `5.3.3`:
* node.js version - `v16.20.2`:
* operating system: `macOs Sonoma`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level : {
      2: {
          all: true,
          removeDuplicateVariableAssignments: true
      }
 }
})
```

### Input CSS

```css
:root {
  --main-bg-color: brown;
  --main-bg-color: blue;
}
p{
  background-color: var(--main-bg-color);
}
```

### Actual output CSS

```css
:root{--main-bg-color:brown;--main-bg-color:blue}p{background-color:var(--main-bg-color)}
```

### Expected output CSS

```css
:root{--main-bg-color:blue}p{background-color:var(--main-bg-color)}
```
