### ISSUE TITLE
spaces before and after nth-child "of"-syntax are removed

### ISSUE THREAD

**Issue by jonex2** [jakubpawlowicz/clean-css#1284]
### Environment

* clean-css version - `5.3.3`:
* node.js version - `22.11.0`:
* operating system: `macOS Sonoma`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS()
```

### Input CSS

```css
.li:nth-child(-n + 3 of .noted) {
  background: red
}

.li:nth-child(even of .noted) {
  background: green
}

.li:nth-child(odd of .noted) {
  background: red
}
```

### Actual output CSS

```css
.li:nth-child(-n+3of.noted){background:red}.li:nth-child(evenof.noted){background:green}.li:nth-child(oddof.noted){background:red}
```

### Expected output CSS

```css
.li:nth-child(-n+3 of .noted){background:red}.li:nth-child(even of .noted){background:green}.li:nth-child(odd of .noted){background:red}
```
