### ISSUE TITLE
clean-css removes the percent symbol from "0%" in the function color-mix() breaking the behavior

### ISSUE THREAD

**Issue by MurzNN** [jakubpawlowicz/clean-css#1292]
I faced a problem that clean-css breaks the function `color-mix()` when it contains `0%` value, here is an example - HTML:
```html
<div class="my-div">my div</div>
```
and CSS
```css
:root {
--my-color: #f00;
}
.my-div {
  width: 500px;
  height: 100px;
  background: linear-gradient(to right,
        color-mix(in srgb, var(--my-color, #0ff) 0%, transparent) 0%,
        color-mix(in srgb, var(--my-color, #0ff) 100%, transparent) 50%,
        color-mix(in srgb, var(--my-color, #0ff) 0%, transparent) 100%
      );
}
```
Codepen: https://codepen.io/MurzNN/pen/PwqpwWd

The minified CSS by `clean-css` is:
```css
:root{--my-color:#f00}.my-div{width:500px;height:100px;background:linear-gradient(to right,color-mix(in srgb,var(--my-color,#0ff) 0,transparent) 0,color-mix(in srgb,var(--my-color,#0ff) 100%,transparent) 50%,color-mix(in srgb,var(--my-color,#0ff) 0,transparent) 100%)}
```

As you can see, ` var(--my-color, #0ff) 0%` became `var(--my-color,#0ff) 0` that doesn't work.

Is there any way to disable this conversion explicitly, to fix this issue?
