### ISSUE TITLE
Shorthand properties

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#134]
http://www.w3.org/community/webed/wiki/CSS_shorthand_reference
1. margin, padding, outline
2. list-style
3. background
4. font
# 

_margin, padding, outline_

``` css
div.foo {
  margin-top: 1em;
  margin-right: 1.5em;
  margin-bottom: 2em;
  margin-left: 2.5em;
}
```

is equivalent to

``` css
div.foo {
  margin: 1em 1.5em 2em 2.5em;
}
```

The same applies to `padding` and `outline`.
# 

_list-style_

``` css
.foo {
  list-style-type: circle;
  list-style-position: inside;
  list-style-image: url(bullet.gif);
}
```

is the same as:

``` css
.foo {
  list-style: circle inside url(bullet.gif);
}
```
# 

_Background_

``` css
.foo {
  background-color: #000;
  background-image: url(image.gif);
  background-repeat: no-repeat;
  background-position: top left;
  background-attachment: fixed;
}
```

is the same as:

``` css
.foo {
  background: #000 url(image.gif) no-repeat top left fixed;
}
```
# 

_font_

``` css
.foo {
  font-weight: bold;
  font-style: italic;
  font-variant: small-caps;
  font-size: 1.5em;
  line-height: 200%;
  font-family: Georgia, "Times New Roman", serif;
}
```

is the same as:

``` css
.foo {
  font: bold italic small-caps 1.5em/200% Georgia, "Times New Roman", serif;
}
```
