### ISSUE TITLE
Add advanced selectors rearrangements

### ISSUE THREAD

**Issue by GoalSmashers** [jakubpawlowicz/clean-css#158]
E.g.

``` css
.one{color:red;margin:0}
.two{color:#fff}
.one{font-size:12px}
```

into

``` css
.one{color:red;margin:0;font-size:12px}
.two{color:#fff}
```

It should be possible to rearrange & merge selectors if:
- any intermediate selectors ones do not redefine properties moved
- any intermediate selectors are do not override moved one (html element ones, classes are unsafe)
