### ISSUE TITLE
Improve property merging algorithm

### ISSUE THREAD

**Issue by GoalSmashers** [jakubpawlowicz/clean-css#168]
``` css
a{color:white;color:black;color:red;}
```

does not get minified into

``` css
a{color:red}
```

That's because we assume adjoining properties to be used deliberately, e.g.:

``` css
a {
  color:rgba(0,0,0,0.5);
  color:#888;
}
```

or

``` css
a{
  background:#fff;
  background:-moz-linear-gradient(...);
  background:-webkit-linear-gradient(...);
  background:linear-gradient(...);
}
```
