### ISSUE TITLE
remove units from 0 in keyfranes

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#181]
``` css
@keyframes mymove
{
0%   {top:0px; left:0px; background:red;}
25%  {top:0px; left:100px; background:blue;}
50%  {top:100px; left:100px; background:yellow;}
75%  {top:100px; left:0px; background:green;}
100% {top:0px; left:0px; background:red;}
}
```

Haven't tried 0deg etc. I know for sure for percentage the unit is needed though, so in the above example `0` won't work in the place of `0%`.

EDIT: seems to work for 0deg too.
