### ISSUE TITLE
minify `transform`

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#182]
```css
div {transform:scaleX(0.5);}
```
```css
div {transform:scaleX(.5);}
```

Also, `scale` and `scaleY`.

Also,

```css
@keyframes rollIn{0%{transform:translateX(-100%) rotate(-120deg)}100%{transform:translateX(0px) rotate(0deg)}}
```

could be

```css
@keyframes rollIn{0%{transform:translateX(-100%) rotate(-120deg)}100%{transform:translateX(0) rotate(0)}}
```

Plus `0%`.

Another thing that seems to work is removing spaces before `rotate`, `translateXYZ` and `scale`.

```css

foo {
-webkit-transform:translateX(100%) rotate(120deg)
}


foo {
-webkit-transform:translateX(100%)rotate(120deg)
}
```
