### ISSUE TITLE
Use important properties for optimalization opportunities

### ISSUE THREAD

**Issue by Venemo** [jakubpawlowicz/clean-css#184]
In cases where there are not enough non-important properties for compacting into a shorthand, but there could be when taking important properties into account, we can use them to our advantage.

For example, this code:

``` css
foo {
  margin-top: 1px;
  margin-right: 2px;
  margin-bottom: 3px !important;
  margin-left: 4px !important
}
```

is equivalent to the following:

``` css
foo {
  margin: 1px 2px 0 0;
  margin-bottom: 3px !important;
  margin-left: 4px !important
}
```

Reasoning:  
In the example it is safe to add a fake `0` for non-important `margin-bottom` and `margin-left` because their values are going to be overridden by the important properties. However, there is a visible gain in terms of CSS size.
