### ISSUE TITLE
Shorthand repeated granular properties when there is already a shorthand with many defaults

### ISSUE THREAD

**Issue by Venemo** [jakubpawlowicz/clean-css#190]
Sometimes when there is already a shorthand in the input and it contains many default values, this gives us the opportunity to shorthand a granular property which already occours in the shorthand.

This would be a useful feature for optimizing CSS with fallbacks and/or vendor-specific values.

**Examples**

``` css
/* This pretty much makes sense: */

/* Input */
foo{background:#fff;background-color:rgba(1,2,3,.4)}
/* Output */
foo{background:#fff;background:rgba(1,2,3,.4)}

/* This will work because the things that the new shorthand will "default out" are already "defaulted out" by the previous shorthand */

/* Input */
foo{background:#fff url(aaa.jpg);background-color:rgba(1,2,3,.4);background-image:linear-gradient()}
/* Output */
foo{background:#fff url(aaa.jpg);background:rgba(1,2,3,.4) linear-gradient()}

/* I'm actually not sure if this last one makes sense, but maybe it does: */

/* Input */
foo{margin:4px;margin-right:calc(1%+1px);margin-left:calc(1%+1px)}
/* Output */
foo{margin:4px;margin:4px calc(1%+1px)}
```

What do you think?
