### ISSUE TITLE
It skips the first rule after a block of comments

### ISSUE THREAD

**Issue by jcayzac** [jakubpawlowicz/clean-css#192]
``` css
/*
@import url(//fonts.googleapis.com/css?family=PT+Sans+Caption:400italic,400,700italic,700);
@import url(//fonts.googleapis.com/css?family=Droid+Sans:400,700);
@import url(//fonts.googleapis.com/css?family=Open+Sans:400,700,800);
@import url(//fonts.googleapis.com/css?family=Inconsolata:400,700);
*/
.vrac {
  overflow: hidden;
  position: relative; }
  .vrac:before {
    content: "";
    display: block;
    height: 0;
    padding-top: 44.44444%; }
  .vrac > *:first-child {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%; }
```

``` sh
$ ./node_modules/.bin/cleancss boo.css
.vrac:before{content:"";display:block;height:0;padding-top:44.44444%}.vrac>:first-child{position:absolute;left:0;top:0;width:100%;height:100%}
```

The **.vrac** rule is gone…

(I use version 2.0.2)
