### ISSUE TITLE
@import inline broken in version 2.0.3+

### ISSUE THREAD

**Issue by marrone** [jakubpawlowicz/clean-css#198]
Commit 7b739b65afe4c59bb8dbcf28ba8e368352da2fb8 seems to have broken @imports between version 2.0.2 and 2.0.3

In our main.css file, we have something like

``` css
@import url('a.css');
@import url('b.css');
@import url('c.css');
#foo { color: blue; }
```

In 2.0.2, the imports were merged inline and minified without issue. In 2.0.3, only the first @import is merged, and the following @imports are not, instead the final @import appears broken inline, the above example outputs

``` css
#aaa{color:red;}import url(c.css);#foo{color:blue;}
```

I tried creating a simple test case, but it appears to depend partially on the contents of the imported stylesheets (I suspect a greedy regex), so I do not yet have a simple repeatable example for you
