### ISSUE TITLE
Merge media queries

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#204]
When dealing with multiple CSS files and media queries, merging those would improve compression a lot.

**Comment by jakubpawlowicz** [comment]
As far as I can see a `@media` can't be moved, thus merged, if any of its selectors or properties is being redefined in between, as specificity is the same and only order matters, e.g.

```css
@media (min-width: 1024px) {
  .one { background: red }
  .two { color: blue }
}
.two { color: red }
@media (min-width: 1024px) {
  .one { color: red; display: block }
}
```

Tricky.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: you are right about that case. But all others should be OK to merge. Maybe looking at https://github.com/buildingblocks/grunt-combine-media-queries/blob/master/tasks/combine-media-queries.js can help.

**Comment by jakubpawlowicz** [comment]
:+1: will do!

**Comment by jakubpawlowicz** [comment]
Please feel free to give `204-media-merging` branch a try - should work well.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: I see a regression

```css
.btn-group>.btn:not(:first-child):not(:last-child):not(.dropdown-toggle){border-radius:0}
```

```css
.btn-group>.btn:not(:first-child) :not(:last-child) :not(.dropdown-toggle){border-radius:0}
```
