### ISSUE TITLE
Bug in protocol imports

### ISSUE THREAD

**Issue by GoalSmashers** [jakubpawlowicz/clean-css#207]
See https://github.com/GoalSmashers/clean-css/issues/85#issuecomment-32083966

``` javascript
cleanCss = require('clean-css');
inst = new cleanCss;
inst.minify('@import url("//fonts.googleapis.com/css?family=Oleo Script Swash Caps");\n.block2 { font-family: \'Oleo Script Swash Caps\'; }\n');
```

resolves into

``` css
@import url(//fonts.googleapis.com/css?family=Oleo) Script Swash Caps);.block2{font-family:'Oleo Script Swash Caps'}
```

**Comment by zanona** [comment]
It might be a good idea to leave the ticket open until it has been fixed on 2.1?
Especially for new users having the same issue to find this one.

**Comment by zanona** [comment]
I am still having the same issue… with the latest version, can someone replicate it?

**Comment by jakubpawlowicz** [comment]
@zanona Works for me with the latest 3.0. Does that help anyhow? https://github.com/jakubpawlowicz/clean-css#how-to-make-sure-remote-imports-are-processed-correctly

**Comment by zanona** [comment]
thanks for your reply @jakubpawlowicz,
The problem here lies on the correct behaviour that generates a new one, I guess, when using __relative protocols__:

```js
var CleanCSS = require('clean-css');
var source = '@import url(//fonts.googleapis.com/css?family=Archivo+Narrow);'
new CleanCSS().minify(source, function (errors, minified) {
  console.log(minified.styles);
});
```

Formatted response here is:

```css
@font-face {
    font-family: 'Archivo Narrow';font-style:normal;font-weight:400;
    src: local('Archivo Narrow Regular'),
         local('ArchivoNarrowRegular'),
         url(http://fonts.gstatic.com/s/archivonarrow/v5/…ttf) format('truetype')
}
```

In this case, please note that since relative was used, its usage should be able to work on both protocols, __(http or https)__, when requesting those by https, the code generated by google automatically converts protocols included for https.

I understand that since the initial imported file is merged within the output, the protocol doesn't matter anymore, but just for safety, I believe it might be best to first perform the import with a HTTPS request first when relative protocol is used, making sure the script will work on both when deployed.

Also, may I ask what happens in case inside the imported document there is another CSS import statement? does Clean CSS follow those URLs as well?

Cheers
