### ISSUE TITLE
Property merging works incorrectly if the properties are not declared consecutively

### ISSUE THREAD

**Issue by asapach** [jakubpawlowicz/clean-css#210]
When `background` properties are declared one after another, the minified result is correct:

``` css
.btn-primary {
  border-color: #005A84;
  background: #0083BF;
  background: linear-gradient(to bottom,  #0083BF 0%,#005A84 100%);
}
```

``` css
.btn-primary{border-color:#005A84;background:#0083BF;background:linear-gradient(to bottom,#0083BF 0,#005A84 100%)}
```

However, if they are separated by another property declaration, the result is broken:

``` css
.btn-primary {
  background: #0083BF;
  border-color: #005A84;
  background: linear-gradient(to bottom,  #0083BF 0%,#005A84 100%);
}
```

``` css
.btn-primary{border-color:#005A84;background:linear-gradient(to bottom,#0083BF 0,#005A84 100%)}
```

Notice that the fallback `background` declaration is missing.

`cleancss -v` `2.0.7`
