### ISSUE TITLE
Bug in merging multiple selectors with background

### ISSUE THREAD

**Issue by doochik** [jakubpawlowicz/clean-css#232]
``` css
.bug-selector,
.bug-selector1
{
    background: red;
}

.bar
{
    padding: 0;
}

.bug-selector,
.bug-selector1
{
    background: black url("images/b-toolbar.gif");
    background: linear-gradient(#5e6081, #353340);
}
```

cleancss v2.0.7 produces

``` css
.bar{padding:0}
.bug-selector,.bug-selector1{background:linear-gradient(#5e6081,#353340)}
```

Valid result

``` css
.bar{padding:0}
.bug-selector,.bug-selector1{background: black url("images/b-toolbar.gif");background:linear-gradient(#5e6081,#353340)}
```

And this code works well

```
.nobug
{
    background: red;
}

.foo
{
    padding: 0;
}

.nobug
{
    background: black url("images/b-toolbar.gif");
    background: linear-gradient(#5e6081, #353340);
}
```
