### ISSUE TITLE
2.0.x - css import incorrect around comments

### ISSUE THREAD

**Issue by shenjunru** [jakubpawlowicz/clean-css#239]
# Issue

css import incorrect around comments.
- 2.0.3~2.0.8 from branch 2.0.
- 2.0.3~2.0.6 from branch master.
## Context

file: `a.css`

``` css
.a { content: "a ok"; }
```

file: `a.css`

``` css
.b { content: "b ok"; }
```

file: `a.css`

``` css
.c { content: "c ok"; }
```

file: `a.css`

``` css
.d { content: "d ok"; }
```

file: `test.css`

``` css
/* comment-1 */
@import url("a.css");
@import url("b.css");

/* comment-2 */
@import url("c.css");

/* comment-3 */
@import url("d.css");
```
## Result

expected result from `test.css` to `test.min.css`

``` css
.a{content:"a ok"}.b{content:"b ok"}.c{content:"c ok"}.d{content:"d ok"}
```

2.0.x result

``` css
.a{content:"a ok"}.b{content:"b ok"}import url(c.css);.d{content:"d ok"}
```
