### ISSUE TITLE
bug when there are IE hacks

### ISSUE THREAD

**Issue by jiangyuan** [jakubpawlowicz/clean-css#245]
just example:

``` css
...
.footer {height:20px;position:relative;}
...
.footer {height:20px\9;}
...
```

just like this, the `cleancss` result is:

``` css
.footer{position:relative;}.footer{height:20px\9;}
```

Obviously not I want.

`cssclean` info:

```
clean-css@2.1.1
   └── commander@2.1.0
```
