### ISSUE TITLE
Problem with deleting duplicate selectors

### ISSUE THREAD

**Issue by maksimr** [jakubpawlowicz/clean-css#248]
Hello!
We have a problem with removing duplicate selectors.

**Problem description**:

Source **css** file:

``` css
.foo {
  right: 10px;
}
....
// HACK: change right only for webkit
.foo, x::-webkit-scrollbar {
  right: 5px
}
```

In the output file is removed first rule and we have only _hack_ rule.
This breaks all browsers except based on webkit.

``` css
...
.foo, x::-webkit-scrollbar {
  right: 5px
}
```

we can fix this _specify rule_ like `html .foo, x::-webkit-scrollbar`, but it is not clear how right.

Thanks!
