### ISSUE TITLE
nested blocks keep the whitespaces

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#25]
``` css
@media (min-width: 980px) {
    #page .span4 {
        width: 250px;
    }

    .row {
        margin-left: -10px;
    }
}
```

becomes:

``` css
@media (min-width: 980px){#page .span4{ width:250px}.row{margin-left:-10px}}
```

expected:

``` css
@media (min-width:980px){#page .span4{width:250px}.row{margin-left:-10px}}
```

The following must be valid too so it might be worth looking at doing it like:

``` css
@media min-width:980px{#page .span4{width:250px}.row{margin-left:-10px}}
```

The parentheses must be only needed if there are 2 conditions or more, but please verify.

http://www.w3.org/TR/css3-mediaqueries/

I suppose the 0px case is converted to 0 so nothing to do there.

I'm using v0.8.2, node.js 0.9.3 (happens with 0.8.14 too) on Windows 32bit. I can't remember if this happened with the previous versions, maybe I just spotted it now...
