### ISSUE TITLE
Incorrect @import output when there is an empty selector group and --skip-advanced

### ISSUE THREAD

**Issue by exogen** [jakubpawlowicz/clean-css#258]
Given this simple CSS:

``` css
@import url('//fonts.googleapis.com/css?family=Domine:700');

body {
  color: #000;
}

body h1 {
  font-family: 'Domine';
}
```

`cleancss --skip-import --skip-advanced` will give the expected output:

``` css
@import url(//fonts.googleapis.com/css?family=Domine:700);body{color:#000}body h1{font-family:Domine}
```

However, if the `@import` is followed by an empty selector group (including when the group has only a comment):

``` css
@import url('//fonts.googleapis.com/css?family=Domine:700');

body {
  /* comment */
}

body h1 {
  font-family: 'Domine';
}
```

`cleancss --skip-import --skip-advanced` will omit the `@import` altogether:

``` csss
body h1{font-family:Domine}
```

Without `--skip-advanced`, the output is as expected – the `@import` remains, but the `body` group is omitted. I would expect the same output with `--skip-advanced`.
