### ISSUE TITLE
"@import" in a comment causes the next lines to be skipped

### ISSUE THREAD

**Issue by d13r** [jakubpawlowicz/clean-css#264]
In v2.1.6, this file:

``` css
/*@import url(//fonts.googleapis.com/css?family=Raleway:400,700);*/
@import url(//fonts.googleapis.com/css?family=Raleway:400,500,700);

.a { color: red; }
.b { color: green; }
```

Is incorrectly minified to:

``` css
.b{color:green}
```

Removing the `@import` from the comment makes it work correctly.

``` css
/*@ import url(//fonts.googleapis.com/css?family=Raleway:400,700);*/
@import url(//fonts.googleapis.com/css?family=Raleway:400,500,700);

.a { color: red; }
.b { color: green; }
```

Is correctly minified to:

``` css
@import url(//fonts.googleapis.com/css?family=Raleway:400,500,700);.a{color:red}.b{color:green}
```
