### ISSUE TITLE
Incorrect ordering / Inconsistent css rule merging

### ISSUE THREAD

**Issue by altmind** [jakubpawlowicz/clean-css#267]
Using standalone cleancss-cli 2.1.7.

Processing 

``` css
.nav-item-link {
    height: 7rem; /* DECLARED FIRST */
}

.nav-item-link-product {
    height: auto; /* DECLARED SECOND */
}

.nav-item-link {
    line-height: 7rem; /* BREAKS ORDERING*/
    color: red;
}
```

results in 

``` css
.nav-item-link-product{height:auto}
.nav-item-link{height:7rem;line-height:7rem;color:red}
```

which is semantically wrong - now .nav-item-link will overwrite height for html element with class="nav-item-link-product nav-item-link". Clear problem with css rule priorities.

I'm puzzled, as when we remove "line-height: 7rem;" from 3rd rule, we get correct result css. See:

``` css
.nav-item-link {
    height: 7rem; /* DECLARED FIRST */
}

.nav-item-link-product {
    height: auto; /* DECLARED SECOND */
}

.nav-item-link {
    color: red;
}
```

generates

``` css
.nav-item-link{height:7rem}
.nav-item-link-product{height:auto}
.nav-item-link{color:red}
```

So it seems that 'color' does not cause .nav-item-link rules merge, whereas 'line-height' property does cause rules merge.

When using option "noAdvanced" clean-css generates correct result.

This problem was observed on production and is real, practical, issue
