### ISSUE TITLE
More improvements

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#28]
``` css
margin: 0 0 6px 0;
```

should be:

``` css
margin: 0 0 6px;
```

The same applies to `padding` and **probably** to many more shorthand notations.

---

``` css
margin: 6px 6px 6px 6px;
padding: 12px 12px 12px 12px;
```

should be:

``` css
margin: 6px;
padding: 12px;
```

---

``` css
font: normal 13px/20px "Helvetica Neue",Helvetica,Arial,sans-serif;
```

should be:

``` css
font: 400 13px/20px "Helvetica Neue",Helvetica,Arial,sans-serif;
```

Another thing I was wondering, would it be very hard for clean-css to merge the selectors when they are the same? For example:

``` css
foo { font: Sans-serif; }
foo { font-weight: bold; }
```

can become:

``` css
foo {
    font: Sans-serif;
    font-weight: bold;
}
```
