### ISSUE TITLE
Not enough grouping of same classes

### ISSUE THREAD

**Issue by tompazourek** [jakubpawlowicz/clean-css#280]
When I try to minify the following CSS:
```css
.a { background: red; }
.b { background: green; }
.c { background: red; }
.d { background: red; }
```

I get this output:
```css
.a{background:red}.b{background:green}.c,.d{background:red}
```

I would expect something like this:
```css
.a,.c,.d{background:red}.b{background:green}
```

I am using **grunt-contrib-cssmin 0.9.0** with the default settings. How should I configure it to get my desired output?

Thank you :-)
