### ISSUE TITLE
Font: Arial Black, becomes Arial #000

### ISSUE THREAD

**Issue by Jrags87** [jakubpawlowicz/clean-css#282]
I've noticed that the font Arial Black compresses to Arial #000.

**Comment by ben-eb** [comment]
This doesn't appear to be fixed; this is perfectly valid CSS:

```css
h1 {
    font-family: Arial Black, sans-serif;
}
```

Compressed to:

```css
h1{font-family:Arial #000,sans-serif}
```
