### ISSUE TITLE
Expression optimize was wrong in 2.x.x

### ISSUE THREAD

**Issue by hefangshi** [jakubpawlowicz/clean-css#288]
I update clean-css from 1.1.7 to 2.1.8, and found that the expression was optimized by mistake.

source:

``` css
.sample {
    zoom:1;
    _zoom:expression(function(el){el.firstChild.style.marginLeft=0;el.style.zoom="1"}(this))
}
```

clean-css 2.18 output:

``` css
.sample{zoom:1;_zoom:expression(function(el){el.firstChild.style.marginLeft=0;el.style.zoom="1"}
```

clean-css 1.17 output:

``` css
.sample{zoom:1;_zoom:expression(function(el){el.firstChild.style.marginLeft=0;el.style.zoom="1"}(this))}
```
