### ISSUE TITLE
Escaped @ symbol handled incorrectly

### ISSUE THREAD

**Issue by leevigraham** [jakubpawlowicz/clean-css#292]
I was testing cssmin with a class name that included an escaped @ symbol:

``` css
body {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

.pad--all0\@sm {
    padding: 0px !important;
}
```

The output of running the `grunt cssmin` task is:

``` css
body{-moz-box-sizing:border-box;box-sizing:border-box}
```

The `.pad--all0\@sm` rule has been removed from the minified css. This can easily be worked around by changing the classname to `pad--all0-at-sm`

Related: https://github.com/GoalSmashers/clean-css/commit/5f623e98cb08fcfa3f3a069e9870b557386e14c6#diff-05e9388c2ace6ca393f620c1e1987b62R2

See: gruntjs/grunt-contrib-cssmin#96
