### ISSUE TITLE
auto removed from outline

### ISSUE THREAD

**Issue by hnrch02** [jakubpawlowicz/clean-css#302]
See https://github.com/twbs/bootstrap/issues/13914.

---

If I give clean-css this

``` css
div {
  outline: 5px auto -webkit-focus-ring-color;
}
```

it gives me back this

``` css
div{outline:-webkit-focus-ring-color 5px}
```

removing `auto` from the property and rendering focus outlines in WebKit non-existent.

You can see the difference `auto` makes [in this JS Bin](http://jsbin.com/faqoj/1/edit?html,css,output).
