### ISSUE TITLE
Incorrect order for multiple backgrounds and redundant color

### ISSUE THREAD

**Issue by hoho** [jakubpawlowicz/clean-css#307]
I have css like:

``` css
body
{
    background: #00f;
    background-image: linear-gradient(to bottom, rgba(0,255,0,.5), rgba(0,0,0,0)),
                      linear-gradient(to top,rgba(255,0,0,.5), rgba(0,0,0,0));
}
```

`cleancss 2.2.4` turns it to:

``` css
body{background:#00f;background:#00f linear-gradient(to bottom,rgba(0,255,0,.5),transparent),linear-gradient(to top,rgba(255,0,0,.5),transparent)}
```

And here are two things:
- Second `#00f` is redundant.
- Even if it exists, it should be last. Otherwise, entire property value is not working: http://www.css3.info/preview/multiple-backgrounds/ says `background: [ <bg-layer> , ]* <final-bg-layer>` and only `<final-bg-layer>` can have `background-color`.
