### ISSUE TITLE
url() and comment: Freeze with 100% CPU load

### ISSUE THREAD

**Issue by molily** [jakubpawlowicz/clean-css#308]
```

$ cleancss -v
2.2.5
```

test.css:

``` css
p {
  background-image: url('/*');
}

/* */
```

```
$ cleancss test.css
```

Freezes with 100% CPU. Can someone reproduce this? I guess this is a bug in parsing of comments.

My actual CSS doesn’t look like the contrived example above, that’s just a minimal test case to reproduce the freeze for me. What I actually have looks like this:

``` css
.some-selector {
  background-image: url('<t4 type="media" id="123456" formatter="path/*"/>');
}

/* Some comment */
.another-rule {}
```

This XML tag is a marker for the CMS we’re using. The CMS replaces the tag with the actual media URL.

I know that’s funky but it’s valid from a CSS syntax point of view, isn’t it? So clean-css shouldn’t choke on it.

Thanks!
