### ISSUE TITLE
Destroyed background-position

### ISSUE THREAD

**Issue by hoho** [jakubpawlowicz/clean-css#316]
cleancss 2.2.7 turns

``` css
.class1 { background: 50% no-repeat; }
.class1 { background-image: url("/ololo"); }
```

to

``` css
.class1{background:url(/ololo) no-repeat}
```
