### ISSUE TITLE
"display: -webkit-flex" gets stripped out from Pure CSS

### ISSUE THREAD

**Issue by kislakiruben** [jakubpawlowicz/clean-css#318]
I'm using the grids from the [Pure CSS](http://purecss.io/grids/) framework.
Every time I run clean-css, 'display: -webkit-flex' gets stripped out.

Input:

``` css
.pure-g {
    letter-spacing: -0.31em;
    *letter-spacing: normal;
    *word-spacing: -0.43em;
    text-rendering: optimizespeed;
    font-family: FreeSans, Arimo, "Droid Sans", Helvetica, Arial, sans-serif;
    display: -webkit-flex; /* this gets removed */
    -webkit-flex-flow: row wrap;
    display: -ms-flexbox;
    -ms-flex-flow: row wrap;
}

```

Output:

``` css
.pure-g{letter-spacing:-.31em;text-rendering:optimizespeed;font-family:FreeSans,Arimo,"Droid Sans",Helvetica,Arial,sans-serif;-webkit-flex-flow:row wrap;display:-ms-flexbox;-ms-flex-flow:row wrap}
```
