### ISSUE TITLE
background-size regression

### ISSUE THREAD

**Issue by Rowno** [jakubpawlowicz/clean-css#326]
2.2.10 has a regression in `background-size` minification that generates invalid css. I think #322 introduced it.

**Input:**

``` css
.close-button {
    width: 28px;
    height: 28px;
    background: none;
    background-image: url("/images/close_button.png");
    -webkit-background-size: 28px 28px;
    background-size: 28px 28px;
}
```

**Output:**

``` css
.close-button{width:28px;height:28px;background:url(/images/close_button.png)/28px 28px;-webkit-background-size:28px 28px}
```

`background:url(/images/close_button.png)/28px 28px;` is invalid css.
