### ISSUE TITLE
Optimizations within comma-separated selectors.

### ISSUE THREAD

**Issue by philipwalton** [jakubpawlowicz/clean-css#328]
Hey, great tool! I'm wondering though if you've thought about additional optimization improvements that can be gained by individually inspecting comma separated selectors as stand-alone selectors.

For example, you're already optimizing this case:

``` css
/* Original */
p { margin: 0; }
p { margin-bottom: 20px; }

/* Compressed */
p{margin:0 0 20px}
```

But this optimization is missed:

``` css
/* Original */
h1, h2, h3, h4, h5 { margin: 0; }
h1, h2, h3, h4, h5, h6 { color: black; }

/* Compressed */
h1,h2,h3,h4,h5{margin:0}h1,h2,h3,h4,h5,h6{color:#000}
```

However, as anyone looking at this can see, further optimization is definitely possible:

``` css
h1,h2,h3,h4,h5{color:#000;margin:0}h6{color:#000}
```

I think if you run the same logic you're currently running on individual sub-selectors it may be possible to detect cases where the code can be even more minified.

As the use of things like Sass's `@extends` increases, long lists of comma-separated selectors are becoming more and more common. Also, if I include multiple libraries that do resets on a group of elements at the same time, I shouldn't have to worry that I'm repeating myself. I should be confident that the minifier will produce the best output.

Anyway, just a suggestion.
