### ISSUE TITLE
v0.8.3 regressions

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#33]
1) space not removed

``` css
.pln { color: #000 }  /* plain text */

@media screen {
  .str { color: #080 }  /* string content */
  .kwd { color: #008 }  /* a keyword */
  .com { color: #800 }  /* a comment */
```

``` css
.pln{color:#000}@media screen{.str{ color:#080}.kwd{color:#008}.com{color:#800}
```

2) the padding property doesn't use the optimized shorthand form, while previously it did.

``` css
.post .entry {
    padding: 10px 0 20px 0;
    text-align: justify;
}
```

becomes

``` css
.post .entry{padding:10px 0 20px 0;text-align:justify}
```

while it should be

``` css
.post .entry{padding:10px 0 20px;text-align:justify}
```

3) `bold` stays `bold` instead of `700`

``` css
header h1 {
    -webkit-font-smoothing: antialiased;
    color: #b5e853;
    font: bold 30px/1.5 Monaco, "Bitstream Vera Sans Mono", "Lucida Console", Terminal, monospace;
    letter-spacing: -1px;
    margin: 0 0 0 -40px;
    text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1),
                 0 0 5px rgba(181, 232, 83, 0.1),
                 0 0 10px rgba(181, 232, 83, 0.1);
}
```

``` css
header h1{-webkit-font-smoothing:antialiased;color:#b5e853;font:bold 30px/1.5 Monaco,"Bitstream Vera Sans Mono","Lucida Console",Terminal,monospace;letter-spacing:-1px;margin:0 0 0 -40px;text-shadow:0 1px 1px rgba(0,0,0,.1),0 0 5px rgba(181,232,83,.1),0 0 10px rgba(181,232,83,.1)}
```

There might be more regressions, I noticed the above by doing a quick testing only. In fact, the happens with any shortened color and `font-weight`.
