### ISSUE TITLE
px fallback for rem units should not be removed in compatibility mode

### ISSUE THREAD

**Issue by ademarre** [jakubpawlowicz/clean-css#333]
When using `rem`, a common way to add support for IE8 is with a `px` fallback:

``` css
.example {
  font-size: 24px;    /* Fallback for IE8 */
  font-size: 1.5rem;
  padding: 32px 16px; /* Fallback for IE8 */
  padding: 2rem 1rem;
}
```

The clean-css advanced optimizations are removing the fallback, even when `compatibility` is on. It would be great if compatibility mode could detect and preserve `px` fallbacks.

My current automated solution is to run [robwierzbowski/node-pixrem](https://github.com/robwierzbowski/node-pixrem) _after_ clean-css in my build. (See https://github.com/gruntjs/grunt-contrib-cssmin/issues/112#issuecomment-50927266)
#186 addressed a related edge case.
