### ISSUE TITLE
Output can be more than input for background shorthanding

### ISSUE THREAD

**Issue by kizu** [jakubpawlowicz/clean-css#341]
Input:

``` CSS
.asd{background:no-repeat;background-position:100% 0,0 100%,100% 100%,50% 50%}
```

clean-css (2.2.13) output:

``` CSS
.asd{background:100% 0 no-repeat,0 100% no-repeat,100% 100% no-repeat,50% 50% no-repeat}
```

I'd say there should be a check if the output of some optimization is actually more than input, so we wouldn't get cases like this one.
