### ISSUE TITLE
Bug in color fallback with importance

### ISSUE THREAD

**Issue by kizu** [jakubpawlowicz/clean-css#346]
When you have multiple declarations with the same property, but one with the hex/keyword and another with rgb/hsl/rgba/hsla, and all of those declarations are `!important`, then all the `rgba/…` declarations are incorrectly discarded:

``` CSS
.test {
    color: red !important;
    color: rgba(0,255,0,0.5) !important;
}
```

Incorrectly minifies to this:

``` CSS
.test{color:red!important}
```

Expected:

``` CSS
.test{color:red!important;color:rgba(0,255,0,.5)!important}
```
