### ISSUE TITLE
SVG filters defined with filter: url(...) are lost

### ISSUE THREAD

**Issue by gaearon** [jakubpawlowicz/clean-css#349]
This code:

``` css
[data-menu="true"] .social-Summary-content,
[data-menu="true"] .editor-Grabbox > * {
  opacity: .5;
  -webkit-filter: url(data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8ZmlsdGVyIGlkPSJibHVyIj4KICAgICAgICA8ZmVHYXVzc2lhbkJsdXIgc3RkRGV2aWF0aW9uPSIxMiIgLz4KICAgIDwvZmlsdGVyPgo8L3N2Zz4=#blur);
          filter: url(data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8ZmlsdGVyIGlkPSJibHVyIj4KICAgICAgICA8ZmVHYXVzc2lhbkJsdXIgc3RkRGV2aWF0aW9uPSIxMiIgLz4KICAgIDwvZmlsdGVyPgo8L3N2Zz4=#blur);
  -webkit-filter: blur(8px);
          filter: blur(8px);
}
```

gets incorrectly reduced to

``` javascript
.editor-Grabbox>*,[data-menu=true] .social-Summary-content{opacity:.5;-webkit-filter:blur(8px);filter:blur(8px)}
```

As you can see, SVG filters are lost.
