### ISSUE TITLE
External imports should be in the beginning of the processed output to be valid CSS

### ISSUE THREAD

**Issue by kasper** [jakubpawlowicz/clean-css#351]
External imports should be in the beginning of the processed output to be valid CSS (according to W3C CSS), but clean-css leaves them in the specified order.

**Input**
```css
@import url('a.css');
@import url('http://kytkemo.com/assets/css/style.css');
```

**Output**
```css
#a{width:1px}@import url(http://kytkemo.com/assets/css/style.css);
```
