### ISSUE TITLE
URLs in processed imports are rebased even if rebasing is disabled

### ISSUE THREAD

**Issue by kasper** [jakubpawlowicz/clean-css#352]
URLs in processed imports are rebased even if rebasing is disabled with `noRebase: true`. I would expect the URLs to stay intact.

**File** `a.css`

``` css
#a {

    height: 1px;
    background-image: url('images/image.png');

}
```

**File** `subdirectory/imports.css`

``` css
/* Process imports */

@import '../a.css';
```

**Output**

``` css
#a{height:1px;background-image:url(../images/image.png)}
```
