### ISSUE TITLE
More cases of bug in color fallbacks with importance

### ISSUE THREAD

**Issue by kizu** [jakubpawlowicz/clean-css#354]
The #346 fixed only some of the cases, like with the `color` property, but there are some other, like with the `background` and `border-color` (maybe there are others too):

``` CSS
.test_color {
    color: red !important;
    color: rgba(0,255,0,0.5) !important;
}
.test_background {
    background: red !important;
    background: rgba(0,255,0,0.5) !important;
}
.test_border-color {
    border-color: red !important;
    border-color: rgba(0,255,0,0.5) !important;
}
```

get compressed by clean-css@2.2.15 to

``` CSS
.test_color{color:red!important;color:rgba(0,255,0,.5)!important}.test_background{background:red!important}.test_border-color{border-color:red!important}
```

Initial case with color is fixed, but others are not.
