### ISSUE TITLE
Css property  disappear after cssmin 

### ISSUE THREAD

**Issue by g8up** [jakubpawlowicz/clean-css#355]
Css property display: -webkit-box; disappear after cssmin.

Before:

``` css
#footer {
    display: -webkit-box;
    -webkit-box-align: center;
    display: -ms-flexbox;
    -ms-box-align: center;
}
```

After:

``` css
#footer{-webkit-box-align:center;display:-ms-flexbox;-ms-box-align:center}
```

Version Info:
`{
  "name": "grunt-contrib-cssmin",
  "description": "Compress CSS files.",
  "version": "0.10.0",
  ...
}`
