### ISSUE TITLE
universal selector is removed from *:first-child+html 

### ISSUE THREAD

**Issue by makotot** [jakubpawlowicz/clean-css#356]
clean-css removes `*` from a selector hack for IE7 like below.

``` css
*:first-child+html .foo {
  display: inline;
}
```
