### ISSUE TITLE
Output > than the input when moving background-size to shorthands

### ISSUE THREAD

**Issue by kizu** [jakubpawlowicz/clean-css#364]
Input:

``` CSS
.v {
    background: #fff;
    background: -webkit-linear-gradient(#fff, #fff);
    background: -o-linear-gradient(#fff, #fff);
    background: linear-gradient(#fff, #fff);
    background-size: 16px 16px;
}
```

clean-css@2.2.16's output is 200 bytes

``` CSS
.v{background:0 0/16px 16px #fff;background:-webkit-linear-gradient(#fff,#fff) 0 0/16px 16px;background:-o-linear-gradient(#fff,#fff) 0 0/16px 16px;background:linear-gradient(#fff,#fff) 0 0/16px 16px}
```

Without moving the background-size to shorthands is 171 byte:

``` CSS
.v{background:#fff;background:-webkit-linear-gradient(#fff,#fff);background:-o-linear-gradient(#fff,#fff);background:linear-gradient(#fff,#fff);background-size:16px 16px;}
```

That's another case when the output becomes larger than input, maybe there could be some general solution for such cases if there is no one right now?
