### ISSUE TITLE
Do not move background-size to background shorthand with different supports

### ISSUE THREAD

**Issue by kizu** [jakubpawlowicz/clean-css#365]
Following up #364: there are differences in support for `background: #fff;` and `background:0 0/16px 16px #fff;`, so it is unsafe to do this for cases like this:

``` CSS
.v {
    background: #fff;
    background: -webkit-linear-gradient(#fff, #fff);
    background: -o-linear-gradient(#fff, #fff);
    background: linear-gradient(#fff, #fff);
    background-size: 16px 16px;
}
```

For example, Safari 6 won't understand such shorthand, and there are a lot of other old browsers that would fail there.
