### ISSUE TITLE
version 9+ converting 'white' and other colors in classnames to hex codes

### ISSUE THREAD

**Issue by malgorithms** [jakubpawlowicz/clean-css#37]
This code:

``` css
.black-and-white .foo {
    color:#fff;
    background-color:#000;
}
```

is compressed with cleancss as follows:

```
.black-and-#fff .foo{color:#fff;background-color:#000}
```

Note the class has been renamed `black-and-#fff`

Tested in v0.9.0. This was not happening in 0.8.3.
