### ISSUE TITLE
Minified measurements not rounding correctly

### ISSUE THREAD

**Issue by ghost** [jakubpawlowicz/clean-css#383]
``` css
div {
  height: 9.995px;
}
```

minifies incorrectly to

``` css
div{height:91px}
```

While

``` css
div {
  height: 9.994px;
}
```

minifies correctly to

``` css
div{height:9.99px}
```

I'm not sure exactly in which cases this is happening, but it does seem to be an error with rounding.

Thanks.
