### ISSUE TITLE
Edge case where minifying some CSS causes infinite recursion (or an infinite loop)

### ISSUE THREAD

**Issue by chilts** [jakubpawlowicz/clean-css#385]
(Clarification: whether that is a loop somewhere, or an infinite regex, I don't know.)

This took some investigation but I managed to narrow things down in terms of a simple case so bear with me through this.

Note: I run [CSS Minifier](http://cssminifier.com/) and perform around anywhere between 1,000 and 4,000 minifications a day. Every so often I find that the server locks up. I run multiple child processes but because it's recursing I can't set a timeout to kill it (since the event loop doesn't return) and because the user didn't get a response, they retry until all the children are unresponsive.
### Test 1

Please note the final comment which starts with `/*` but does not close.

``` css
/* @group PRINT */
/* ---------------------------------------------- */
@media print {

}
/* @end group PRINT 
```

This minifies with `Maximum call stack size exceeded`. So I figured that was ok.
### Test 2

If I add some weird and wonderful bits in the middle:

``` css
/* @group PRINT */
/* ---------------------------------------------- */
@media print {

    /* MISC. CLASSES & IDS */
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; clear:both; }

    /* HIDE ITEMS */
    [data-nostyle], [data-zc-nav], [data-zc-footer] ul, [data-zc-buttons], [data-zc-btn] { display:none; }

}
/* @end group PRINT 
```

This sets off an infinite recursion. So I figured there was something wrong with the middle somewhere. Or perhaps a weird combination of the two.
### Test 3

If I add a closing comment onto the end of the above, it minifies fine! So that's good.

``` css
/* @group PRINT */
/* ---------------------------------------------- */
@media print {

    /* MISC. CLASSES & IDS */
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; clear:both; }

    /* HIDE ITEMS */
    [data-nostyle], [data-zc-nav], [data-zc-footer] ul, [data-zc-buttons], [data-zc-btn] { display:none; }

}
/* @end group PRINT */
```

This minifies correctly. I figured then it wasn't something in the middle but related to the open comment at the end.
### Test 4

Trying to minimise the test case, I then got to this:

``` css
@media print {
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; }
}
/* @end group PRINT 
```

This also recurses. Note: I also took out the `display:block;` but then it gives the range error rather than recurses. Weird. Same with the `content:''`. If either of those aren't there it errors. If they are both there it recurses.
### Test 5

Just to make sure I'm not going insane, I tried this with the final (but unclosed) comment:

``` css
@media print {
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; }
}
```

This minifies correctly. Ok ... weird, but at least the bit above is somewhat ok (I think).
### Test 6

So let's play with that comment:

``` css
@media print {
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; }
}
/* @
```

This also recurses. However if I replace `/* @` with a `/*` only and still leave the comment open, it minifies fine.
### Test 7

Try to play around with that last one to minimise the test. However, I tried all of the following and none of them recursed, though they all did error out with the `RangeError: Maximum call stack size exceeded error`.

``` css
@media print {
    div { content:''; display:block; }
}
/* @
```

``` css
@media print {
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { }
}
/* @
```

``` css
@media print {
}
/* @
```

``` css
@media print {
    [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; }
}
/* @
```

``` css
@media print {
    .clearfix, [data-zc-inner], [data-zc-content] { content:''; display:block; }
}
/* @
```

``` css
@media print {
    a:after, b:after, c:after { content:''; display:block; }
}
/* @
```

And finally, without the final comment (which I might have mentioned earlier), this minimises fine:

``` css
@media print {
    .clearfix:after, [data-zc-inner]:after, [data-zc-content]:after { content:''; display:block; }
}
```

to:

```
@media print{.clearfix:after,[data-zc-content]:after,[data-zc-inner]:after{content:'';display:block}}
```

So basically, I can't touch the above test (number 6) without it then being raised as an error. Obviously your error handling catches loads of stuff, but I figure if something is making it recurse then I guess something is getting through somewhere.
### Where to from here ...

I don't know. There must be some weird interaction between these things, perhaps related to the two levels of the `@media` query, but perhaps not.

Note: I can see a comment in the CSS file (uploaded to the server) a product name which doesn't seem to be open source, so I can't paste the whole thing here. Feel free to send me an email to andychilton at gmail dot com and I can send you the original file if it helps, however, I think the above tries to demonstrate a minimal case for you. Let me know if I can be of further assistance. :) So yeah, that product _does_ have a CSS file with an open comment at the end and I can't send a patch to fix it!

And like I've said before, thanks for clean-css, it's a great project!
