### ISSUE TITLE
Bug with position in background shorthand property

### ISSUE THREAD

**Issue by zxbodya** [jakubpawlowicz/clean-css#386]
When minifying css:

``` CSS
.bg-fail{
    background: url(../images/photo-cart.png) no-repeat left 23px center;
}
```

getting following result:

``` CSS
.bg-fail{background:url(../images/photo-cart.png) no-repeat left}
```

Using clean-css@2.2.19

As I found  - it was introduced in commit e10ade3
