### ISSUE TITLE
Structural optimization

### ISSUE THREAD

**Issue by shuhrat** [jakubpawlowicz/clean-css#387]
Hi all!

Assume that you have a stylesheet

``` css
.right-col
{
    position: relative;
    z-index: 7;

    margin-left: 602px;

    -webkit-transition: margin-left .25s;
            transition: margin-left .25s;
}

.right-col-hidden
{
    margin-left: 602px;

    -webkit-transition: margin-left .25s;
            transition: margin-left .25s;
}
```

What do you think about structural optimization, like a

``` css
.right-col
{
    position: relative;
    z-index: 7;
}

.right-col,
.right-col-hidden
{
    margin-left: 602px;

    -webkit-transition: margin-left .25s;
            transition: margin-left .25s;
}
```

?
