### ISSUE TITLE
Merging of rules with unprefixed pseudo-classes

### ISSUE THREAD

**Issue by silverwind** [jakubpawlowicz/clean-css#390]
This is probably a bit of a corner case, but in advanced mode,

``` css
a{color: red}
div:fullscreen{color: red}
```

will get merged into

``` css
a,div:fullscreen{color:red}
```

The merged rule is considered invalid (because no browser supports unprefixed :fullscreen yet) and the `a` style ist dropped by browsers. I noticed that a `:-moz-full-screen` wasn't getting merged, so maybe that same treatment could be useful in this case too.
