### ISSUE TITLE
"TypeError" when SVG inlined

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#395]
I have the correct SVG image inlined to CSS. When trying minify this file gets error:

``` sh
$ cleancss test.css
```

```
.../node_modules/clean-css/lib/selectors/tokenizer.js:37
    .replace(WHITESPACE, ' ')
     ^
TypeError: Object
    background-image: __ESCAPED_URL_CLEAN_CSS0__%22%2F%3E%3Cpath d%3D%22m40.96 40.96c-4.69 4.69-10.82 7-16.96 7v-3.15c5.33 0 10.67-2.04 14.74-6.11 4.07-4.07 6.1-9.41 6.1-14.74h3.16c-.01 6.14-2.35 12.28-7 16.96%22 fill%3D%22__ESCAPED_URL_CLEAN_CSS1__%22%2F%3E%3Cpath d%3D%22m44.85 24c0-5.32-2.03-10.65-6.1-14.71-4.07-4.06-9.41-6.09-14.74-6.09v-3.2c6.14.01 12.28 2.35 16.96 7 4.7 4.69 7 10.83 7 16.98h-3.16%22 fill%3D%22__ESCAPED_URL_CLEAN_CSS2__%22%2F%3E%3Cpath d%3D%22m24 3.2c-5.32 0-10.65 2.03-14.71 6.09-4.06 4.06-6.09 9.39-6.09 14.71h-3.2c-.01-6.15 2.33-12.29 7-16.98 4.69-4.69 10.83-7 16.98-7v3.2%22 fill%3D%22__ESCAPED_URL_CLEAN_CSS3__%22%2F%3E%3Cpath d%3D%22m24 35.2c-2.87 0-5.74-1.09-7.93-3.29-2.18-2.19-3.27-5.1-3.28-7.91h3.18c0 2.05.78 4.1 2.34 5.66 1.57 1.57 3.62 2.35 5.67 2.34v3.19%22 fill%3D%22__ESCAPED_URL_CLEAN_CSS4__%22%2F%3E%3Cpath d%3D%22m24 38.4v3.22c-4.51.01-9-1.71-12.45-5.16-3.43-3.43-5.14-7.93-5.15-12.44h3.21c.01 3.68 1.41 7.36 4.21 10.16 2.81 2.82 6.5 4.23 10.19 4.22%22 fill%3D%
```

Content of file:

``` css
.example
{
    background-image: url("data:image/svg+xml,%3Csvg xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22 viewBox%3D%220 0 48 48%22 xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%3E%3Cdefs%3E%3ClinearGradient x1%3D%2226.3%22 y1%3D%2233.6%22 x2%3D%2233.4%22 y2%3D%2226.5%22 id%3D%227%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%232%22%2F%3E%3ClinearGradient x1%3D%2240.6%22 y1%3D%2221%22 x2%3D%2227%22 y2%3D%227.4%22 id%3D%22B%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%231%22%2F%3E%3ClinearGradient x1%3D%2228%22 y1%3D%2239.5%22 x2%3D%2239%22 y2%3D%2228.4%22 id%3D%228%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%232%22%2F%3E%3ClinearGradient x1%3D%2214.2%22 y1%3D%2221.9%22 x2%3D%2221.9%22 y2%3D%2214.2%22 id%3D%22A%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%234%22%2F%3E%3ClinearGradient x1%3D%228.1%22 y1%3D%2220.3%22 x2%3D%2220.3%22 y2%3D%228.1%22 id%3D%229%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%234%22%2F%3E%3ClinearGradient x1%3D%2234%22 y1%3D%2222.4%22 x2%3D%2225.6%22 y2%3D%2213.7%22 id%3D%226%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%231%22%2F%3E%3ClinearGradient x1%3D%229.1%22 y1%3D%2228.7%22 x2%3D%2220.8%22 y2%3D%2240%22 id%3D%220%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%235%22%2F%3E%3ClinearGradient x1%3D%223.4%22 y1%3D%2230.7%22 x2%3D%2219.3%22 y2%3D%2246.6%22 id%3D%225%22 gradientUnits%3D%22userSpaceOnUse%22%3E%3Cstop%2F%3E%3Cstop offset%3D%221%22 stop-opacity%3D%22.8%22%2F%3E%3C%2FlinearGradient%3E%3ClinearGradient x1%3D%2247%22 y1%3D%2219.6%22 x2%3D%2228.4%22 y2%3D%221%22 id%3D%221%22 gradientUnits%3D%22userSpaceOnUse%22%3E%3Cstop stop-opacity%3D%22.5%22%2F%3E%3Cstop offset%3D%221%22 stop-opacity%3D%22.3%22%2F%3E%3C%2FlinearGradient%3E%3ClinearGradient x1%3D%2214.8%22 y1%3D%2226.7%22 x2%3D%2222%22 y2%3D%2234%22 id%3D%223%22 gradientUnits%3D%22userSpaceOnUse%22 xlink%3Ahref%3D%22%235%22%2F%3E%3ClinearGradient x1%3D%222%22 y1%3D%2218.6%22 x2%3D%2218.6%22 y2%3D%222%22 id%3D%224%22 gradientUnits%3D%22userSpaceOnUse%22%3E%3Cstop stop-opacity%3D%220%22%2F%3E%3Cstop offset%3D%221%22 stop-opacity%3D%22.3%22%2F%3E%3C%2FlinearGradient%3E%3ClinearGradient x1%3D%2229.9%22 y1%3D%2245.5%22 x2%3D%2245%22 y2%3D%2230%22 id%3D%222%22 gradientUnits%3D%22userSpaceOnUse%22%3E%3Cstop stop-opacity%3D%22.8%22%2F%3E%3Cstop offset%3D%221%22 stop-opacity%3D%22.5%22%2F%3E%3C%2FlinearGradient%3E%3C%2Fdefs%3E%3Cg fill-rule%3D%22evenodd%22%3E%3Cpath d%3D%22m24 44.85v3.15c-6.15.01-12.29-2.34-16.98-7-4.68-4.69-7-10.82-7-16.96h3.2c0 5.33 2.03 10.67 6.09 14.74 4.06 4.07 9.39 6.11 14.71 6.11%22 fill%3D%22url(%235)%22%2F%3E%3Cpath d%3D%22m40.96 40.96c-4.69 4.69-10.82 7-16.96 7v-3.15c5.33 0 10.67-2.04 14.74-6.11 4.07-4.07 6.1-9.41 6.1-14.74h3.16c-.01 6.14-2.35 12.28-7 16.96%22 fill%3D%22url(%232)%22%2F%3E%3Cpath d%3D%22m44.85 24c0-5.32-2.03-10.65-6.1-14.71-4.07-4.06-9.41-6.09-14.74-6.09v-3.2c6.14.01 12.28 2.35 16.96 7 4.7 4.69 7 10.83 7 16.98h-3.16%22 fill%3D%22url(%231)%22%2F%3E%3Cpath d%3D%22m24 3.2c-5.32 0-10.65 2.03-14.71 6.09-4.06 4.06-6.09 9.39-6.09 14.71h-3.2c-.01-6.15 2.33-12.29 7-16.98 4.69-4.69 10.83-7 16.98-7v3.2%22 fill%3D%22url(%234)%22%2F%3E%3Cpath d%3D%22m24 35.2c-2.87 0-5.74-1.09-7.93-3.29-2.18-2.19-3.27-5.1-3.28-7.91h3.18c0 2.05.78 4.1 2.34 5.66 1.57 1.57 3.62 2.35 5.67 2.34v3.19%22 fill%3D%22url(%233)%22%2F%3E%3Cpath d%3D%22m24 38.4v3.22c-4.51.01-9-1.71-12.45-5.16-3.43-3.43-5.14-7.93-5.15-12.44h3.21c.01 3.68 1.41 7.36 4.21 10.16 2.81 2.82 6.5 4.23 10.19 4.22%22 fill%3D%22url(%230)%22%2F%3E%3Cpath d%3D%22m24 35.2v-3.19c2.05 0 4.1-.78 5.66-2.34 1.57-1.57 2.35-3.61 2.35-5.66h3.19c-.01 2.87-1.1 5.73-3.28 7.91-2.18 2.19-5.1 3.28-7.92 3.29%22 fill%3D%22url(%237)%22%2F%3E%3Cpath d%3D%22m24 12.8c2.87 0 5.73 1.09 7.92 3.27 2.2 2.19 3.29 5.06 3.28 7.93h-3.19c0-2.04-.78-4.08-2.35-5.63-1.56-1.55-3.61-2.33-5.66-2.34v-3.23%22 fill%3D%22url(%236)%22%2F%3E%3Cpath d%3D%22m24 9.61v-3.21c4.5.01 9 1.72 12.44 5.15 3.45 3.44 5.17 7.95 5.16 12.45h-3.22c.01-3.68-1.4-7.37-4.22-10.18-2.81-2.8-6.48-4.2-10.16-4.21%22 fill%3D%22url(%23B)%22%2F%3E%3Cpath d%3D%22m24 12.8v3.23c-2.05 0-4.1.78-5.67 2.34-1.56 1.56-2.34 3.59-2.34 5.63h-3.18c-.01-2.87 1.09-5.74 3.27-7.93 2.19-2.19 5.06-3.28 7.93-3.28%22 fill%3D%22url(%23A)%22%2F%3E%3Cpath d%3D%22m24 6.4v3.21c-3.68-.01-7.37 1.39-10.19 4.21-2.81 2.81-4.21 6.5-4.21 10.18h-3.21c-.01-4.51 1.71-9 5.15-12.45 3.44-3.44 7.95-5.15 12.45-5.15%22 fill%3D%22url(%239)%22%2F%3E%3Cpath d%3D%22m24 41.6v-3.22c3.68-.01 7.36-1.41 10.16-4.22 2.81-2.8 4.21-6.48 4.22-10.16h3.22c-.01 4.5-1.73 9-5.16 12.44-3.44 3.44-7.94 5.16-12.44 5.16%22 fill%3D%22url(%238)%22%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E");
}
```

_master branch_
