### ISSUE TITLE
Comment broke CSS

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#398]
Seems this normal case:

``` css
:link:hover,
:visited:hover
{
    color: #f00 !important; /*!comment*/
}
```

but result is broken CSS:

``` css
:link:hover,:visited:hover{color:red!important;:/*!comment*/}
```

```
:/*!comment*/
^
```
