### ISSUE TITLE
@import file when name contains "__" separator

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#403]
`index.css`

``` css
@import "style__one.css";
@import "style__two.css";
```

`style__one.css`

``` css
.one
{
    color: green;
}
```

`style__two.css`

``` css
.two
{
    color: red;
}
```

and result is:

``` css
one.css)__.one{color:green}two.css)__.two{color:red}
```
