### ISSUE TITLE
Don't removed comments if used !important 

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#410]
Source:

``` css
:link:hover,
:visited:hover
{
    color: #f00 !important; /*!comment*/
    width: 100px; /*!comment2*/
}
```

Result:

``` css
:link:hover,:visited:hover{color:red!important;width:100px/*!comment2*/}
```
