### ISSUE TITLE
Removed semicolon if used !important

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#411]
Source:

``` css
:link:hover,
:visited:hover
{
    color: #f00 !important; /*!comment*/
    width: 100px;
}
```

Result:

``` css
:link:hover,:visited:hover{color:red!important/*!comment*/width:100px}
```
