### ISSUE TITLE
Ensure URLs are normalized at an earlier stage to reduce them properly

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#432]
See https://github.com/jakubpawlowicz/clean-css/issues/357#issuecomment-69305561

```css
/* Assets with non-stylistic syntax */

.asset {

    background-image:url('images/image.png');

}

.asset-2 {

    background-image:    url('images/image.png');

}

.asset-3 {

    background-image:
    url('images/image.png');

}

.asset-4 {

    background-image: url(    'images/image.png');

}

.asset-5 {

    background-image: url(
'images/image.png');

}

.asset-6 {

    background-image: url('    images/image.png');

}

.asset-7 {

    background-image: url('images/image.png    ');

}

.asset-8 {

    background-image: url('images/image.png'    );

}

.asset-9 {

    background-image: url('images/image.png'
);

}

.asset-10 {

    background-image: url('images/image.png')    ;

}

.asset-11 {

    background-image: url('images/image.png')
;

}

.asset-12 {

    background-image: URL('images/image.png');

}
```
