### ISSUE TITLE
Combining large background-image as data-uri

### ISSUE THREAD

**Issue by lupugabriel1** [jakubpawlowicz/clean-css#437]
clean-css does not have a way to treat large background-images defined as data-uris. I'll give you an example of jstree library that was processed to convert resources to data-uris:
```css
 #jstree-dnd.jstree-dnd-responsive > .jstree-ok {
    background-image: url(data:image/png;[----VERY_LARGE_STRING----]=);
    background-position: 0 -200px;
    background-size: 120px 240px;
  }
  #jstree-dnd.jstree-dnd-responsive > .jstree-er {
    background-image: url(data:image/png;[----VERY_LARGE_STRING----]=);
    background-position: -40px -200px;
    background-size: 120px 240px;
  }
```
If cssmin would figure out that ```background-image: url(data:``` should be treated independently and update the code to
```css
 #jstree-dnd.jstree-dnd-responsive > .jstree-ok,
 #jstree-dnd.jstree-dnd-responsive > .jstree-er {
   background-image: url(data:image/png;[----VERY_LARGE_STRING----]=);
}
 #jstree-dnd.jstree-dnd-responsive > .jstree-ok {    
    background-position: 0 -200px;
    background-size: 120px 240px;
  }
  #jstree-dnd.jstree-dnd-responsive > .jstree-er {
    background-position: -40px -200px;
    background-size: 120px 240px;
  }
```
my total size of the css would decrease with 50KB, representing 20% of the total amount of the file. I assume that optimizing this, would dramatically decrease size of files that contain data-uri for different resources ( background-image, fonts ).
Is there any tweak to achieve the above mentioned behavior, or a new processor is required ?
