### ISSUE TITLE
list-style attribute failing depending on order of arguments

### ISSUE THREAD

**Issue by zanona** [jakubpawlowicz/clean-css#446]
I understand that as per the spec, attributes such as `list-style` have its arguments listed as `style, position`.

However, something which works either way in CSS, is to invert such values as an example:

```css
li { list-style: inside none; }
```

Unfortunately when doing so, clean CSS will strip the `none` value from the output resulting in

```css
li { list-style: inside; }
```

_I am not sure about what happens with other CSS attributes accepting arguments in different order_
