### ISSUE TITLE
Bug: Losing padding style with `advanced: true`

### ISSUE THREAD

**Issue by adamschwartz** [jakubpawlowicz/clean-css#452]
In `v3.0.8`, the this CSS:

```css
header,
footer {
  padding-top: 1.25em;
  padding-bottom: 1.25em;
}
header {
  padding-top: 2.5em;
}
footer {
  padding-bottom: 2.5em;
}
```

minifies to:

```css
footer,header{padding-top:1.25em}header{padding-top:2.5em}footer{padding-bottom:2.5em}
```

Essentially the rule `padding-bottom: 1.25em;` is omitted.
