### ISSUE TITLE
bug with multi line strings

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#46]
``` css
.test[title="my very long\
title"] {
    background-image: url("very/long/\
path")
}
```

should become

``` css
.test[title="my very longtitle"]{background-image:url("very/long/path")}
```

and not

``` css
.test[title="my very long \title"]{background-image:url("very/long/\path")}
```
