### ISSUE TITLE
Corrupted gradient

### ISSUE THREAD

**Issue by jods4** [jakubpawlowicz/clean-css#472]
In my project the following attribute:
`background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0) 70%, rgba(0,0,0,0.6)) #eee;`
gets "minified" to (spaces added for readability):
`background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,0) 70%, rgba(0,0,0,.6) ;:) #eee;`
which is of course invalid CSS.

Experiments showed that explicitely adding the `100%` position for the end stop works around the problem.

**Comment by jakubpawlowicz** [comment]
That's odd as the latest 2.2, 3.0, and 3.1 branches output valid content:

`a{background:linear-gradient(rgba(0,0,0,.7),rgba(0,0,0,0)70%,rgba(0,0,0,.6))#eee}`

Which version do you use?

**Comment by jods4** [comment]
I use `gulp-minify-css`, looking into its `node_modules` it uses `clean-css` v3.1.

Could the repro be influenced by what's around this rule? Do you need the whole css file (btw the file also breaks restructuring, I had to turn it off)?

**Comment by jakubpawlowicz** [comment]
If that's possible, could you please share the file? That's the easiest way to find out what's wrong.

**Comment by jods4** [comment]
Here you have:
https://gist.github.com/jods4/01c0f06013be627c1e6b

1. It crashes when I don't use `restructuring: false`.
2. The rule with the broken gradient is `.background`.

If something doesn't repro, let me know. The _real_ input to `clean-css` is piped into `auto-prefixer` first.

**Comment by jakubpawlowicz** [comment]
Thanks for sharing @jods4! This is how the `.backround` rule looks for me:

```css
.background{background:linear-gradient(rgba(0,0,0,.7),rgba(0,0,0,0)70%,rgba(0,0,0,.6)100%)#eee;transition:background 1s;font-family:Calligraphica;font-size:18px;color:#fff;height:100vh;width:100vw}
```

It's likely it breaks due to autoprefixer change - would you be able to share the autoprefixer output?

**Comment by jods4** [comment]
Sorry, my bad. I've copied the version that includes a workaround. It breaks if you remove the "100%" position on the last stop. I updated the gist:
https://gist.github.com/jods4/01c0f06013be627c1e6b

**Comment by jakubpawlowicz** [comment]
:+1: I'll check

**Comment by jakubpawlowicz** [comment]
Unfortunately I still can't reproduce it - https://gist.github.com/jods4/01c0f06013be627c1e6b isn't the output after autoprefixer, is it? It also has no trailing `100%` in `.background`.

**Comment by jods4** [comment]
I did more tests. I removed autoprefixer from my build task -- i.e. I used exactly the file in the gist above -- and I still get this invalid CSS:
`.background{background:linear-gradient(rgba(0,0,0,.7),rgba(0,0,0,0) 70%,rgba(0,0,0,.6);:)#eee;`

I have no idea why you can't repro. Maybe because of some options passed by `gulp-minify-css`?

For reference my gulp task for css looks like this:
```javascript
gulp.task('css', function () {
	gulp.src('CSS/sw.css')
		.pipe(sourcemaps.init())
		//.pipe(autoprefixer({
		//	browsers: ['last 1 Chrome version', 'last 1 FF version', 'last 1 IE version']
		//}))
		.pipe(minifyCss({ restructuring: false }))
		.pipe(sourcemaps.write('.'))
		.pipe(gulp.dest('wwwroot/Content'));
});
```

And FWIW if I don't pass the option `restructuring: false`, the process crashes in `clean-css\lib\properties\extractor.js:47:56`.

**Comment by jakubpawlowicz** [comment]
Ok, that's suspicious as it works fine with restructuring for me. Will investigate.

**Comment by MarcBT** [comment]
Hello, 
to confirm this, I am encountering exactly the same issue / process crash with a similar gulpfile config. 

The css build works fine when commenting either
`.pipe(minifyCss())` 
or
`.pipe(sourcemaps.init())` and `pipe(sourcemaps.write('.'))`

@jakubpawlowicz let me know if you want sources, i can post them later.

**Comment by jakubpawlowicz** [comment]
@MarcBT Please do so, but if possible ones that go directly to clean-css after any autoprefixing or anything else.

**Comment by MarcBT** [comment]
@jakubpawlowicz 
Please find an exemple of the issue on that gist : https://gist.github.com/MarcBT/2a94d67e36cb634d5c7e
Hope this can help. 
Regards

**Comment by jakubpawlowicz** [comment]
@MarcBT Very nice bug report :+1: I'll check again later today.

**Comment by jakubpawlowicz** [comment]
@MarcBT I ran the example locally and it gives me a wrong input indeed. However when I comment out `.pipe(sourcemaps.init())` then it's fine!

I also pulled out main.css file after sass transformation and it looks like this:

```css
/* Variables */
/* Bug #472 */
.shadow {
  /*
  background: -webkit-linear-gradient(top, $color 0%, $color 100%);
  background: -moz-linear-gradient(top, $color 0%, $color 100%);
  background: -ms-linear-gradient(top, $color 0%, $color 100%);
  background: -o-linear-gradient(top, $color 0%, $color 100%);
*/
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 0, rgba(0, 0, 0, 0.1)); }
``` 

and minified using cleancss binary:

```css
.shadow{background:linear-gradient(to bottom,rgba(0,0,0,.1)0,rgba(0,0,0,.1))}
```

I believe there may be something wrong about the sourcemaps plugin instead!
