### ISSUE TITLE
Extra space generated in minified output

### ISSUE THREAD

**Issue by realityking** [jakubpawlowicz/clean-css#475]
Using clean-css 3.1.2 the following source:

```css
li:not(.foo).bar {
    display: block;
}
```
creates this output:

```css
li:not(.foo) .bar{display:block}
```

Note the extra space after the closing parenthesis.
