### ISSUE TITLE
Selectors are moved above @import with restructuring on and --skip-import

### ISSUE THREAD

**Issue by buduchail** [jakubpawlowicz/clean-css#476]
Seems like @import rules are not kept on top when restructuring. When skipping processing of @import rules and using advanced optimization with restructuring, some properties can end up above @import rules which are correctly at the top, thus breaking the generated CSS.

This CSS:

```css
@charset "UTF-8";
@import url(http://fonts.googleapis.com/css?family=Lora:400,700);
a {
	width: 100px;
}
div {
	color: red;
}
.one {
	display: block;
}
.two {
	color: red;
	display: inline;
}
```

will end up as:
```css
@charset "UTF-8";.two,div{color:red}@import url(http://fonts.googleapis.com/css?family=Lora:400,700);a{width:100px}.one{display:block}.two{display:inline}
```
instead of:
```css
@charset "UTF-8";@import url(http://fonts.googleapis.com/css?family=Lora:400,700);.two,div{color:red}a{width:100px}.one{display:block}.two{display:inline}
```
