### ISSUE TITLE
redundant space in minified css

### ISSUE THREAD

**Issue by shahata** [jakubpawlowicz/clean-css#478]
Hello, this is my css:
```css
a:not(.cls)[attr=value] {
  display: none;
}
```

This is the css I get from cleancss 3.1.3:
```css
a:not(.cls) [attr=value]{display:none}
```

It should be:
```css
a:not(.cls)[attr=value]{display:none}
```
