### ISSUE TITLE
remove duplicate selectors

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#48]
``` css
.foo, .foo {
    font-weight: bold;
}
```

should be

``` css
.foo{font-weight:700}
```

instead of

``` css
.foo,.foo{font-weight:700}
```

The same applies for:

``` css
.foo, .bar, .foo {
    font-weight: bold;
}
```

should be

``` css
.foo,.bar{font-weight:700}
```
