### ISSUE TITLE
AlphaImageLoader is mangled after compression

### ISSUE THREAD

**Issue by ben-eb** [jakubpawlowicz/clean-css#489]
```css
body {
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='images/skyline.jpg', sizingMethod='scale');
}
```

After compression:

```css
body{filter:alphaImageLoader(src='images/skyline.jpg', sizingMethod='scale')}
```

I know it's an old property and is only relevant in IE8 and older, but I would expect that compatibility mode preserves this syntax.
