### ISSUE TITLE
Bug with media query and empty selector

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#49]
`cleancss -o out.css in.css -e`

``` css
@media screen {
    .test {}
}

.test1 {
    color: green;
}
```

becomes

``` css
}.test1{color:green}
```
