### ISSUE TITLE
Ensure prefix vendors first

### ISSUE THREAD

**Issue by DontShootMe** [jakubpawlowicz/clean-css#495]
In this case : 

```css
.class{
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
     -moz-box-sizing: border-box;
      -ms-box-sizing: border-box;

}
```

there is no re-ordering putting the W3 rule `box-sizing : border-box` at the end of the group declaration.
But i think it should be !

```css
.class{
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
      -ms-box-sizing: border-box;
          box-sizing: border-box;

}
```
