### ISSUE TITLE
IE8 doesn't render minified css correctly

### ISSUE THREAD

**Issue by shahata** [jakubpawlowicz/clean-css#497]
Hello,
The following CSS:
```css
body {
  background: url(a.png) no-repeat;
}
```
Is minified by clean-css `3.1.6` to:
```css
body{background:url(a.png)no-repeat}
```
But IE8 doesn't parse this correctly and doesn't display the background image :(

This works fine in IE8 when minifying with clean-css `3.0.10`, which produces:
```css
body{background:url(a.png) no-repeat}
```
