### ISSUE TITLE
align-items: flex-start; being removed

### ISSUE THREAD

**Issue by bostondv** [jakubpawlowicz/clean-css#498]
I have some css that's run through Autoprefixer (grunt-autoprefixer) then Clean CSS (grunt-contrib-cssmin). `align-items: flex-start` is being removed from the final minified output.

Original:

```
.panel--top {
  align-items: flex-start; }
```

Autoprefixer:
```
.panel--top {
  -webkit-box-align: start;
  -webkit-align-items: flex-start;
      -ms-flex-align: start;
          align-items: flex-start; }
```

End result (missing `align-items: flex-start`):

```
.panel--top{-webkit-box-align:start;-webkit-align-items:flex-start;-ms-flex-align:start}
```

Using v3.1.7. Checking back older versions appears that it broke from v3.0.10 to v3.1.0.

**Comment by jakubpawlowicz** [comment]
@bostondv Thanks for an informative bug report! I guess you have more than one rule with `align-items: flex-start`, because minifying just this selector works fine:

```css
.panel--top{-webkit-box-align:start;-webkit-align-items:flex-start;-ms-flex-align:start;align-items:flex-start}
```

You can fix it using `restructuring: false` switch until it's fixed.
