### ISSUE TITLE
Duplicate property: value should get de-duped

### ISSUE THREAD

**Issue by kaelig** [jakubpawlowicz/clean-css#500]
```css
.el {
	display: block;
	display: block;
}
```

### Expected

```css
.el{display:block}
```

### Actual

```css
.el{display:block;display:block}
```

Note that I ran these commands to test it:

```cli
cleancss -o test-min-advanced.css test.css
cleancss -o test-min-not-advanced.css test.css --skip-advanced
```

And had the same results with/without advanced optimisations.
