### ISSUE TITLE
*:before and *:after not writing

### ISSUE THREAD

**Issue by erkanunluturk** [jakubpawlowicz/clean-css#506]
## *:before and *:after not writing

```javascript
keepBreaks: true,
restructuring: false
```
input:
```stylus
*
  &
  &:before
  &:after
    box-sizing border-box
```
output:
```css
*,:after,:before{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}
```
