### ISSUE TITLE
Specific border color properties not merging correctly with border-color shorthand properties

### ISSUE THREAD

**Issue by hejmartin** [jakubpawlowicz/clean-css#507]
## Input
```css
.test {
    border-color:rgb(228, 118, 23);
    border-color:rgba(228, 118, 23, 0.9);
    border-right-color:transparent;
}
```

## Expected output
```css
.test{border-color:#e47617 transparent #e47617 #e47617;border-color:rgba(228,118,23,.9) transparent rgba(228,118,23,.9) rgba(228,118,23,.9)}
```
or
```css
.test{border-color:#e47617;border-color:rgba(228,118,23,.9);border-right-color:transparent;}
```

## Actual output
```css
.test{border-color:#e47617 transparent #e47617 #e47617;border-color:rgba(228,118,23,.9)}
```

I'm guessing the issue here is that merging `border-right-color` with the `border-color` containing the rgba  value will actually result in more characters than keeping them separated, but then the `border-right-color` is merged with the first `border-color` which means that browsers with rgba support will not get the transparent bottom border.
