### ISSUE TITLE
A,B,C layout disabling ?

### ISSUE THREAD

**Issue by erkanunluturk** [jakubpawlowicz/clean-css#515]
stylus file:

```stylus
.b
.c
.a
.d
	margin 0
```

output file:

```css
.a,.b,.c,.d{margin:0}

```
