### ISSUE TITLE
opacity improvement

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#52]
IIRC this is perfectly valid:

``` css
foo {
  opacity: 1; /*1.0*/
}
```

And `0.x` is already converted to `.x`, so you could convert `1.0` to `1`. This probably applies to more cases.
