### ISSUE TITLE
Improve longhand into multiple shorthand merging 

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#527]
E.g (shorter value).

`p{background:-webkit-linear-gradient();background:linear-gradient();background-repeat:repeat-x}` ->
`p{background:-webkit-linear-gradient()repeat-x;background:linear-gradient()repeat-x}`

or (default value)

`p{background:-webkit-linear-gradient();background:linear-gradient();background-repeat:repeat}` ->
`p{background:-webkit-linear-gradient();background:linear-gradient()}`

**Comment by jakubpawlowicz** [comment]
these proposed transformations may be invalid due to style cascading, e.g.

```css
.block-1 {
  background:url(image.png) repeat-y;
}
/* ... somewhere further down */
.block-2 {
  background:-webkit-linear-gradient();
  background:linear-gradient();
  background-repeat:repeat-x; /* <- trying to merge this into two properties above */
}
```

where merging in `repeat-x` would not override `repeat-y` from `.block-1` declaration anymore - I recommend we leave it as is to avoid potential issues.
