### ISSUE TITLE
Adds support for multi-file compilation

### ISSUE THREAD

**Issue by talwoolf** [jakubpawlowicz/clean-css#535]
is there a way to loop a directory of .css files and minify them without concatenating them into one file using CLI.

I have tried using ```cat */dirname | cleancss``` but this does not seem to work.

Thanks

**Comment by jakubpawlowicz** [comment]
Well, it should work that way - e.g this command concatenates and minifies relevant files from our `test/fixtures` folder:

`cat test/fixtures/issue-2*.css | cleancss`

```css
.bar{padding:0}.bug-selector,.bug-selector1{background:url(images/b-toolbar.gif)#000;background:linear-gradient(#5e6081,#353340)}.c4:not(.c1,.c2){width:1px}@media (min-width:1px){.c3{width:1px}}
```
