### ISSUE TITLE
Option to remove imported files

### ISSUE THREAD

**Issue by mikkotikkanen** [jakubpawlowicz/clean-css#536]
If you are running master css file which is just split with imports, it would be nice to have r.js styled removing of the imported files

Ie. if

**master.css**

``` css
@import('buttons.css')
body { background: #fff; }
```

**buttons.css**

``` css
.btn { background: #bada55; }
```

Would then become...

**master.css**

``` css
.btn { background: #bada55; }
body { background: #fff; }
```

...with `buttons.css` removed.

If file is not imported anywhere, it would be just minified as usual.
