### ISSUE TITLE
Font-face with comments reduced bad

### ISSUE THREAD

**Issue by olegstepura** [jakubpawlowicz/clean-css#543]
Hi!

I'm using `clean-css` with `gulp-minify-css`

if I have comments like this in @font-face rule:
```css
@font-face {
    font-family: "myfont";
    src: url("../font/myfont.eot"); /* IE9 */
    src: url("../font/myfont.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */

    url("../font/myfont.woff") format("woff"), /* chrome, firefox */
    url("../font/myfont.ttf") format("truetype"), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */

    url("../font/myfont.svg#myfont") format("svg"); /* iOS 4.1- */
    font-style: normal;
    font-weight: normal;
}
```
the generated css is broken like this (I reformatted it back to human-readable):

```css
@font-face {
    font-family: myfont;
    src: url(build/font/myfont.eot);
    src: url(build/font/myfont.eot?#iefix)format("embedded-opentype"),;
    url(build/font/myfont.woff)format("woff"),url(build/font/myfont.ttf)format("truetype"),url(build/font/myfont.svg#myfont)format("svg")font-style: normal;
    font-weight: 400
}
```

Notice the `,;` in the end of line 4. `;` Should not be there, it breaks font-face and such font does not work. Removing comments on line 4 helps, but same happens on next line (line 5). Removing comments on line 5 makes this happen on line 6, etc. (untill all comments in font-face declaration are removed)

**Comment by jakubpawlowicz** [comment]
Please use gulp bound to 3.1.x for now. Fix is coming!

**Comment by jakubpawlowicz** [comment]
Oh, well, I can't reproduce it locally with the latest 3.2 master:

```css
@font-face{
  font-family:myfont;
  src:url(../font/myfont.eot);
  src:url(../font/myfont.eot?#iefix)format("embedded-opentype"),url(../font/myfont.woff)format("woff"),url(../font/myfont.ttf)format("truetype"),url(../font/myfont.svg#myfont)format("svg");
  font-style:normal;
  font-weight:400
}
```
