### ISSUE TITLE
--s1 fails when using --source-map

### ISSUE THREAD

**Issue by shinnn** [jakubpawlowicz/clean-css#549]
### Fixtures

in-with-map.css:

```css
/*!
comment 1
*/a{color:#00f}/*!
comment 2
*/b{color:red}/*!
comment 3
*/i{color:green}/*# sourceMappingURL=in-with-map.css.map */
```

in-with-map.css.map:

```json
{"version":3,"sources":["source.css"],"names":[],"mappings":";;AAGA,EACI,MAAO;;AAMX,EACI,MAAO;;AAMX,EACI,MAAO"}
```

### Versions

```
$ node -v
v1.8.1
$ npm -v
2.8.3
$ cleancss -v
3.2.4
```

### 1. without --source-map (OK)

```
$ cleancss --s1 -o out.css in-with-map.css
```

out.css:

```css
/*!
comment 1
*/a{color:#00f}b{color:red}i{color:green}
```

(works as expected)

### 2. with --source-map (not OK)

```
$ cleancss --s1 --source-map -o out.css in-with-map.css
```

out.css:

```css
/*!
comment 1
*/a{color:#00f}/*!
comment 2
*/b{color:red}/*!
comment 3
*/i{color:green}/*# sourceMappingURL=out.css.map */
```

(still contains too many comments despite `--s1` flag)
