### ISSUE TITLE
IE hack issue

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#556]
Using clean-css v3.2.5, node.js 0.12.2 on Windows 7 64-bit:

```
cleancss --s0 --keep-line-breaks --compatibility ie8 1.css -o 2.css
```

source:

``` css
.caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top: 4px dashed;
  border-top: 4px solid\9;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
}
```

output:

``` css
.caret{display:inline-block;width:0;height:0;margin-left:2px;vertical-align:middle;border-top:4px dashed;border-top:4px solid\0;border-right:4px solid transparent;border-left:4px solid transparent}
```

`\9` becomes `\0`.
