### ISSUE TITLE
merged vendor-prefixed ::placeholder psuedo-selectors  with 2+ rules not working in v3.2.7

### ISSUE THREAD

**Issue by Datanizze** [jakubpawlowicz/clean-css#561]
Hi,

Using the ::placeholder selector with vendor prefixes and more than one rule is not working in v3.2.7. The issue is not present in v3.2.6.

I'm just using `::placeholder`, which gets autoprefixed with -moz, -webkit and so on and is returned as separate selectors with their own (duplicate) rules (i.e. not a comma separated merge).

This works (i.e. the result is _not_ merged):
```css
input:-ms-input-placeholder {
  color:#fafafa;
}

input::placeholder {
  color:#fafafa;
}
```

This doesn't work (i.e. the result is merged):
```css
input:-ms-input-placeholder {
  color:#fafafa;
  text-align:center;
}

input::placeholder {
  color:#fafafa;
  text-align:center;
}
```

Expected result:
```css
input:-ms-input-placeholder{color:#fafafa;text-align:center}input::placeholder{color:#fafafa;text-align:center}
```

Actual result:
```css
input:-ms-input-placeholder,input::placeholder{color:#fafafa;text-align:center}
```

It doesn't seem to matter what kind of rules, just that 1 rule gives the expected result, 2+ doesn't. The merged result makes [browsers sad](http://stackoverflow.com/a/16982510).
