### ISSUE TITLE
Potential merging optimization for linear-gradient?

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#564]
Input:
```css
#a {
	background-image: -webkit-linear-gradient(top,#000,#001);
	background-image: -moz-linear-gradient(top,#010,#011);
	background-image: linear-gradient(to bottom,#030,#031);
}

#b {
	background: #000;
}

#a {
	background-image: -webkit-linear-gradient(top,#100,#101);
	background-image: -moz-linear-gradient(top,#110,#111);
	background-image: linear-gradient(to bottom,#130,#131);
}
```

Prettified output from v3.2.8: (I'm not sure why ```-webkit-linear-gradient``` is removed??)
```css
#a {
    background-image: -moz-linear-gradient(top, #010, #011);
    background-image: linear-gradient(to bottom, #030, #031)
}

#b {
    background: #000
}

#a {
    background-image: -webkit-linear-gradient(top, #100, #101);
    background-image: -moz-linear-gradient(top, #110, #111);
    background-image: linear-gradient(to bottom, #130, #131)
}
```
If I remove the ```#b``` block, then the first ```#a``` block is removed.

On v3.1.9, the first ```#a``` block is removed too, so this is kind of a regression on v3.2.0, not too major though.
