### ISSUE TITLE
Missing media query when last rule is empty

### ISSUE THREAD

**Issue by jkenlooper** [jakubpawlowicz/clean-css#572]
A media query with last rule being empty strips out the whole media query.

```css  
  /* The below media query will be stripped out since the last rule is empty. */

  @media screen and (min-width: 960px) {
    .padded-text {
      padding: 0 10px;
    }
    .an-empty-style-rule {
    }
  }

  /* However, this one won't since it has something in the last rule. */
  @media screen and (min-width: 1200px) {
    .example-with-padding {
      padding: 0 10px;
    }
    .example-1 {
      color: white;
    }
  }
```

Is incorrectly minified to this starting with the version 3.2.0.  The 'min-width: 960px' media query is missing.

```css
  @media screen and (min-width:1200px){.example-with-padding{padding:0 10px}.example-1{color:#fff}}
```

**Comment by jakubpawlowicz** [comment]
@jkenlooper good catch - I'll fix it later today!

**Comment by jakubpawlowicz** [comment]
Fixed in 3.2.10! :+1:

**Comment by keithjgrant** [comment]
I saw a similar issue with keyframes being removed... did this fix cover that as well?  I'm running 3.2.9 from within a lib I don't have control over, so I don't have a quick means of testing.  In my example, this was being stripped out entirely: 

```css
@keyframes blur-in {
    0% {
        transform: scale(.85, .85);
        -webkit-filter: blur(1em);
    }
    100% {
    }
}
```
