### ISSUE TITLE
Breaking border-color in ie up to 11

### ISSUE THREAD

**Issue by d4rkr00t** [jakubpawlowicz/clean-css#578]
clean-css has `-c` option intended to handle ie7-8 issues, but there is an issue with all latest ie, and mobile ie:

This code:
```css
.b:before
{
    border-color: rgba(0,0,0,.2) rgba(0,0,0,.1) rgba(0,0,0,.2) rgba(0,0,0,.1);
}

```

Will be minimized to:
```css
.b:before{border-color:rgba(0,0,0,.2)rgba(0,0,0,.1)}
```

Which doesn't work in all ie up to 11. With `-c ie8` option everything works as expected, produced code will be:
```css
.b:before{border-color:rgba(0,0,0,.2) rgba(0,0,0,.1)}
```

With space between rgba and rgba.

May be better not to remove space between rgba in such cases?
