### ISSUE TITLE
Property de-duplication in @font-face produces semantically different CSS (Disregard; fixed in 2.3.10)

### ISSUE THREAD

**Issue by rjgotten** [jakubpawlowicz/clean-css#581]
**This report can be ignored; under v2.3.10 this bug does not reproduce anymore**

Given is the following input CSS, which uses linked font-family styles for all browsers that support the full `@font-face` syntax and falls back to faux-bold (note use of the regular font-face) for IE8 and below:

```css
@font-face {
	font-family : 'Open Sans';
	src         : url('../fonts/opensans-regular.eot');
	src         : url('../fonts/opensans-regular.eot?#iefix') format('eot'),
	              url('../fonts/opensans-regular.woff') format('woff'),
	              url('../fonts/opensans-regular.ttf') format('truetype');
	font-weight : normal;
	font-style  : normal;
}

@font-face {
	font-family : 'Open Sans';
	src         : url('../fonts/opensans-regular.eot');
	src         : url('../fonts/opensans-regular?#iefix') format('eot'),
	              url('../fonts/opensans-bold.woff') format('woff'),
	              url('../fonts/opensans-bold.ttf') format('truetype');
	font-weight : bold;
	font-style  : normal;
}
```

When processed by CleanCSS (v 3.2.4), even with the `--compatibility=ie8` flag, it will produce the following output CSS (reformatted for readability). Note that the rules related to the `.eot` file format are removed from the set's second block.

```css
@font-face{
	font-family:'Open Sans';
	src:url(../fonts/opensans-regular.eot);
	src:
		url(../fonts/opensans-regular.eot?#iefix) format('eot'),
		url(../fonts/opensans-regular.woff) format('woff'),
		url(../fonts/opensans-regular.ttf) format('truetype');
	font-weight:400;
	font-style:normal
}

@font-face{
	font-family:'Open Sans';
	src:
		url(../fonts/opensans-bold.woff) format('woff'),
		url(../fonts/opensans-bold.ttf) format('truetype');
	font-weight:700;
	font-style:normal
}
```

Not only is this semantically different CSS, it *completely* breaks the pattern used to service IE8 and below.

Said pattern ensures IE8 and below, which does not support the `format()` qualifier gets served an `.eot` file, while everything else gets whatever supported format is first encountered while going through the list.  

Said pattern also protects against a well-known problem with parsing `src` URLs in `@font-face` blocks. IE8 and below will treat everything up to the next encountered character-sequence `);` as the URL. 

As IE8 and below do not support the `format()` qualifier and also do not load fonts on first use (but rather the moment the definitions are parsed) they **will always** fetch broken URLs. In my case URLS of the form:
`/fonts/opensans-bold.woff) format("woff"), url(../fonts/opensans-bold.ttf) format("truetype"`

(For a touch of the truly bizarre: yes; IE's parser does appear to rewrite the single quotes to double quotes inside the unsupported `format()` qualifiers...)

IE8 and below will also fetch these URLs **on each and every page load** as the URLs in question will 404 and that result will never be cached but be retried until the end of days.

This is an extremely nasty issue. I am somewhat surprised no-one has *noticed* this; atleast I don't seem to see this as a resolved issue anywhere.

Will test with more current version as well...

[EDIT]
Seems to be fixed with 2.3.10.

**Comment by jakubpawlowicz** [comment]
@rjgotten Thank for a detailed bug report! I've just tested locally and here's the output I got:

```css
@font-face{
  font-family:'Open Sans';
  src:url(../fonts/opensans-regular.eot);
  src:url(../fonts/opensans-regular.eot?#iefix) format('eot'),url(../fonts/opensans-regular.woff) format('woff'),url(../fonts/opensans-regular.ttf) format('truetype');
  font-weight:400;
  font-style:normal
}
@font-face{
  font-family:'Open Sans';
  src:url(../fonts/opensans-regular.eot);
  src:url(../fonts/opensans-regular?#iefix) format('eot'),url(../fonts/opensans-bold.woff) format('woff'),url(../fonts/opensans-bold.ttf) format('truetype');
  font-weight:700;
  font-style:normal
}
```

That's on 3.2.4 and it's the same on 3.2.10.
Would you be able to share a larger excerpt from your CSS source?
