### ISSUE TITLE
border-color merges too much aggressively

### ISSUE THREAD

**Issue by ogonkov** [jakubpawlowicz/clean-css#587]
clean-css break styles with reordering styles. tested on `clean-css@3.2.10`

```css
.something-else {
    border-color: red;
}

.button {
    border: solid 1px;
}

.button_primary {
    color: #fff;
    background: red;
    border-color: red;
}
```

result:
```css
.button_primary,.something-else{border-color:red}
.button{border:1px solid}
.button_primary{color:#fff;background:red}
```

Now `.button_primary` has broken border, instead of red.
