### ISSUE TITLE
@font-face font-name is changed during minifcation in new 3.3.0 

### ISSUE THREAD

**Issue by maurermax** [jakubpawlowicz/clean-css#590]
We use gulp-minify-css which has recently changed from 3.2.6 to 3.3.0. Since then the following css is not correctly compacted anymore.

````
@import url("//hello.myfonts.net/count/XXXXX");
/* Icomoon Font Styles */
@font-face {
  font-family: "icomoon";
  src: url("/fonts/icomoon.eot");
  src: url("/fonts/icomoon.eot?#iefix") format('embedded-opentype'), url("/fonts/icomoon.woff") format('woff'), url("/fonts/icomoon.ttf") format('truetype'), url("/fonts/icomoon.svg#icomoon") format('svg');
  font-weight: normal;
  font-style: normal; }
[... a lot more]
````

is compacted to
````
@import url(//hello.myfonts.net/count/2e36b9);.icon-fw,.icon-li,.md-text-center{text-align:center}@font-face{font-family:url(web/scss/icomoon);src:url(/fonts/icomoon.eot);src:url(/fonts/icomoon.eot?#iefix) url(/fonts/icomoon.woff) format('woff'),url(/fonts/icomoon.ttf) format('truetype'),url(/fonts/icomoon.svg#icomoon) format('svg');font-weight:400;font-style:normal}
````

the font-family is not a string anymore and is instead transformed to an url statement. 

We are running the process with `processImport: false` to keep the tracking import for our paid fonts.

**Comment by jakubpawlowicz** [comment]
I've just run your code fragment via clean-css 3.3 and here's the output:

```css
@font-face{font-family:icomoon;src:url(/fonts/icomoon.eot);src:url(/fonts/icomoon.eot?#iefix) format('embedded-opentype'),url(/fonts/icomoon.woff) format('woff'),url(/fonts/icomoon.ttf) format('truetype'),url(/fonts/icomoon.svg#icomoon) format('svg');font-weight:400;font-style:normal}
```

At this point I have no idea why font-family is being wrapped in a `url()`.
