### ISSUE TITLE
IE hack issue

### ISSUE THREAD

**Issue by thekondrashov** [jakubpawlowicz/clean-css#595]
I tried to use [IE 10 css hack](http://browserstrangeness.bitbucket.org/css_hacks.html) by Jeff Clayton:
```css
/* only works in IE 10 */
_:-ms-lang(x), .selector { property:value\9; }
```
My real input CSS:
```css
/* IE 10 special css */
_:-ms-lang(x), @-ms-viewport {
  width: auto\9 !important;
}
```
Expected output:
```css
_:-ms-lang(x),@-ms-viewport{width:auto\9!important}
```
But real output is empty.

I use clean-css through `Minify` package for Sublime Text (it uses clean-css directly).
Command line parameters: `--s0 -s --skip-rebase`
Latest version of clean-css (now is v3.3.1) on Windows 8.1 Pro x64.
