### ISSUE TITLE
media queries don't merge

### ISSUE THREAD

**Issue by Lomacar** [jakubpawlowicz/clean-css#607]
Why doesn't clean-css merge the media queries in this case? I have tried various options to no avail.

        #bx-pager img {
            display: inline-block;
            width: 92px;
            vertical-align: middle
        }

        @media (max-width: 768px) {
            #bx-pager img {
                display: none
            }
        }

        #bx-pager span {
            display: inline-block;
            width: 50%;
            text-align: left;
            margin-left: .5em;
            vertical-align: middle
        }

        @media (max-width: 768px) {
            #bx-pager span {
                width: 100%;
                margin-left: 0;
                text-align: center
            }
        }

**Comment by jakubpawlowicz** [comment]
In this case we'd be safe to do so! I'll add it in 3.4.

**Comment by Lomacar** [comment]
Great! Because I have hundreds of these in my code for any given website, because I use LESS/SASS mixins to declare media queries inside the selectors. I find it better to organize responsive code this way. The only downside is hundreds of repetitive media queries, which I assumed CSS optimizers could clean up. But none that I have tried do!

**Comment by aarr0n** [comment]
Is this working? I'm using [gulp-minify-css](https://github.com/murphydanger/gulp-minify-css) and pass the `mediaMerging: true` option along, but the media queries aren't combined.

**Comment by jakubpawlowicz** [comment]
Please make sure to use the latest clean-css and that your media rules are actually mergeable.

**Comment by widoz** [comment]
I have the opposite issue, using grunt and mediaMergin : false under the cssmin task. 
grunt-contrib-cssmin use the 3.3.7 version of clean-css.

**Comment by jakubpawlowicz** [comment]
@widoz please open a separate issue if needed

**Comment by ajmueller** [comment]
@aarr0n did you get this working?  I'm still having this issue with gulp-minify-css and its version of clean-css it's using is 3.4.5.

@jakubpawlowicz when you say to make sure "your media rules are actually mergeable," are there any specifics we need to look out for besides the obvious (e.g. their syntax is all the same)?  For instance, can we specify media type (e.g. `only screen`) or use ems instead of px?

**Comment by jakubpawlowicz** [comment]
@ajmueller in this case mergeable means there are no rules in between that prevent merging. In the example you gave the first media should be removed but I guess that's not the case, am I right?

**Comment by ajmueller** [comment]
@jakubpawlowicz that's correct.

**Comment by jakubpawlowicz** [comment]
^ I've opened a new issue which will address in the next minor version

**Comment by ajmueller** [comment]
Awesome, thanks!

**Comment by chharvey** [comment]
I'm having the same issue, though I don't know what's causing it.

source:
```css
ul, ol { list-style: none; }
.o-List { padding-left: 0; list-style: none; }
@media screen {
  .o-List-s { padding-left: 0; list-style: none; }
}
@media print {
  .o-List-p { padding-left: 0; list-style: none; }
}

.o-Flex { display: flex; line-height: inherit; justify-content: space-between; }
.o-Flex__Item { flex: 1; }
@media screen {
  .o-Flex-s { display: flex; line-height: inherit; justify-content: space-between; }
  .o-Flex__Item-s { flex: 1; }
}
@media print {
  .o-Flex-p { display: flex; line-height: inherit; justify-content: space-between; }
  .o-Flex__Item-p { flex: 1; }
}

.o-Grid { display: flex; line-height: inherit; flex-wrap: wrap; }
.o-Grid__Item { flex: 100%; }
@media screen {
  .o-Grid-s { display: flex; line-height: inherit; flex-wrap: wrap; }
  .o-Grid__Item-s { flex: 100%; }
}
@media print {
  .o-Grid-p { display: flex; line-height: inherit; flex-wrap: wrap; }
  .o-Grid__Item-p { flex: 100%; }
}
```

actual output (formatting added for readability):
```css
.o-List,
ul,
ol { list-style:none }

.o-Flex,
.o-Grid { line-height:inherit }

.o-List { padding-left:0 }
.o-Flex { display:flex; justify-content:space-between }
.o-Flex__Item { flex:1 }
@media screen {
  .o-List-s { padding-left:0; list-style:none }
  .o-Flex-s { display:flex; line-height:inherit; justify-content:space-between }
  .o-Flex__Item-s { flex:1 }
}
@media print {
 .o-List-p { padding-left:0; list-style:none }
 .o-Flex-p { display:flex; line-height:inherit; justify-content:space-between }
 .o-Flex__Item-p { flex:1 }
}

.o-Grid { display:flex; flex-wrap:wrap }
.o-Grid__Item { flex:100% }
@media screen {
  .o-Grid-s { display:flex; line-height:inherit; flex-wrap:wrap }
  .o-Grid__Item-s { flex:100% }
}
@media print{
 .o-Grid-p { display:flex; line-height:inherit; flex-wrap:wrap }
 .o-Grid__Item-p { flex:100% }
}
```

expected output:
```css
.o-List,
ul,
ol { list-style:none }
.o-List { padding-left:0 }
.o-Flex,
.o-Grid { display:flex; line-height:inherit }

.o-Flex { justify-content:space-between }
.o-Flex__Item { flex:1 }
.o-Grid { flex-wrap:wrap }
.o-Grid__Item { flex:100% }
@media screen {
  .o-Flex-s,
  .o-Grid-s { display:flex; line-height:inherit; }
  .o-List-s { padding-left:0; list-style:none }
  .o-Flex-s { justify-content:space-between }
  .o-Flex__Item-s { flex:1 }
  .o-Grid-s { flex-wrap:wrap }
  .o-Grid__Item-s { flex:100% }
}
@media print {
  .o-Flex-p,
  .o-Grid-p { display:flex; line-height:inherit; }
  .o-List-p { padding-left:0; list-style:none }
  .o-Flex-p { justify-content:space-between }
  .o-Flex__Item-p { flex:1 }
  .o-Grid-p { flex-wrap:wrap }
  .o-Grid__Item-p { flex:100% }
}
```
