### ISSUE TITLE
not to strip quotes in url

### ISSUE THREAD

**Issue by zeakd** [jakubpawlowicz/clean-css#611]
@font-face {
      font-family: "BebasNeue";
      font-weight: bold;
      font-style : normal;
      src: url('/fonts/BebasNeue Bold.eot');
      src:
      url("/fonts/BebasNeue Bold.woff") format("woff"),
      url("/fonts/BebasNeue Bold.otf") format("opentype");
    }

Hi.
I write this code and it works, but when I strip quotes like this

    @font-face {
      font-family: "BebasNeue";
      font-weight: bold;
      font-style : normal;
      src: url(/fonts/BebasNeue Bold.eot);
      src:
      url(/fonts/BebasNeue Bold.woff) format("woff"),
      url(/fonts/BebasNeue Bold.otf) format("opentype");
    }

and it doesn't work. no request send.

so I want not to remove that quotes. 

    cleancss -o result.css my.css --compatibility *,+properties.urlQuotes

and I did

    cleancss -o result.css my.css --compatibility *,-properties.urlQuotes
    cleancss -o result.css my.css --compatibility ie8,+properties.urlQuotes

even I changed all urlQuotes property to true in lib/compatibility.js but it still remove my quotes. how can I leave these?

**Comment by jakubpawlowicz** [comment]
Can you provide an example page (jsfiddle, etc) so it can be retested in different browsers? In which browser it fails btw?

**Comment by zeakd** [comment]
I made test in github.io because of font file

#### common index.html
``` html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	 <link rel="stylesheet" href="styles/style.css">
	<title>font-face</title>
</head>
<body>
	<div id = "test">
		<h2>#TEXT</h2>
  	</div>
</body>
</html>
```

#### font-face-example1 style.css (success)
##### http://zeakd.github.io/font-face-example1/
``` css 
@font-face {
  font-family: "BebasNeue";
  font-weight: bold;
  font-style : normal;
  src: url('/font-face-example1/fonts/BebasNeue Bold.eot');
  src:local("☺"),
  url("/font-face-example1/fonts/BebasNeue Bold.woff") format("woff"),
  url("/font-face-example1/fonts/BebasNeue Bold.otf") format("opentype");
}

#test {
	font: 12px/26px BebasNeue;
}
```
#### font-face-example2 style.css (fail)
##### http://zeakd.github.io/font-face-example2/
``` css
@font-face {
  font-family: "BebasNeue";
  font-weight: bold;
  font-style : normal;
  src: url(/font-face-example2/fonts/BebasNeue Bold.eot);
  src:local("☺"),
  url(/font-face-example2/fonts/BebasNeue Bold.woff) format("woff"),
  url(/font-face-example2/fonts/BebasNeue Bold.otf) format("opentype");
}

#test {
	font: 12px/26px BebasNeue;
}
```

I don't know why example2 doesn't send font get request. I knew quote in url is option... 
So I want to leave these quotes. thanks.
