### ISSUE TITLE
Broke rules after optimization

### ISSUE THREAD

**Issue by unlok** [jakubpawlowicz/clean-css#616]
There are two independent files:
```css
.class
{
    border: 2px solid #fc0;
    border-right-width: 0;
}
```
and
```css
.another-class
{
    border: 2px solid #fc0;
}
```

The files can used independently and together. And when it together, result is broken rules:
```css
.class{border-right-width:0}
.another-class,.class{border:2px solid #fc0}
```

First occurs setting of sub-rule `border-right-width` but then occurs settings of `border` and it override sub-rule.

It must be as follows:
```css
.another-class,.class{border:2px solid #fc0}
.class{border-right-width:0}
```
