### ISSUE TITLE
Properties of background are odd?

### ISSUE THREAD

**Issue by yPangXie** [jakubpawlowicz/clean-css#617]
```css
.testBackgroundStyle {
    background: url(../image/logo.png) no-repeat center center;
    background: -webkit-image-set(url(../image/logo.png) 1x, url(../image/logo-retina.png) 2x) no-repeat center;
    width: 100%;
    height: 90px;
    display: block;
}

.otherStyle {margin: 0 10px 10px 10px; padding: 10px 10px 10px 10px; fon-size: 12px; font-style: bold;}
```

I use two "background" and the output is(use default settings)
```css
.testBackgroundStyle{background:center no-repeat;width:100%;height:90px;display:block}.otherStyle{margin:0 10px 10px;padding:10px;fon-size:12px;font-style:bold}
```

The output of background is weird.
