### ISSUE TITLE
Add correct processing of -webkit-image-set

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#618]
```css
.testBackgroundStyle {
    background: url(../image/logo.png) no-repeat center center;
    background: -webkit-image-set(url(../image/logo.png) 1x, url(../image/logo-retina.png) 2x) no-repeat center;
    width: 100%;
    height: 90px;
    display: block;
}
```

See #617
