### ISSUE TITLE
Font property incorrectly minified

### ISSUE THREAD

**Issue by mbenford** [jakubpawlowicz/clean-css#620]
I have one stylesheet containing the following rule:

```css
em { 
  font: normal bold 16px 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```
I've been using version 3.1.0 to minify that stylesheet, and everything's been working just fine.

Today I tried to upgrade to version 3.3.5, but had to go back to 3.1.0 because the aforementioned selector was being minified as

```css
em{font:400 bold 16px "Helvetica Neue",Helvetica,Arial,sans-serif;} 
```

instead of

```css
em{font:normal bold 16px "Helvetica Neue",Helvetica,Arial,sans-serif;} 
```

It seems that the minifier is considering `normal` to be the font weight instead of the font style.

**Additional information**

> Do you use clean-css directly or through any of the plugins?

I use `grunt-contrib-cssmin`, but I tested `clean-css` directly and the problem happened as well.

> What options do you pass to clean-css / the plugin?

None.

> What operating system do you use?

Linux Mint 17.1.
