### ISSUE TITLE
Broken prefixed flex

### ISSUE THREAD

**Issue by gera2ld** [jakubpawlowicz/clean-css#630]
The code below is broken by clean-css:
``` css
.foo {
    -ms-flex: 1 1 0px;
    flex: 1 1 0px;
}
```

The expected output is:
``` css
.foo{-ms-flex:1 1 0px;flex:1 1 0}
```
`-ms-flex` requires a unit to be given for the 3rd argument even if the value is zero, while `flex` accepts just `0`.

But the actual result which breaks layout in IE 10 is like this:
``` css
.foo{-ms-flex:1 1 0;flex:1 1 0px}
```
