### ISSUE TITLE
About css hack

### ISSUE THREAD

**Issue by chenxiaochun** [jakubpawlowicz/clean-css#631]
## the source code

```css
.p-layer {background:none\9\0;}
.a{*width:100px;}
.b{_width:100px;}
```

## after clean-css

```css
.p-layer{background:0 0}
```
