### ISSUE TITLE
border short-hand breaks when using rgba(…) color

### ISSUE THREAD

**Issue by blixt** [jakubpawlowicz/clean-css#638]
This:

``` css
.viewport .download a {
    border: rgba(255, 255, 255, .6) solid 1px;
    border-radius: 9999px;
    color: #fff;
    display: inline-block;
    font-size: 18px;
    padding: 10px 20px;
    text-decoration: none;
}
```

Gets turned into this:

``` css
.viewport .download a{border:rgba(255,255,255,.6) solid;border-radius:9999px;color:#fff;display:inline-block;font-size:18px;padding:10px 20px;text-decoration:none}
```

Note how the `1px` was dropped from the `border` short-hand. This causes the border to have the wrong width.
