### ISSUE TITLE
3.3.8 regression

### ISSUE THREAD

**Issue by dosoft** [jakubpawlowicz/clean-css#643]
3.3.8 incorrectly processes the following code (processImport: false, restructuring: false, keepSpecialComments: 1):

```css
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');

*,
*:before,
*:after {
  box-sizing: inherit;
}

audio:not([controls]) {
  display: none;
  height: 0;
}
```

The resulting css is:

```css
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);*,:after,:before%7Bbox-sizing:inherit%7Daudio:not([controls]){display:none;height:0}
```

Please note on %7B, %7D instead of {, }. Is this a regression after #633?
