### ISSUE TITLE
Polymer's @apply mixins removed after minification

### ISSUE THREAD

**Issue by antonmoiseev** [jakubpawlowicz/clean-css#648]
Input file:
```css
.title {
  @apply(--paper-font-body1);
  flex: 1;
}
```
After I run `cleancss styles.css -o styles.min.css` the output is:
```css
.title{flex:1}
```

Is it possible to preserve `@apply` mixins?

**Comment by jakubpawlowicz** [comment]
Sure :+1:

**Comment by xiulunlin** [comment]
@jakubpawlowicz 
It seems this problem is not fixed when I download `3.4.0-pre`.
Also please support theme name in polymer's `:host` with a double-hyphen prefix. like:  
```css
:host {
    //theme name
    --live-head-theme: {
        line-height: 40px !important;
        vertical-align: middle;
        height: 40px;
        z-index: 999;
    }
}
```
