### ISSUE TITLE
-webkit-image-set() error

### ISSUE THREAD

**Issue by yisibl** [jakubpawlowicz/clean-css#650]
input:

```css
.foo {
  background: url(foo.png) 50% 0 no-repeat; /* fallback */
  background: -webkit-image-set(url(foo.png) 1x,
                                url(foo-2x.png) 2x) 50% 0 no-repeat;
}
```

output:
```css
.foo{background:50% 0 no-repeat}
```

This is a very serious problem, and the result is completely wrong.
