### ISSUE TITLE
Pixel (px) height getting converted to points (pt)

### ISSUE THREAD

**Issue by kfitzgerald** [jakubpawlowicz/clean-css#654]
Greetings!

I just updated the dependencies for one of [my projects](https://github.com/okanjo/okanjo-js) and ran into this issue. I've got a pixel height in a pseudo-selector and it's getting converted into points. 

Here's a snippet of the affected css prior to minification:
```css
.okanjo-product-sidebar .okanjo-product:first-of-type {
  height: 124px;
  border-top: none;
}
```

And here's the snippet after:
```css
.okanjo-product-sidebar .okanjo-product:first-of-type{height:93pt;border-top:none}
```

My expected result is:
```css
.okanjo-product-sidebar .okanjo-product:first-of-type{height:124px;border-top:none}
```

IMHO, pixels and points are two completely different animals, and should not be interchangeable. This is very much undesirable functionality.

After some digging, my current workaround is to kill the pt unit and set the compatibility config:
```js
{ compatibility: '*,-units.pt' }
```

But I don't feel like I should have to do this. Seems more like a bug.

For reference, on my other machine where I did not experience this issue, my dependency graph is:
* gulp-minify-css@1.0.0
 * clean-css@3.1.5
    * commander@2.6.0
    * source-map@0.1.43
      * amdefine@0.1.0

And my new machine where this issue is present, the dependency graph looks like this:
 * gulp-minify-css@1.2.1
  * clean-css@3.4.1
    * commander@2.8.1
      * graceful-readlink@1.0.1
  * source-map@0.4.4
    * amdefine@1.0.0

Thanks!
-Kevin
