### ISSUE TITLE
quotes in @font-face

### ISSUE THREAD

**Issue by Xarksass** [jakubpawlowicz/clean-css#659]
Hello,
i would like to keep quote in my @font-face request.

```css
@font-face {
  font-family: "FontAwesome";
  src: url("fonts/font-awesome/fontawesome-webfont.eot?v=4.4.0");
  src: url("fonts/font-awesome/fontawesome-webfont.eot?#iefix&v=4.4.0") format("embedded-opentype"), url("fonts/font-awesome/fontawesome-webfont.woff2?v=4.4.0") format("woff2"), url("fonts/font-awesome/fontawesome-webfont.woff?v=4.4.0") format("woff"), url("fonts/font-awesome/fontawesome-webfont.ttf?v=4.4.0") format("truetype"), url("fonts/font-awesome/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

no matter what i do it always output :
```css
@font-face{font-family:FontAwesome;src:url(fonts/font-awesome/fontawesome-webfont.eot?v=4.4.0);src:url(fonts/font-awesome/fontawesome-webfont.eot?#iefix&v=4.4.0) format("embedded-opentype"),url(fonts/font-awesome/fontawesome-webfont.woff2?v=4.4.0) format("woff2"),url(fonts/font-awesome/fontawesome-webfont.woff?v=4.4.0) format("woff"),url(fonts/font-awesome/fontawesome-webfont.ttf?v=4.4.0) format("truetype"),url(fonts/font-awesome/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular) format("svg");font-weight:400;font-style:normal}
```
and the problem is that the font isn't loaded that way.

I'm using less-plugin-clean-css to compile and minify my less and i thought it was the plugin who skip the quotes. But i tried to minify a non-minified and compiled version of the css file directly in command line with clean-css and it skipped the quotes.

Is there any solution to keep the quotes in place ?

Thanks in advance for your reply.
