### ISSUE TITLE
Regression from 3.3.10: !important gets dropped if the property is duplicated in a selector

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#669]
Caught my silly authoring mistake when I upgraded from 3.3.10 to 3.4.2 and compared side-by-side:

```css
.one {
	margin: 0;
	margin: 0 !important;
}
```

```
Ngs-Applejack:cleancsstest ngyikp$ npm install clean-css@3.3.10
clean-css@3.3.10 node_modules/clean-css
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── source-map@0.4.4 (amdefine@1.0.0)
Ngs-Applejack:cleancsstest ngyikp$ node_modules/clean-css/bin/cleancss test.css
.one{margin:0!important}

Ngs-Applejack:cleancsstest ngyikp$ npm install clean-css@3.4.2
clean-css@3.4.2 node_modules/clean-css
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── source-map@0.4.4 (amdefine@1.0.0)
Ngs-Applejack:cleancsstest ngyikp$ node_modules/clean-css/bin/cleancss test.css
.one{margin:0}
```

There's no issue if the values are not the same, this does return ```margin:2px!important```
```css
.two {
	margin: 1px;
	margin: 2px !important;
}
```
