### ISSUE TITLE
Suggestion: Lowercase hex colors for more potential gzip savings

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#685]
Currently, this won't be merged into a single selector, I suggest there could be a further optimization to lowercase hex colors only if it's safe to do so.

``` css
.a {background:#abcdef;}
.b {background:#ABCDEF;}
```
