### ISSUE TITLE
Error trying to parse Polymer styles

### ISSUE THREAD

**Issue by felixzapata** [jakubpawlowicz/clean-css#689]
Hi, I've seen the issue #648 related with the `Polymer apply mixins` but I still have errors when trying to reduce the size of the vulcanized file.

I'm trying to reduce the size applying first `gulp-html-minify` and then `gulp-minifi-inline` (this task uses clean-css version 3.4.5). When I do this, my console throws errors in the `wrap-for-optimizing.js` file.

The first error is in the function `isImportant` because the `property[property.length - 1]` is empty, so `property[property.length - 1][0].indexOf` fails. When I fix this, there is another error this time in  `hackType` function and, again, if I fix it, I obtain an error here: `block: isVariable && property[1] && Array.isArray(property[1][0][0])`.

I will try to make a test but, what do you think is the reason that the `property` array received undefined values?

**Comment by jakubpawlowicz** [comment]
@felixzapata could you please share some CSS sources as described in https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md - ideally what goes into clean-css after all previous gulp plugins ran?

**Comment by felixzapata** [comment]
hi, i am trying to isolate some of the css to do a test because the result vulcanized file is big due to the project itself. That is the reason my first attempt was to make some fixes directly over the task to check the process.

Regards.

**Comment by jakubpawlowicz** [comment]
Thanks @felixzapata - if you can't share it publicly feel free to email it to me (see package.json).

**Comment by felixzapata** [comment]
hi @jakubpawlowicz , after (a "little" investigation and) extract all the styles of my vulcanized file and create separate files (more than 30), I've discovered the problem who is throwing the error. 

For example, this css file will throw an error (in my last tests, I've used gulp-css-minify that is a wrap for clean-css):

``
:root {
  --separator: {
    border-top: 1px solid #e0e1e4;
    border-bottom: var(--border-white);
  };
  --layout-fixed-left: {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
  };
  --background: {red};
  --my-toolbar-title-color: green;
  --stagLight: 'Helvetica, Arial, sans-serif';
  --size: 1.75em;
  /* Stag Sans light */
  .foobar {
    @apply(--separator);
    color: var(--my-toolbar-title-color, blue);
    font-family: var(--stagLight);
    font-size: var(--size);
    background:var(--background);
  };
}
``

But this other css file will not throw an error:

``
:root {
  --separator: {
    border-top: 1px solid #e0e1e4;
    border-bottom: var(--border-white);
  };
  --layout-fixed-left: {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
  };
  --background: red;
  --my-toolbar-title-color: green;
  --stagLight: 'Helvetica, Arial, sans-serif';
  --size: 1.75em;
  /* Stag Sans light */
  .foobar {
    @apply(--separator);
    color: var(--my-toolbar-title-color, blue);
    font-family: var(--stagLight);
    font-size: var(--size);
    background:var(--background);
  };
}
``

The problem, and I think is related with an error to write the css properties, is when you use a css variable with a single value with brackets.  

I mean: `--background:{red}` instead of `--background:red`.

I've reviewed the css specification about [css variables in the Mozilla website](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), so I think the syntax with brackets is not allowed.

**Comment by jakubpawlowicz** [comment]
Thanks @felixzapata for more details! I think you are right about the error being raised - how come `--background:{red}` even shows up there?

**Comment by felixzapata** [comment]
Sorry @jakubpawlowicz, your question is why are the brackets in the variable? I think that the person who have written the styles, unintentionally, put (or kept because started with some properties) the brackets in these cases.

**Comment by jakubpawlowicz** [comment]
Does it mean it still works with the brackets? I have never seen those before.

**Comment by felixzapata** [comment]
Yes it works (unintentionally). Our scenery is: the styles are written with SASS and we use them inside Polymer components.

**Comment by jakubpawlowicz** [comment]
So as far as I understand those brackets are specific to Polymer component styling, right? Trying to get the context here. Are there any docs covering those?

**Comment by felixzapata** [comment]
Well, if you use the brackets is because you are going to use it as a mixin with the  `@apply`. There was an [issue about that but is resolved](https://github.com/jakubpawlowicz/clean-css/issues/648).

By the other hand, you can read information about Polymer component styling [here](https://www.polymer-project.org/1.0/docs/devguide/styling.html). (find "Custom CSS properties" and "Custom CSS mixins")

**Comment by jakubpawlowicz** [comment]
Ok, stay tuned for updates. The reason it doesn't work is because I have never thought it was possible, and it does not work with normal (non-Polymer) variables.

**Comment by felixzapata** [comment]
Maybe you have not to worry to much about that and only try to throw a message that informs about the format instead of the task is finished.

Really, the correct format with a single value is without brackets and only if you add more properties, the brackets are mandatory.

**Comment by jakubpawlowicz** [comment]
I think we should just handle it transparently.

**Comment by jakubpawlowicz** [comment]
I've just retested it and (at least in Firefox) it doesn't work with curly braces around values, like `--background:{red}`. I don't know the reason it works inside polymer components. Do you have any ideas?

**Comment by felixzapata** [comment]
do you have the example code in a gist or codepen?

**Comment by jakubpawlowicz** [comment]
Something as simple as http://codepen.io/anon/pen/YyRqPq - if you remove braces around variable value then it works fine. After giving it a thought I am slightly hesitant to support it as the syntax is Polymer specific.

**Comment by felixzapata** [comment]
hummm,  the [specification](https://drafts.csswg.org/css-variables/#defining-variables) and [examples](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) are very clear. So is ok that with braces the example does not work. In Chrome the example should not work neither. 

Maybe there are differences between how Chrome and Firefox manage the css variables. I will make an isolate and simple example and it is possible I will open an issue to the Polymer project to ask about it.

**Comment by felixzapata** [comment]
I think the problem is related with the _sim_ that Polymer loads to use the CSS variables:

_Polymer includes a shim for custom CSS properties inspired by (and compatible with) the future W3C CSS Custom Properties for Cascading Variables specification (see Using CSS Variables on the Mozilla Developer Network)._

_Cross-platform support for custom properties is provided in Polymer by a JavaScript library that approximates the capabilities of the CSS Variables specification for the specific use case of theming custom elements, while also extending it to add the capability to mixin property sets to rules as described above. It is important to note that this is not a full polyfill, as doing so would be prohibitively expensive; rather this is a shim that is inspired by that specification and trades off aspects of the full dynamism possible in CSS with practicality and performance._

[Styling local DOM - Developer guide](https://www.polymer-project.org/1.0/docs/devguide/styling.html)

**Comment by felixzapata** [comment]
[I have opened a issue about that.](https://github.com/Polymer/polymer/issues/2709)

**Comment by jakubpawlowicz** [comment]
@felixzapata :100: - thanks for tracking it down! Let's see what Polymer people will say about it.

**Comment by zanona** [comment]
hey guys, have you had any further thoughts on this?
Polymer works with __mixins__ and this is what is causing the issue with clean-css as a mixin can be declared as:


```css
:root {
    --my-mixin: {
      color: teal;
      background-color: goldenrod;
    }
}
.another-element {
    font-size: 2em;
    @apply(--my-mixin);
    text-transform: uppercase;
}
```

More about it [here](https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins). It would be great if it was possible to handle this kind of input?

I am running through post-css and autoprefixer prior clean-css and those didn't have issues with that fortunately :)

**Comment by jakubpawlowicz** [comment]
@zanona this issue was originally about using parentheses inside property declarations, see related issue https://github.com/Polymer/polymer/issues/2709

Here's the output I get from your snippet with clean-css 3.4.13 (latest version):
```css
:root{--my-mixin:{color:teal;background-color:#daa520};}
.another-element{font-size:2em;@apply(--my-mixin);text-transform:uppercase}
```

Anything wrong about it?

**Comment by zanona** [comment]
Hey @jakubpawlowicz,

Yes, unfortunately it still seems to be an issue when declaring multiple mixins, where everything declared after a mixin will be stripped out inside that element?

Using the following, for example:

```css
:root {
  --foo: red;
  --my-mixin: { color: teal; }
  --bar: yellow; /* <-- this will be stripped out on clean-css */
  font-size: 1em;
}
```

output:

```css
:root{--foo:red;--my-mixin:{color:teal};font-size:1em} /*missing `--bar`*/
```

```css
:root {
  --foo: red;
  --my-mixin: { color: teal; }
  --another-mixin: { color: blue; }  /* <-- this will be stripped out on clean-css */
  --bar: yellow;  /* <-- this will be stripped out on clean-css */
  font-size: 1em;
}
```

output:

```css
:root{--foo:red;--my-mixin:{color:teal};font-size:1em} /*missing `--another-mixin` and `--bar`*/
```

**Comment by carolirod** [comment]
just in case it helps but mixins MUST end with ;

You have:

```css
:root {
  --foo: red;
  --my-mixin: { color: teal; }
  --bar: yellow; /* <-- this will be stripped out on clean-css */
  font-size: 1em;
}
```

```css
:root {
  --foo: red;
  --my-mixin: { color: teal; };      /** here a dot and a comma could make a difference **/
  --bar: yellow; /* <-- this will be stripped out on clean-css */
  font-size: 1em;
}
```
