### ISSUE TITLE
Possibly a small space issue with the first class after an @media query

### ISSUE THREAD

**Issue by mhulse** [jakubpawlowicz/clean-css#69]
Hi again!

I'm using [gunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin), and (based on `package.json`) it's running `"version": "0.8.3"` of `clean-css`.

With that said, this is a totally minor thing, but I thought it would be worth mentioning.

Take this code for example:

``` css
.wiffle { margin: 0 10px; }
.foo { font-weight: bold; }

@media only screen and (min-width: 665px) {

    .wiffle {
        width: 640px;
        margin: 0 auto;
    }

}

.baz { color: red; }

@media only screen and (min-width: 1005px) {

    .wiffle { width: 980px; }

    .bing {
        color: green;
        font-weight: bold;
    }

}

.other {
    font-style: italic;
    float: left;
    display: inline;
}
```

... and here's the output:

``` css
.wiffle{margin:0 10px}.foo{font-weight:700}@media only screen and (min-width: 665px){.wiffle{ width:640px;margin:0 auto}}.baz{color:red}@media only screen and (min-width: 1005px){.wiffle{ width:980px}.bing{color:green;font-weight:700}}.other{font-style:italic;float:left;display:inline}
```

See where there's a space before the first property of the first class after an `@media` declaration?

Not a biggy at all. Just thought it might be worth mentioning (that is, if it hasn't been mentioned already).

I love this code, it's been so useful! Thanks for sharing it with the rest of the world! :+1:

Thanks for listening!

Cheers,
Micky
