### ISSUE TITLE
list-style shorthandCompacting doesn't work with list-style-image as a gradient

### ISSUE THREAD

**Issue by grouphoot** [jakubpawlowicz/clean-css#712]
Found on grunt-contrib-cssmin 0.14.0
```
ul li {
    list-style-type: square;
    list-style-position: outside;
    list-style-image: -webkit-gradient(radial, 50% 50%, 3, 50% 50%, 6, from(#aaaaaa), color-stop(0.8, #aaaaaa), to(#aaaaaa));
}
```
results as
`ul li{list-style:square}`

**Comment by grouphoot** [comment]
Happens on grunt-contrib-cssmin 0.14.0

**Comment by ngyikp** [comment]
Run ```npm ls clean-css``` and see if it's version 3.4.8, I tried your CSS and it seems fine:

```css
ul li{list-style:square -webkit-gradient(radial,50% 50%,3,50% 50%,6,from(#aaa),color-stop(.8,#aaa),to(#aaa))}
```
