### ISSUE TITLE
#808080 gets converted to "grey"

### ISSUE THREAD

**Issue by josh18** [jakubpawlowicz/clean-css#727]
Fresh install of clean-css, just running `clean-css test.css`
**Input**
```css
body {
    color: #808080;
}
```
**Output**
```css
body{color:grey}
```
Not sure why it is doing this, other hex colour codes seem to be fine. For example:
```
#000 -> #000
#000000 -> #000
black -> #000
```
