### ISSUE TITLE
Skip merging same properties while allowing same selectors to be merged?

### ISSUE THREAD

**Issue by corysimmons** [jakubpawlowicz/clean-css#730]
I want to merge same selectors, but want to keep same properties for fallback reasons.

**Comment by jakubpawlowicz** [comment]
You may want to use `--skip-aggressive-merging` and `--skip-compacting` together. Hope that helps!

**Comment by corysimmons** [comment]
I already tried `--skip-aggressive-merging`. It doesn't merge same selectors.

```css
a {
  color: blue;
}
a {
  font-size: 16px;
  font-size: 1rem;
}
```

turns into

```css
a {
  color: blue;
  font-size: 1rem;
}
```

when I'm looking for

```css
a {
  color: blue;
  font-size: 16px;
  font-size: 1rem;
}
```
