### ISSUE TITLE
The transformation of the background-color in the background

### ISSUE THREAD

**Issue by Wernalur** [jakubpawlowicz/clean-css#759]
Hello. I have the following SASS code:

```
a
{
    background-color: rgba(0, 0, 0, 0.5);
    background-image: url("https://example.org/pic.png");
    background-repeat: no-repeat;
    background-position: center center;

    &:hover
    {
        background-color: $var;
    }
}
```

After use clean-css I get

```
a{background:url("https://example.org/pic.png") no-repeat center center rgba(0,0,0,.5)}
a:hover{background:#2ecc71}
```

As you can imagine the picture thus erased. I can do something with this?

**Comment by jakubpawlowicz** [comment]
Could you tell me why picture is erased? Do you mean `rgba` gets merged into background and it's broken in IE<9?

**Comment by Wernalur** [comment]
I want to at hover-effect change only the color of the background, so use design background-color. As a consequence of optimization "-color" cut off, and instead of a picture of color + I get a background consisting of color.

Maybe it's just a bad practice and I should write?

```
a
{
    background-color: rgba(0, 0, 0, 0.5);
    background-image: url("https://example.org/pic.png");
    background-repeat: no-repeat;
    background-position: center center;

    &:hover
    {
        background: $var url("https://example.org/pic.png") no-repeat center center;
    }
}
```

**Comment by jakubpawlowicz** [comment]
Nah, I don't see the reason it doesn't work.

This is the output I'm getting:
```css
a{background-color:rgba(0,0,0,.5);background-image:url(https://example.org/pic.png);background-repeat:no-repeat;background-position:center center}
a:hover{background-color:#2ecc71}
```

Any ideas why yours is different? Which version of clean-css do you use?
