### ISSUE TITLE
Single quotation marks inside double-quoted strings are removed

### ISSUE THREAD

**Issue by chris-morgan** [jakubpawlowicz/clean-css#763]
Example:

```css
:root {
    background: url("data:image/svg+xml,%3csvg%20xmlns%3d'http://www.w3.org/2000/svg'/%3e");
}
```

This is cleaned to:

```css
:root{background:url(data:image/svg+xml,%3csvg%20xmlns%3dhttp://www.w3.org/2000/svg/%3e)}
```

This is glaringly incorrect: it was fine to remove the double quotation marks, but definitely not to scrap the single quotation marks! The change breaks the embedded SVG.

If the `data:` URI contains `)` or ` ` it will leave all the quotes in, but that’s not a desirable solution.

As it stands, the workaround is to replace each `'` with `%27`.
