### ISSUE TITLE
calc isn't retained properly for background-position

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#779]
```css
.one {
	width: 1px;
	width: -webkit-calc(1px * 2);
	width: -moz-calc(1px * 2);
	width: calc(1px * 2);
}

.two {
	background-position: 1px 0;
	background-position: -webkit-calc(1px * 2) 0;
	background-position: -moz-calc(1px * 2) 0;
	background-position: calc(1px * 2) 0;
}
```

Version is 3.4.14

Output:
```
.one{width:1px;width:-webkit-calc(1px * 2);width:-moz-calc(1px * 2);width:calc(1px * 2)}
.two{background-position:calc(1px * 2) 0}
```

**Comment by ngyikp** [comment]
Opps, I hit the submit button too early, just edited

**Comment by jakubpawlowicz** [comment]
Thanks @ngyikp, will be fixed in next release.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.4.15.

**Comment by ngyikp** [comment]
Wow, that's a fast fix, thanks ^_^

Though I found another regression caused by upgrading from 3.4.14 to 3.4.15 (gotta love real world CSS :p )

Input:
```css
.abc {
	background: #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111);
	background-image: url(a.png), linear-gradient(to bottom, #000, #111);
}
```

3.4.14 is pretty much the same:
```css
.abc {
	background: #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111);
	background-image: url(a.png), linear-gradient(to bottom, #000, #111)
}
```

3.4.15 hoists the `linear-gradient` to the background shorthand, which doesn't work for browsers that don't support it:
```css
.abc {
	background: url(a.png), linear-gradient(to bottom, #000, #111) #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111)
}
```

I guess I should create another new issue to make it easier to track for you?
