### ISSUE TITLE
Regression: v3.4.15 hoists the linear-gradient background to the top

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#781]
Input:
```css
.abc {
	background: #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111);
	background-image: url(a.png), linear-gradient(to bottom, #000, #111);
}
```

3.4.14 is pretty much the same:
```css
.abc {
	background: #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111);
	background-image: url(a.png), linear-gradient(to bottom, #000, #111)
}
```

3.4.15 hoists the `linear-gradient` to the background shorthand, which doesn't work for browsers that don't support it:
```css
.abc {
	background: url(a.png), linear-gradient(to bottom, #000, #111) #fff;
	background-image: url(a.png), -webkit-linear-gradient(top, #000, #111);
	background-image: url(a.png), -moz-linear-gradient(top, #000, #111);
	background-image: url(a.png), -o-linear-gradient(top, #000, #111)
}
```
