### ISSUE TITLE
Classes with escaped at sign (`\@`) do not merge

### ISSUE THREAD

**Issue by rdmurphy** [jakubpawlowicz/clean-css#786]
Hello! Don't believe I saw another instance of this in the issues.

I'm running `clean-css` against a file that has class names with escaped characters in them. The output generates fine, but an escaped at sign (`\@`) prevents `clean-css` from properly concatenating classes that contain the same properties. Here's an example (`clean-css` is being run with all defaults except `-b` being set to prevent line-breaks):
#### Without escaped @

Input:

``` css
.col-1-4 {
  width: 25%; }

.col-2-4 {
  width: 50%; }

.col-1-2 {
  width: 50%; }

.col-3-4 {
  width: 75%; }

.col-4-4 {
  width: 100%; }

.col-1-1 {
  width: 100%; }
```

Output:

``` css
.col-1-4{width:25%}
.col-1-2,.col-2-4{width:50%}
.col-3-4{width:75%}
.col-1-1,.col-4-4{width:100%}
```
#### With escaped @

Input:

``` css
.col-1\@4 {
  width: 25%; }

.col-2\@4 {
  width: 50%; }

.col-1\@2 {
  width: 50%; }

.col-3\@4 {
  width: 75%; }

.col-4\@4 {
  width: 100%; }

.col-1\@1 {
  width: 100%; }
```

Output:

``` css
.col-1\@4{width:25%}
.col-2\@4{width:50%}
.col-1\@2{width:50%}
.col-3\@4{width:75%}
.col-4\@4{width:100%}
.col-1\@1{width:100%}
```

I've tried this with a few other escapable characters — `~`, `/`, `+` — and they all worked as expected. I didn't try them all ([a list can be found in this blog post](https://mathiasbynens.be/notes/css-escapes)) but in my small set of tests it appeared to be unique to `@`.
