### ISSUE TITLE
Line breaks inside background tag cause bad css

### ISSUE THREAD

**Issue by tollus** [jakubpawlowicz/clean-css#790]
Hi,

Please let me know if this is just bad input/css. I've resolved this in my project just by removing the line breaks. But this may cause issues for someone else?

Source: 
```css
#loader {
	background: rgb( 255, 255, 255 )
				url(../images/ajax-loading.gif)
				50% 50%
				no-repeat;
}
```

Output:
```css
#loader{background:50%}
```

Expected Output: (or something similar)
```css
#loader{background:url(../images/ajax-loading.gif) 50% 50% no-repeat #fff}
```

I am using grunt, but I was able to replicate using the command line:
`./node_modules/.bin/cleancss input.css`

Version: `3.4.18`

Thanks!

**Comment by jakubpawlowicz** [comment]
Hi @tollus! Unfortunately I cannot replicate it as `cleancss input.css` on 3.4.18 on Linux and node 4 gives me the right output:

```css
#loader{background:url(../images/ajax-loading.gif) 50% 50% no-repeat #fff}
```

Could you please give us more details, as described in https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md#bug-reports?
