### ISSUE TITLE
Quotes with multiline strings

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#80]
``` css
.test[title="my_very_long_\
title"] {
    background-image: url("my/very/long/\
path")
}
```

becomes

``` css
.test[title="my_very_long_title"]{background-image:url("my/very/long/path")}
```

As you can see the quotes can be removed from `title` and `url` since there is no space.
