### ISSUE TITLE
disappearing border width when using CSS variables

### ISSUE THREAD

**Issue by jlowcs** [jakubpawlowicz/clean-css#806]
Input:

``` css
.foobar1a {
    border: solid red 1px;
}
.foobar1b {
    border: 1px green solid;
}
.foobar2a {
    border: solid var(--test1) 1px;
}
.foobar2b {
    border: 1px var(--test1) solid;
}
.foobar3 {
    border: 1px solid var(--test1);
}
```

Output (with `cleancss testfile.css -b`):

``` css
.foobar1a{border:1px solid red}
.foobar1b{border:1px solid green}
.foobar2a{border:var(--test1) solid}
.foobar2b{border:1px var(--test1) solid}
.foobar3{border:1px solid var(--test1)}
```

On `.foobar2a`, the border width has disappeared. Probably a parsing issue.

Work around is to put the variable at the end (see `.foobar3`).
