### ISSUE TITLE
Incorrect background shorthand handling

### ISSUE THREAD

**Issue by breeswish** [jakubpawlowicz/clean-css#808]
When there are no spaces between `)` and `url` (usually generated by another css minifier), `clean-css` will break:

``` css
.a{background:rgba(0,0,0,0)url(//example.com/a.jpg)}
```

Minified:

``` css
.a{background:0 0}
```
