### ISSUE TITLE
multiple @charset removal results in a useless space

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#81]
``` css
@charset 'utf-8';
div :before {
  display: block;
}
@charset 'utf-8';
a {
  color: #f10;
}
```

becomes

``` css
@charset 'utf-8'; div :before{display:block}a{color:#f10}
```

Interestingly, this works fine:

``` css
@charset 'utf-8';

div :before {
    display: block;
}

@charset 'utf-8';

a {
    color: #f10;
}
```
