### ISSUE TITLE
Incorrect background transformation

### ISSUE THREAD

**Issue by pocketjoso** [jakubpawlowicz/clean-css#812]
Possibly related to #808. 
# Input

``` css
body {
  background: #;
}
```
# Result

```
body {
  background: 0 0;
}
```
# Expected

`<nothing>`,
 or at least not `background: 0 0`, which I found renders as black in some browsers.
