### ISSUE TITLE
Option to disable renaming of animation names

### ISSUE THREAD

**Issue by KuroNoDev** [jakubpawlowicz/clean-css#823]
assume I have a file that has
```css
.class1 {
  animation: owo 1s;
}

@keyframe owo {
  ...
}
```
and on another separate file
```css
.class2 {
  animation: whatsthis 1s;
}

@keyframe whatsthis {
  ...
}
```
both will end up having the same animation and keyframe name
```css
/* file 1 */
.class1 {
  animation: a 1s;
}

@keyframe a {
  ...
}

/* file 2 */
.class2 {
  animation: a 1s;
}

@keyframe a {
  ...
}
```

Is there a way to prevent this? What I'm thinking is not minifying the other file or just disable variable renaming if possible
