### ISSUE TITLE
"display: -webkit-box;" was removed

### ISSUE THREAD

**Issue by heeroluo** [jakubpawlowicz/clean-css#825]
"display: -webkit-box;" will be removed unless I set the value of "advanced" to false.

**Comment by jakubpawlowicz** [comment]
Could you provide some details, like a CSS snippet?

**Comment by heeroluo** [comment]
``` css
.dl-cover__half {
	height: 50%;
	display: -webkit-box;
	-webkit-box-orient: horizontal;
	-webkit-box-pack: center;
	-webkit-box-align: center;
	display: box;
	box-orient: horizontal;
	box-pack: center;
	box-align: center;
}
```
