### ISSUE TITLE
Missing the close parenthesis.

### ISSUE THREAD

**Issue by zeed-w-beez** [jakubpawlowicz/clean-css#828]
Hi,
i got some css as below, from [here](http://stackoverflow.com/questions/9328832/how-to-apply-specific-css-rules-to-chrome-only):
```css
/* Chrome 22-28 */
@media screen and(-webkit-min-device-pixel-ratio:0) {
  .logo img{-chrome-:only(; 
     image-rendering:-webkit-optimize-contrast;
  );} 
}
```
after `gulp.pipe(cleancss({advanced:false})) `

i got this:

```css
@media screen and(-webkit-min-device-pixel-ratio:0){.logo img{-chrome-:only(;image-rendering:-webkit-optimize-contrast}}
```
but, i want this:
```css
@media screen and(-webkit-min-device-pixel-ratio:0){.logo img{-chrome-:only(;image-rendering:-webkit-optimize-contrast;);}}
```
The close paren is missing, am i wrong?

npm version: 3.10.6
gulp version: 3.9.1  
clean-css version: 3.4.20

**Comment by jakubpawlowicz** [comment]
Wow, I haven't seen such hack before. Thanks for bringing it up!

**Comment by SJern** [comment]
Hi Jakub,

I am having a similar issue. Here is what my css looks like before cssmin and after compass:dist
```
@font-face {
  /* line 211, ../modules/dashboard/dashboard.scss */
  .redash-query {
    font-family: 'Glyphicons Halflings';
    src: url("../fonts/glyphicons-halflings-regular.eot");
    src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("../fonts/glyphicons-halflings-regular.woff2") format("woff2"), url("../fonts/glyphicons-halflings-regular.woff") format("woff"), url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"), url("../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format("svg");
  }
}
```

Here is what it looks like after cssmin
```
@font-face{.redash-query{font-family:'Glyphicons Halflings';src:url(../fonts/glyphicons-halflings-regular.eot);src:url(../fonts/glyphicons-halflings-regular.eot?#iefix) format("embedded-opentype"),url(../fonts/glyphicons-halflings-regular.woff2) format("woff2"),url(../fonts/glyphicons-halflings-regular.woff) format("woff"),url(../fonts/glyphicons-halflings-regular.ttf) format("truetype"),url(../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format("svg")}
```
notice how it originally had ;}} following (“svg”)
but is now only left with one } ?

Have you figured out the missing parenthesis problem? Thanks!

npm version: 3.10.7
grunt-contrib-cssmin version: 1.0.2

**Comment by zeed-w-beez** [comment]
@SJern 
no offense.
May be syntax error, try the [W3C](http://www.w3schools.com/cssref/css3_pr_font-face_rule.asp) demo , like this :
```css
@font-face {
    font-family: 'GH';
    src: url("../fonts/glyphicons-halflings-regular.eot");
    src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("../fonts/glyphicons-halflings-regular.woff2") format("woff2"), url("../fonts/glyphicons-halflings-regular.woff") format("woff"), url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"), url("../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format("svg");
}

.redash-query {
    font-family: 'GH'
}
```
