### ISSUE TITLE
[4.0.0-pre] Regression in handling selectors with single/double quotes

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#843]
Migrated from https://github.com/jakubpawlowicz/clean-css/issues/842#issuecomment-267643167

Input:
```css
.a[title="a b c's d e f"] {background:#000;}
.b[data-json='"aaaa":"bbbb"'] {background:#111;}
```

Terminal:
```
Ngs-Applejack:test ngyikp$ npm install git://github.com/jakubpawlowicz/clean-css
/Users/ngyikp/Desktop/test
└─┬ clean-css@4.0.0-pre  (git://github.com/jakubpawlowicz/clean-css.git#a18f86c69fd9e5cc08bf52c501f040554f8017c3)
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  └── source-map@0.5.6 
```

Output:
```css
.a[title="a b c'sdef"]{background:#000}
.b[data-json='aaaa:bbbb']{background:#111}
```
