### ISSUE TITLE
Property merging bug

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#852]
I was hunting around for #800 when I encounter this bug:
```css
a{
  border-top-color:red;
}
a{
  border-top-width:10px;
}
a{
  border:magenta;
}
```
... gets optimised into:
```css
a{border:#ff00ff}
```
Note the missing `border-top-width`. Happens on both `3.4.23` (default options) and master (with `{level:2}`)
