### ISSUE TITLE
broken @ charset

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#86]
Using the files from the /bench dir.

```
cleancss TP-demo.css -o TP-demo-Clean-CSS.css --s0
```

results in:

``` css
@charset "."; .ui-helper-hidden{display:none}...
```

instead of

``` css
@charset 'UTF-8';.ui-helper-hidden{display:none}.
```

Notice the space after `@charset`.

BTW, are the double quotes replaced with single quotes in the `@charset` declarations?
