### ISSUE TITLE
space not removed before !important

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#88]
``` bat
cleancss --s0 -b -e -o out.css in.css
```

``` css
@media (min-width: 768px){
    #libraryNavbar{
        /*width:67.5%;*/
    }
    .marg10Top10Bottom{
    margin-top:5px ! important;
    }
}
```

becomes

``` css
@media (min-width:768px){
.marg10Top10Bottom{margin-top:5px! important}}
```

while it should be

``` css
@media (min-width:768px){
.marg10Top10Bottom{margin-top:5px!important}}
```
