### ISSUE TITLE
Adjacent rules with `:hover::after` don't get merged

### ISSUE THREAD

**Issue by ngyikp** [jakubpawlowicz/clean-css#886]
Input:
```css
.a:hover:after {color: #000;}
.b:after {color: #000;}

.c:hover::after {color: #111;}
.d:hover::after {color: #111;}
.e::after {color: #111;}
```

Output from clean-css 3.4.24:
```
$ ./node_modules/.bin/cleancss in.css

.a:hover:after,.b:after{color:#000}.c:hover::after,.d:hover::after,.e::after{color:#111}
```

Output from clean-css 4.0.5:
```
$ ./node_modules/.bin/cleancss in.css -O2

.a:hover:after,.b:after{color:#000}.c:hover::after{color:#111}.d:hover::after{color:#111}.e::after{color:#111}
```
