### ISSUE TITLE
space not removed after tag in selector

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#89]
``` bat
cleancss --s0 -b -e -o out.css in.css
```

``` css
a [class^="glyph-"], a [class*=" gylph-"] {
  display: inline-block;
  text-decoration: none;
}
```

shouldn't the above minify into:

``` css
a[class^=glyph-],a[class*=" gylph-"]{display:inline-block;text-decoration:none}
```

At the moment the space after `a` isn't removed.

``` css
a [class^=glyph-],a [class*=" gylph-"]{display:inline-block;text-decoration:none}
```
