### ISSUE TITLE
Ignore specific styles

### ISSUE THREAD

**Issue by strarsis** [jakubpawlowicz/clean-css#895]
It would be nice to let clean-css skip specific rulesets/declarations/blocks e.g. by 
surrounding them with terminated comments, e.g.:

```css
/* #clean-css: ignore */
.ignore-me {
  color: transparent;
}
/* #clean-css: /ignore */
````

**Comment by jakubpawlowicz** [comment]
This is an interesting concept!

So given this input:

```css
.block-1 {
  color: #f00;
}
/* #clean-css: ignore */
.ignore-me {
  color: transparent;
}
/* #clean-css: /ignore */
.block-2 {
  margin: 0px;
}
````

should the output (let's assume we use `format: 'keep-breaks'`) be:

```css
.block-1{color:red}
/* #clean-css: ignore */
.ignore-me{color:transparent}
/* #clean-css: /ignore */
.block-2{margin:0}
````

?

Should this mechanism:

- keep the comments?
- remove whitespace in preserved block?

**Comment by studio404pl** [comment]
@jakubpawlowicz - Cześć :)

+1 to that, it would be great to just keep some sections not parsed at all, content between tags should just be passed as raw css.

**Comment by jakubpawlowicz** [comment]
@studio404pl hej! :-)

Do you think the output should still contain the `/* #clean-css: ignore */` and `/* #clean-css: /ignore */` comments? What's the "standard" for such comments anyway?

**Comment by studio404pl** [comment]
@jakubpawlowicz i think syntax that you suggest is ok. IMHO this condition's comments should not be included in parsed file.

**Comment by jakubpawlowicz** [comment]
Ok, thanks for input!

**Comment by strarsis** [comment]
In my opinion, it would be nice to not only to set ignore option per block but also other options like the aforementioned 'format: `keep-breaks`, so this kind of block can not only be used for ignoring styles but also for just setting specific options.

**Comment by jakubpawlowicz** [comment]
@strarsis we'll start with something simple here as having a per-block options would bump the complexity greatly.

**Comment by FRSgit** [comment]
@jakubpawlowicz Any updates on when can it be ready or how to help with bringing that functionality?
I came to the situation in which there is no other way but to use these ignore comments.

But have one proposal - let's use comment naming standard set by jshint as it's quite recognisable, [link](http://jshint.com/docs/) (under "ignore" title).

So example will look like this:
```css
.block-1{color:red}
/* clean-css ignore:start */
.ignore-me{color:transparent}
/* clean-css ignore:end */
.block-2{margin:0}
```

And I guess we can think of introducing single-line ignore-comments as well, but initially, it's not necessary.
