### ISSUE TITLE
issue with escaped characters in content

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#90]
When I minify bench/TP-demo.css using

``` bat
cmd /c cleancss bench/TP-demo.css -o bench/TP-demo-Clean-CSS.css --s0 -e --keep-line-breaks
```

I notice that this https://github.com/GoalSmashers/clean-css/blob/master/bench/TP-demo.css#L1457

``` css
blockquote small:before {
  content: '\2014 \00A0';
}
```

gets minified into

``` css
blockquote small:before{content:""}
```

Unfortunately, when I try to reproduce the issue with the above snippet alone, it seems to work fine, i.e.

``` css
blockquote small:before{content:'\2014 \00A0'}
```
