### ISSUE TITLE
[attribute='value' i] case insensitivity is not correctly handled

### ISSUE THREAD

**Issue by pixelastic** [jakubpawlowicz/clean-css#902]
Seems like `clean-css` is too aggressively minifying attributes selectors that contains an ` i` to denote case-insensitivity.

### Input
```css
input[value="test" i] { color:#FFFFFF; }
```

### Output
```css
input[value=testi]{color:#fff}
```

### Expected output
```css
input[value='test' i]{color:#fff}
```

### Version
I'm using the commandline `cleancss` binary, installed through `yarn add global` on Ubuntu 16.04. The `cleancss` version is 4.0.7, with the default options.

### More information

[According to MDN](https://developer.mozilla.org/en/docs/Web/CSS/Attribute_selectors), one can use the `[attribute='value' i]` syntax to make the attribute check case-insensitive.
![image](https://cloud.githubusercontent.com/assets/283419/23438449/2d5c8764-fe12-11e6-98a9-bd856ef2587c.png)
