### ISSUE TITLE
red hex color doesn't get minified into the color name

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#92]
``` css
.red { color: #FF0000; }
```

becomes

``` css
.red{color:#F00}
```

while it should be

``` css
.red{color:red}
```

You can try minifying the short hex also which has the same result.
