### ISSUE TITLE
Fix merging multi-value longhand into single-value shorthands

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#933]
Here's an example from `background` property:

```css
.block {
  background:url(one.png);
  background-repeat:no-repeat,repeat-x;
}
```

which when optimized ends up as:

 ```css
.block {
  background:url(one.png) no-repeat, url(one.png) repeat-x;
}
```

which should rather be:

 ```css
.block {
  background:url(one.png) no-repeat, repeat-x;
}
```

~or maybe second value can be dropped altogether since the shorthand doesn't declare a 2nd value?~
EDIT: in this particular case it may be OK to drop it but not in general, e.g. imagine having a two-value `background-image` declaration afterwards. So I believe the solution above is the correct one.

 ```css
.block {
  background:url(one.png) no-repeat;
}
```

**Comment by jakubpawlowicz** [comment]
Here's the opposite case:

```css
.block {
  background:repeat-x,repeat-y;
  background-image:url(one.png);
}
```

should be

```css
.block {
  background:url(one.png) repeat-x,repeat-y;
}
```

**Comment by jakubpawlowicz** [comment]
However `background-url` stands out as the only property which behaves differently when pulling into a shorthand, e.g `background-repeat`:

```css
.block {
  background: url(one.png) repeat-x, url(two.png) repeat-y;
  background-repeat: no-repeat;
}
```

equals to

```css
.block {
  background: url(one.png) no-repeat, url(two.png) no-repeat;
}
```
