### ISSUE TITLE
Transform in media queries

### ISSUE THREAD

**Issue by WebDerekh** [jakubpawlowicz/clean-css#935]
### Configuration options

```js
options = {
    level: {
	2: {
		all: true
	}
    }
}
```

### Input CSS

```css
@media (min-width:768px) and (max-width:979px) {
	.topbar {
		display: block;
		transform: rotate(20deg);
	}
}
@media (max-width:767px) {
	.topbar {
		bottom: 0;
		border-bottom: 0;
		z-index: 1027;
		transform: translate(-8px, -50%);
		display: block
	}
}
@media (min-width:768px) and (max-width:979px) {
	.topbar {
		transform: rotate(20deg);
	}
}
```

### Actual output CSS

```css
@media (min-width:768px) and (max-width:979px) {
	.topbar {
		display: block;
		transform: rotate(20deg)
	}
}
@media (max-width:767px) {
	.topbar {
		bottom: 0;
		border-bottom: 0;
		z-index: 1027;
		transform: translate(-8px, -50%);
		display: block
	}
}
@media (min-width:768px) and (max-width:979px) {
	.topbar {
		transform: rotate(20deg)
	}
}
```

### Expected output CSS

```css

@media (max-width:767px) {
	.topbar {
		bottom: 0;
		border-bottom: 0;
		z-index: 1027;
		transform: translate(-8px, -50%);
		display: block
	}
}
@media (min-width:768px) and (max-width:979px) {
	.topbar {
		display: block;
		transform: rotate(20deg)
	}
}
```

If i delete @media query in the middle, then it gets minified as expected. When I drop the transform rules from css and use other css rules, it works as correctly too. So the problem some where in this mix.

Some ideas?
