### ISSUE TITLE
Keep quotes for font names

### ISSUE THREAD

**Issue by juanpujol** [jakubpawlowicz/clean-css#94]
Im using a font with Google Web Fonts and I need to specify the font name with quotes like this:

``` css
body {
  font-family: "Lato" sans-serif; 
}
```

After minify the quotes are gone, doesn't matter if they are single or double.

Is there any option available to keep quotes?

Thanks.
