### ISSUE TITLE
Font Awesome comment not removed

### ISSUE THREAD

**Issue by hyperknot** [jakubpawlowicz/clean-css#955]
### Environment

* clean-css version - `npm ls clean-css`: 4.1.6
* node.js version - `node -v`: v6.11.0
* operating system: OS X 10.11.6

### Configuration options
cli --skip-rebase

### Input CSS

```css
.test {
    display: block;
}
/*!
 *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
/* FONT PATH
 * -------------------------- */
.test2 {
  display: block;
}
```

### Actual output CSS

```css
.test{display:block}/*!
 *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */.test2{display:block}
```

### Expected output CSS

```css
.test{display:block} .test2{display:block}
```

Font Awesome has a multiline comment which is not detected by clean-css. I wouldn't worry too much about ~200 bytes but recently files generated like the above output broke CloudFlare's minifier and our css bundle stopped working. That was clearly a bug in CloudFlare's side, but still it would be nice to just clean that comment as well.
