### ISSUE TITLE
Wrong placement of an extra comment closing

### ISSUE THREAD

**Issue by BugHunter2k** [jakubpawlowicz/clean-css#965]
### Environment

* clean-css version - `npm ls clean-css`:
clean-css@4.1.7

* node.js version - `node -v`:
v6.6.0

* operating system:
Kubuntu 17.04

### Configuration options
defaults

### Input CSS

```css
[class*='col-'] {
	float: left;
	padding-right: 30px; /* column-space */
}

[class*='col-']:last-child {
    float: left;
/*     padding-right: 0; /* column-space */ */
}


.grid {
	width: 100%;
	max-width: 1200px;
	min-width: 755px;
	margin: 0 auto;
}
```

### Actual output CSS

```css
[class*=col-]{float:left;padding-right:30px}[class*=col-]:last-child{float:left}*/ .grid{width:100%;max-width:1200px;min-width:755px;margin:0 auto}
```

### Expected output CSS

```css
[class*=col-]{float:left;padding-right:30px}[class*=col-]:last-child{float:left}.grid{width:100%;max-width:1200px;min-width:755px;margin:0 auto}
```
