### ISSUE TITLE
restructureRules not working as expected

### ISSUE THREAD

**Issue by chharvey** [jakubpawlowicz/clean-css#967]
### Environment

* gulp-clean-css version - `npm ls gulp-clean-css`: 3.7.0 (contains `clean-css` v4.1.7)
* node.js version - `node -v`: 6.9.4
* operating system: macOS 10.12.5 (Sierra)

### Configuration options

```js
var gulp = require('gulp')
var less = require('gulp-less')
var autoprefixer = require('gulp-autoprefixer')
var clean_css = require('gulp-clean-css')

gulp.task('test', function () {
  return gulp.src('test.less')
    .pipe(less())
    .pipe(autoprefixer())
    .pipe(clean_css({
      format: 'beautify',
      level: { 2: { restructureRules: true } },
    }))
    .pipe(gulp.dest('./'))
})
```

### Input Less (`test.less`)

```less
.flex-wrap--nowrap {
  flex-wrap: nowrap;
}
.flex-wrap--initial {
  .flex-wrap--nowrap; // fallback for `initial` support
  flex-wrap: initial;
}
.flex-wrap--unset {
  .flex-wrap--initial; // fallback for `unset` support
  flex-wrap: unset;
}
```

### Actual output CSS

```css
.flex-wrap--nowrap {
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap
}
.flex-wrap--initial {
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap;
  -ms-flex-wrap: initial;
  flex-wrap: initial
}
.flex-wrap--unset {
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap;
  -ms-flex-wrap: initial;
  flex-wrap: initial;
  -ms-flex-wrap: unset;
  flex-wrap: unset
}
```

### Expected output CSS

```css
.flex-wrap--nowrap,
.flex-wrap--initial,
.flex-wrap--unset {
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap
}
.flex-wrap--initial,
.flex-wrap--unset {
  -ms-flex-wrap: initial;
  flex-wrap: initial
}
.flex-wrap--unset {
  -ms-flex-wrap: unset;
  flex-wrap: unset
}
```
