### ISSUE TITLE
@keyframes slideout-null {} output @keyframes slideout-) {}

### ISSUE THREAD

**Issue by jpuncle** [jakubpawlowicz/clean-css#975]
### Environment

* clean-css version - 4.1.9
* node.js version - v8.1.4
* operating system:  Mac

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: 'ie7',
})
```

### Input CSS

```css
@keyframes slideout-null {
  0% { opacity: 1;}
  100% { opacity: 1;}
}

.null {
  animation: slideout-null 10ms;
}
```

### Actual output CSS

```css
@keyframes slideout-){0%{opacity:1}100%{opacity:1}}.null{animation:slideout-null 10ms}
```

### Expected output CSS

```css
@keyframes slideout-null{0%{opacity:1}100%{opacity:1}}.null{animation:slideout-null 10ms}
```
