### ISSUE TITLE
Selectors containing keyword 'white' change to '#fff'

### ISSUE THREAD

**Issue by esr360** [jakubpawlowicz/clean-css#978]
I am using `grunt-contrib-cssmin` and I have the following CSS:

```css
[class*="button-"][class*=“-white”]{
    background: white;
    color:#6f777b;
}
```

After minifying the above CSS I get the following output:

```css
[class*="button-"][class*="-#fff"]{background:#fff;color:#6f777b}
```

This should actually be:

```css
[class*="button-"][class*="-white"]{background:#fff;color:#6f777b}
```

Is there an option I need to pass to prevent this?
