### ISSUE TITLE
Source Url  Occur Error !

### ISSUE THREAD

**Issue by zhuzhuyule** [jakubpawlowicz/clean-css#982]
I use the plugns: [gulp-css-clean](https://github.com/scniro/gulp-clean-css)
it used [clean-css](https://github.com/jakubpawlowicz/clean-css)

中文：
我使用的插件：[gulp-css-clean](https://github.com/scniro/gulp-clean-css)，
实际也是使用  [clean-css](https://github.com/jakubpawlowicz/clean-css) 去压缩的。

### problem
（当我运行 gulp任务时）
when i use gulp task:
```js
var gulp = require('gulp');
var debug = require('gulp-debug');
var cleancss = require('gulp-clean-css'); 

gulp.task('compressCss', function () {
    return gulp.src('./target/**/*.css')
        //.pipe(gulpif(isDebug,debug({title: 'Compress CSS:'})))
        .pipe(cleancss())
        .pipe(gulp.dest('./target'));
});
```
（我发现我的 css 文件压缩后，资源路径也被压缩了）
my css files are compressed, i fund that source url has changed! 

`dictionary` like this:（目录树图）
[![PQv.png](https://imgly.net/img/PQv.png)](https://imgly.net/i/PQv)

`source files`:（四个不同层目录的css文件）
```css
/*  file1:  target/root/css/1.css   */
.test{
  background:url(../images/test.png)
}

/*  file2:  target/root/css/1/22.css   */
.test{
  background:url(../../images/test.png)
}

/*  file3:  target/root/css/1/22/333.css   */
.test{
  background:url(../../../images/test.png)
}

/*  file4:  target/root/css/1/22/333/4444.css   */
.test{
  background:url(../../../../images/test.png)
}
```

`compressed files`:（压缩后的效果，路径也被压缩了）
```css
/*  file1:  target/root/css/1.css   */
.test{background:url(../images/test.png)}

/*  file2:  target/root/css/1/22.css   */
.test{background:url(../images/test.png)}

/*  file3:  target/root/css/1/22/333.css   */
.test{background:url(../images/test.png)}

/*  file4:  target/root/css/1/22/333/4444.css   */
.test{background:url(../images/test.png)}
```
it don's i want!（这不是我想要的结果）

`want get files`:(don't change source url)（以下是我想要的结果，不要改变资源路径）
```css
/*  file1:  target/root/css/1.css   */
.test{background:url(../images/test.png)}

/*  file2:  target/root/css/1/22.css   */
.test{background:url(../../images/test.png)}

/*  file3:  target/root/css/1/22/333.css   */
.test{background:url(../../../images/test.png)}

/*  file4:  target/root/css/1/22/333/4444.css   */
.test{background:url(../../../../images/test.png)}
```
