### ISSUE TITLE
Loses one level of subdir : url(../a/b/c) instead of url(../../a/b/c)

### ISSUE THREAD

**Issue by phil69210** [jakubpawlowicz/clean-css#984]
### Precheck
 
Done

### Environment

* clean-css version - `npm ls clean-css`: gulp-clean-css@3.9.0 / clean-css@4.1.9
* node.js version - `node -v`: v6.10.1
* operating system: Red Hat Enterprise Linux Server release 7.3

#### Directory tree :

PROJECT
--- gulpfile.js
--- node_modules (directory with gulp and gulp-clean-css installed)
--- src
-------  fr
-------  css
-----------  dummy.css (size = 0)
-----------  appli
----------------  my_file.css
                    
#### my_file.css :

```css
.test {
  border-image: url(../../images/my_image.png) no_repeat 0 50%;
}
```
#### gulpfile.js :

```javascript
let gulp = require('gulp');
let cleanCSS = require('gulp-clean-css');

gulp.task('minify-css', () => {
    return gulp.src('./src/fr/css/**/*.css')
        .pipe(cleanCSS())
        .pipe(gulp.dest('./dist/fr/css'));
});

gulp.task('default', ['minify-css']);
```
#### Observations :

In this configuration and in the PROJECT directory, run : node_modules/.bin/gulp
The 2 css are generated in the "dist" subdirectories.
-> url content begins with : "../" instead of "../../". Not good !

Rename the dummy.css file in dummy.tst and run the same command.
One css is generated in the dist subdirectory (dist/fr/css/appli)
-> url content begins with "../../" : it's correct.

Copy my_file.css in the parent directory (dist/fr/css) and re-run the command.
The two css are generated in the dist subdirectories.
-> In dist/fr/css the result is correct ("../..")
-> In dist/fr/css/appli the result is incorrect : ("../")

### Configuration options

none : CleanCss is used in a gulp task without option.

### Input CSS
```css
.test {
   border-image: url(../../images/my_image.png) no_repeat 0 50%;
}
```
### Actual output CSS
```css
.test{border-image:url(../images/my_image.png) no_repeat 0 50%}
```
### Expected output CSS
```css
.test{border-image:url(../../images/my_image.png) no_repeat 0 50%}
```
