### ISSUE TITLE
8-digit hex support not available yet

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [jakubpawlowicz/clean-css#986]
(Using the web/online version of clean-css)

```css
.entry-content blockquote,
.comment-content blockquote {
	border: 1px solid #ededed;
	border: 1px solid rgba(0, 0, 0, 0.06666666666666667);
	border: 1px solid #0001;
	background-color: #fefefe;
	background-color: rgba(0, 0, 0, 0.00392156862745098);
	background-color: #00000001;
	color: #696969;
	color: rgba(68, 68, 68, 0.8);
	color: #444c;
	font-style: normal;
}
```

### Actual output CSS
```
.comment-content blockquote,.entry-content blockquote{border:1px solid #ededed;border:1px solid rgba(0,0,0,.06666666666666667);border:1px solid;background-color:#fefefe;background-color:rgba(0,0,0,.00392156862745098);background-color:#00000001;color:#696969;color:rgba(68,68,68,.8);color:#444c;font-style:normal}
```

### Expected output CSS

Actual output misses the hex hash-0001 after solid in "border". 

Options chosen are: natural order for selector sorting, all level 2 optimizations, IE7 compatibility.
