### ISSUE TITLE
`clean-css ignore` does not work with html template code

### ISSUE THREAD

**Issue by JounQin** [jakubpawlowicz/clean-css#987]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: html-loader@0.5.1 -> html-minifier@3.5.2 -> clean-css@4.1.5
* node.js version - `node -v`: v8.9.1
* operating system: macOS 10.12

### Input CSS

```css
body{
  background-color: blue
}
/* clean-css ignore:start */
<% if(pattern) {
print(`body{background-color: red}`)
} %>
/* clean-css ignore:end */
```

### Actual output CSS

```css
body{background-color: blue}
```

### Expected output CSS

```css
body{background-color: blue}
/* clean-css ignore:start */
<% if(pattern) {
print(`body{background-color: red}`)
} %>
/* clean-css ignore:end */
```
