### ISSUE TITLE
removeUnusedAtRules option drops @font-face if the usage has !important

### ISSUE THREAD

**Issue by alfaproject** [jakubpawlowicz/clean-css#989]
### Environment

* clean-css version: `4.1.9`
* node.js version: `8.9.1`
* operating system: `macOS 10.13.1`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
    level: {
        2: {
            removeUnusedAtRules: true,
        }
    },
});
```

### Input CSS

```css
@font-face {
  font-family: f;
}

i {
  font-family: f !important;
}
```

### Actual output CSS

```css
i{font-family:f!important}
```

### Expected output CSS

```css
@font-face{font-family:f}i{font-family:f!important}
```
