### ISSUE TITLE
Remove Empty option breaks FontAwesome

### ISSUE THREAD

**Issue by mightymephisto** [jakubpawlowicz/clean-css#99]
FontAwesome uses content attribute for selecting with icon to use from a font file.

``` css
.icon-glass:before                { content: "\f000"; }
.icon-music:before                { content: "\f001"; }
.icon-search:before               { content: "\f002"; }
```

_Section taken from https://raw.github.com/FortAwesome/Font-Awesome/master/css/font-awesome.css_

If compressing this file using the remove empty option, the resulting css is

``` css
.icon-glass:before{content:" icon-"}.icon-music:before{content:" icon-"}.icon-search:before{content:"\f000"}
```

_Same section taken out of the overall compressed css_

If you don't use the remove empty option, the resulting css is

``` css
.icon-glass:before{content:"\f000"}.icon-music:before{content:"\f001"}.icon-search:before{content:"\f002"}
```

_Same section taken out of the overall compressed css_

Also there has been mixed reports around stackoverflow that minified @font-face blocks don't work, interestingly the provided minified fontawesome file doesn't have a minified @font-face https://raw.github.com/FortAwesome/Font-Awesome/master/css/font-awesome.min.css
