### ISSUE TITLE
How to preserve the query param of background url?

### ISSUE THREAD

**Issue by prime89** [jakubpawlowicz/clean-css#994]
### My code
i use gulp-clean-css to optimize css file, 
```js
gulpif(isCss, cleanCSS({
            compatibility: 'ie8', 
        })),
```
 my css file is 
```css
.message{background:url(../images/about/message-mb.png?v=aaaaa) no-repeat center}
```
after optimized, the file becomes below
```css
.message{background:url(../images/about/message-mb.png) no-repeat center}
```
how to preserve the query param of backgound url?
